# Sounds Data Paper Python

## Artists List

There are multiple lists of artists. One is in the `artistsIndex` worksheet. This should presumably be the master artist list since it contains indexes for all of them.

There are also artists in other worksheets: `Venue_Artist_Event` and `Ven_Ev_Address`. The first task is to double check artist names and ensure we have a complete list with unique indexes for all artists.

First, I'm going to load the excel file and access the worksheet.

Here, I'm going to import the pandas library, read the file, and inspect the names of the worksheets.

In [1]:
import pandas as pd

In [2]:
sounds_data = pd.ExcelFile('spreadsheets/product1_data_master_rev.xlsx')

In [3]:
sheets = sounds_data.sheet_names
sheets

['Ven_Ev_Ar_Address',
 'Venue_Artist_Event',
 'Layer 1 Venues',
 'artistsGenre',
 'genreIndex',
 'Sheet5',
 'artistsIndex',
 'Venues No Address',
 'venues_with_coordinates']

Now that I have the exact names of all the sheets, I will go ahead and load the artistsIndex sheet and the other sheets I am interested in. Then I will inspect the resulting pandas data frames to find the names of the columns containing artist information.

In [4]:
artists_index = pd.read_excel('spreadsheets/product1_data_master_rev.xlsx', sheet_name='artistsIndex')
venue_artist_event = pd.read_excel('spreadsheets/product1_data_master_rev.xlsx', sheet_name='Venue_Artist_Event')
ven_ev_ar_address = pd.read_excel('spreadsheets/product1_data_master_rev.xlsx', sheet_name='Ven_Ev_Ar_Address')

In [5]:
artists_index.head()

                   Name  Index
0        Dierks Bentley      1
1  "The Italian Cowboy"      2
2           Keith Urban      3
3          George Jones      4
4           Hilary Duff      5

In [6]:
venue_artist_event.head()

,Month,Day,Year,Venue,Event_Artists,Artist_Formula,Event_Formulas,Index
0,September,10,1857,St. Mary's Catholic Church,French Mountaineer Singers,French Mountaineer Singers,NaN,1
1,June,25,1869,Menger Hotel,General Mason Farewell Party: San Antonio Bras...,San Antonio Brass Band,General Mason Farewell Party,2
2,July,4,1874,San Pedro Park,San Antonio Brass Band,San Antonio Brass Band,NaN,3
3,October,9,1874,"San Pedro Springs, Turner Hall",Tenth Texas Saengerfest,Tenth Texas Saengerfest,NaN,4
4,October,10,1874,"Casino Hall, Turner Hall",Tenth Texas Saengerfest,Tenth Texas Saengerfest,NaN,5

In [7]:
ven_ev_ar_address.head()

,Index,Month,Day,Year,Venue,Event_Artists,Address,Zip,Longitude,Latitude,Artist,Event,City,State
0,2581,January,1,1970,San Antonio Convention Center Arena,"KBER Holiday Show: Willie Nelson, Charley Pri...",601 Hemisfair Plaza Way,78205.0,NaN,NaN,Willie Nelson,KBER Holiday Show,San Antonio,Texas
1,2581,January,1,1970,San Antonio Convention Center Arena,"KBER Holiday Show: Willie Nelson, Charley Pri...",601 Hemisfair Plaza Way,78205.0,NaN,NaN,Charley Pride,KBER Holiday Show,San Antonio,Texas
2,2581,January,1,1970,San Antonio Convention Center Arena,"KBER Holiday Show: Willie Nelson, Charley Pri...",601 Hemisfair Plaza Way,78205.0,NaN,NaN,Grandpa Jones,KBER Holiday Show,San Antonio,Texas
3,2581,January,1,1970,San Antonio Convention Center Arena,"KBER Holiday Show: Willie Nelson, Charley Pri...",601 Hemisfair Plaza Way,78205.0,NaN,NaN,David Houston,KBER Holiday Show,San Antonio,Texas
4,2582,January,16,1970,San Antonio Municipal Auditorium,Vikki Carr,100 Auditorium Cir.,78205.0,NaN,NaN,Vikki Carr,NaN,San Antonio,Texas

Now, I'm going to extract the list of unique artists listed in the artistIndex sheet. I see there are 1764 total artists listed there.

In [8]:
artists_artist_index = set(artists_index['Name'].dropna().str.strip())
len(artists_artist_index)

1764

Next, I'm going to create a set data structure, which ensures that all data items are unique and avoids any duplication. I'll then get the length of the set and do an initial inspection of its contents.

I can see there are 1764 artists in the artistsIndex sheet, and that while it's a good list, there are some data issues. For example, 

```
'Ballet Folklorico de San Antonio',
'Ballet Folkloricp de San Antonio',
```

or

```
'Billy Mata & the Texas Tradition',
'Billy Mata and the Texas Tradition',
```

All this suggests some manual cleanup may be helpful, but overall the collection is generally valid.

In [9]:
unique_artists = set()
unique_artists.update(artists_artist_index)

In [10]:
len(unique_artists)

1764

In [11]:
sorted(unique_artists)

['"The Italian Cowboy"',
 '(Fools?)',
 '(TLC - cancelled)',
 '01 Blues',
 '10 Years',
 '112',
 '12 Step Rebels',
 '13th Floor Elevators',
 '214th Army Band',
 '3 Balls of Fire',
 '4 2 MD',
 '4 on the Floor',
 '7seconds',
 '98 Degrees',
 'A Perfect Circle',
 'AC',
 'ANJ',
 'Aaron Barker',
 'Aaron Carter',
 'Accept',
 'Ace Frehley',
 'Adam Bomb',
 "Adler's Appetite",
 'Adolescents',
 'Adolph Hofner',
 'Adolph Hofner and the Pearl Wranglers',
 'Adrian y Destino',
 'Aerosmith',
 'Agustin Ramirez',
 'Air Force Concert Band',
 'Air Supply',
 'Airbourne',
 'Al Gomez',
 'Al Hirt w',
 'Al Olsen',
 'Al Sturchio Orchestra',
 'Al Sturchio and His Orchestra',
 'Alabama',
 'Alan Jackson',
 'Albert Collins and the Antone Blues Band',
 'Albert Garcia',
 'Albita',
 'Alcatrazz & Odin',
 'Alex Abravanel',
 'Alex Sutherlin Project',
 'Algiers Brass Band',
 'Ali Ekber Cicek',
 'Alibi',
 'Alice Cooper',
 'Alice Gomez',
 'All Time Low',
 'All-American Rejects',
 'Alondra',
 'Altered Natives',
 'Alvin Crow and the Pleasant Valley Boys',
 'Aly & AJ',
 'Amanda Perez',
 'America',
 'Americult',
 'Amy Grant',
 'Anacani',
 "Anarchists' Convention",
 'Ancient Cross',
 'Andre Cymone',
 'Angelina',
 'Angels Grace',
 'Angerkill',
 'Anthrax',
 'Antonio Aguillar',
 'April Wine',
 'Armed Forces Bicentennial Band Concert',
 'Armored Saint',
 'Army Blues',
 'Arthur Hanlon',
 'Article of Control',
 'Arturo Sandoval',
 'Ashburn',
 'Ashlee Rose',
 'Asian Dub Foundation',
 'Asleep at the Wheel',
 'Association',
 'Aswad',
 'Atlanta',
 'Augie Meyer',
 'Augie Meyers',
 'Augie Meyers and the Western Head Band',
 'Aurellio de Hoyas and Mariachi Azteca',
 'Awaken the Fallen',
 'Axe',
 'Az Yet',
 'Azteca Intnernacional',
 'Azul & Maya',
 'Azul (Azucena Barrientos)',
 'B.B. King',
 'B.G. and Hot Boys',
 'BL Lacerta',
 'Baby Bash',
 'Bachman Turner Overdrive',
 'Backstreet Boys',
 'Bad Company',
 'Bad Religion',
 'Ball & Jack',
 'Ballet Folklorico de San Antonio',
 'Ballet Folkloricp de San Antonio',
 'Ballet Regional Mexicano',
 'Bamboleo',
 'Banda Copala',
 'Bandango',
 'Banned in Public',
 'Bar-Kays',
 'Barbara Fairchild',
 'Barbara Mandrell',
 'Barrington Levy',
 'Barry Brake (piano)',
 'Basehead',
 'Bastard Sons of Johnny Cash',
 'Be Syndicate',
 'Beach Boys',
 'Beastie Boys',
 'Beatriz Lamas',
 'Becky Hobbs and Moe Bandy',
 'Bela Fleck and the Flecktones',
 'Bellamy Brothers',
 'Ben King',
 'Ben McPeak',
 'Benny Goodman',
 'Bent Norup',
 'Berlin Opera',
 'Beto and the Fairlanes',
 'Bett Butler',
 'Better Than Ezra',
 'Better than Ezra',
 'Betty Carter',
 "Beverly Houston and Breezin'",
 'Beyond Black',
 'Big & Rich',
 'Big & Rich with Cowboy Troy',
 'Big Al Downing',
 'Big Mountain',
 'Big Walter Price',
 'Big Wreck',
 'Bill Bailey',
 'Bill Cosby',
 'Bill Engvall',
 'Billy Cobham',
 'Billy Currington',
 'Billy Joel & Elton John',
 'Billy Mata',
 'Billy Mata & the Texas Tradition',
 'Billy Mata and the Texas Tradition',
 'Billy Morgan',
 'Biohazard',
 'Black Crowes',
 'Black Market Revival',
 'Black Oak Arkansas',
 'Black Sabbath',
 'Black Sabbath featuring Ozzy Osbourne',
 'Black and Blue',
 'Blackbird',
 'Blackwater Gospel',
 'Blaine Keith',
 'Blak Fate',
 'Blake Shelton',
 'Blaque',
 "Blood 'n' Beer",
 'Bloodhound Gang',
 'Blowsing Trees',
 'Blue Man Group',
 'Blue Norther',
 'Blue October',
 'Blue Öyster Cult',
 'Blues Traveler',
 'Bo Bice',
 'Bob Dylan',
 'Bob Dylan with G.E. Smith',
 'Bob Haggart',
 'Bob James',
 'Bob Marley Festival',
 'Bobbie Cryner and Sisters Morales.',
 'Bobby "Tossin\' and Turnin\'" Lewis',
 'Bobby & Jody Jenkins',
 'Bobby Aragon Group',
 'Bobby Baker & the Longnecks',
 'Bobby Blue Bland',
 'Bobby Flores Band',
 'Bobby G & the Drive',
 'Bobby Jenkins',
 'Bobby Lloyd',
 'Bobby Martin',
 'Bobby Pulido',
 'Boerne Village Band',
 'Bombasta',
 'Bone Thugs-n-Harmony',
 'Bonham',
 'Bonnie Raitt',
 'Border Palace All-Stars',
 'Boston',
 'Bow Evil',
 'Boxcar Willie',
 'Boys II Men',
 'Boys Like Girls',
 'Brad Paisley',
 'Brand New',
 'Brandon Rhyder and Wade Bowen',
 'Brenda Russell',
 'Brian Culbertson',
 'Briggs',
 'Britney Spears',
 'Brokencyde',
 'Brooks & Dunn',
 'Brother Cane',
 'Bruce James',
 'Bubba Bartosh',
 'Bubba Littrell and the Melody Mustangs',
 'Buckcherry',
 'Bud Keefer',
 'Buddy Guy',
 'Budgie',
 'Buffalo Soldier',
 'Bullet for My Valentine',
 'Bush',
 'Butthole Surfers',
 'Byfist',
 'Café Tacumba',
 'Calhoun',
 'Campanas De America,Ram Herrera',
 'Candlebox',
 'Cano Estremera',
 'Carlos Vives',
 'Carman',
 'Carmen Munoz',
 'Carnaval de San Anto',
 'Carol Plunk',
 'Carolyn Steele',
 'Carolyn Wonderland',
 'Carrie Underwood',
 'Casey Donahew Band',
 "Cat's Cradle",
 'Catch War',
 'Catfish',
 'Cedella Marley Booker',
 'Celine Dion',
 'Centro Cultural Aztlan',
 'Cerrito',
 'Chacho & Brance',
 'Chamillionaire',
 'Charlie Daniels Band',
 'Charlie Walker',
 'Charlie and the Cool Cats',
 'Cheap Trick',
 'Cheats',
 'Cheb Tati',
 'Chente Barrera',
 'Cher',
 'Cherelle',
 'Chevelle',
 'Chick Corea (trio w',
 'Children of Bodom',
 'Chilton Vance & Texas Connection',
 'Chiodos',
 'Chris Holzhaus',
 'Chris Pfifer',
 'Chris and Judy',
 'Chris and Judy Wagon',
 'Chrissy Flatt',
 'Christopher Parker;  Wire Train',
 'Cinderella',
 'Cinderleaf',
 'Claude Morgan & the Blast',
 'Clay Walker',
 'Cleo Auiderhaar',
 'Clifford Scott',
 "Clyde's Car and the Rockets",
 'Coal Chamber',
 'Coffin Creeps',
 'Cold Sweat',
 'Coldplay',
 'Colima',
 'Collective Soul',
 'Collin Raye',
 'Commodores',
 'Concombre Zombi',
 'Concrete Blonde',
 'Conjunto Reunion de Raul Vasquez',
 'Conspiracy of Silence',
 'Conway Twitty',
 'Cool for August',
 'Corina',
 'Corrosion of Conformity',
 'Cortez Greer',
 'Cory Morrow',
 'Cory Morrow Band',
 'Costumbre',
 'Country Cavaliers',
 'Country Express',
 'Country Horizon',
 'Country Joe and the Fish',
 'Countrymen',
 'Covergirls',
 'Cowboy Mouth',
 'Coyote Dreams',
 'Craig Morgan',
 'Cranberries',
 'Creed',
 'Creed Taylor',
 'Creed Taylor and the Travellers',
 'Crimson Jazz Orchestra',
 'Crosby',
 'Cross Canadian Ragweed',
 'Cross Canadian Ragweed & Montgomery Gentry',
 'Cross Wind',
 'Cruz Arizmendi and his Orchestra',
 'Crystal Myth',
 'Curley Mays',
 'Curtis Calderon',
 'Cutting Crew',
 'Cyndi Lauper',
 'DC',
 'DJ Laze',
 'DJ Papote and the Semeneya Dance Group',
 'DJ Unk',
 'DRI',
 'Dale Jackson',
 'Damian Marley (Rasta Rapper)',
 'Damij',
 'Damn Yankees',
 'Dan Ryan',
 'Dan Seals',
 'Dangerous Toys',
 'Danny Valdez',
 'Darius Rucker',
 'Darrel Tidaback',
 'Darrell Clanton',
 'Darrell Harkins and the Love Country Express',
 'Daryl Singletary',
 'Dave Kemp and the Family Tradition',
 'Dave Koz',
 'Dave Valentine',
 'Dave Wakeling',
 'Dave Wilkins Band',
 'David Ball',
 'David Larson',
 'David Lee Garza',
 'David Lindley',
 'David Mares and Hot Tamales',
 'David Marez',
 'David Sanborn',
 'Davie Allan and the Apaches',
 'De Los Muertos',
 'De-Animator',
 'DeBarge',
 'DeWayne Toney & Rogue Moon',
 'Deadpool',
 'Deadpool (Carlos Lopez',
 'Deanna Carter',
 'Debbie Garris',
 'Deborah Harry',
 'Deborah Hay',
 'Default',
 'Deicide',
 'Del Castillo',
 'Delbert McClinton',
 'Deniece Williams',
 'Denim',
 'Denny Ezba',
 'Denny Ezba (the Goldens)',
 'Denny Laine',
 'Depeche Mode',
 'Deryl Dodd',
 "Destiny's Child",
 'Destruction Evolution',
 'Desvelados',
 'Detective',
 'Devestation',
 "Devil's Hollow",
 "Devil's Martini",
 'Dieboy',
 'Dierks Bentley',
 'Dimas Garza',
 'Dino',
 'Dio',
 'Dirty Dozen Brass Band',
 'Dirty Power',
 'Dishwalla and Seven Mary Three',
 'Dissension',
 'Dixie Chicks',
 'Dizzy Gillespie',
 'Dog Men Poets',
 'Dog Tooth Violet',
 'Dokken',
 'Don Albert',
 'Don Santiago & Flaco Jimenez',
 'Don Wallace',
 'Don Williams',
 'Doobie Brothers',
 'Dottsy',
 'Double or Nothing',
 'Doug Fesler',
 'Doug Kershaw & Trio',
 'Doug Stone',
 'Downfall Funeral',
 'Downset',
 'Doyle Bramhall',
 'Dr. Ed Hill',
 'Dr. Matt Jones',
 'Dr. Patterson Barrett & the Associates',
 'Drain S.T.H. and Vision of Disorder',
 'Dreamscape',
 'Drivin Rain',
 'Dru Hill',
 'Duke',
 'Duke Ellington and his Orchestra',
 'Duke y Azzero',
 'Dynasty',
 'E-Z-O',
 'EJB Reggae Gospel Review',
 'Eagles',
 'Earl "Fatha\' Hines',
 'East Meets West',
 'Easy Adams',
 'Echoset',
 'Ecleticism',
 'Eclipse',
 'Econoline Crush',
 'Ed Shaughnessy',
 'Eddie Gonzales',
 'Eddie Gonzalez',
 'Eddie Gonzalez and Grupo Vida',
 'Eddie Holman',
 'Eddie Money',
 'Eddy Raven',
 'Eden Burning',
 'Edward C. Garza',
 'Eisley',
 'El Caso de Pullo',
 'El Curro',
 'El International Folklorico Mexicano',
 'El Mariachi Nuevo San Juan',
 'El Rayo X',
 'Eleven Hundred Springs',
 'Eli Young Band',
 'Elida y Avante',
 'Elton John',
 'Elton John & Billy Joel',
 'Elyssia Marie',
 'Emerald House',
 'Emerson',
 'Emilio',
 'Emilio Casares',
 'Emilio Navaira',
 'Emily Gimble and the Jitterbug Vipers',
 'Emotions',
 'Engage',
 'English Beat w',
 'Enrique Inglesias',
 'Eric Clapton',
 'Eric Hisaw',
 'Eric Johnson',
 'Eric Lynn',
 'Ernesto Rodriguez',
 'Ernie Sky and the K-Tells',
 'Eskalith',
 'Esteban Jordan y el Rio Jordan',
 'Etta James',
 'Eve 6',
 'Evelyn "Champagne" King',
 'Everclear',
 'Everlast',
 'Exciter',
 'Exile',
 'Exodus',
 'Expose',
 'Eye 2 Eye',
 'Fabolous',
 'Fabulous Thunderbirds',
 'Faith Hill',
 'Fama',
 'Faron Young',
 'Faster Pussycat',
 "Fate's Warning",
 'Fear Factory',
 'Fearless Iranians from Hell',
 'Fergie Frederiksen',
 'Festus (Ken Curtis)',
 'Fictionplane',
 "Fiddlin' Frenchie Burke",
 'Fifth Army Band',
 'Fine Line',
 'Fingerprints',
 'Firehouse',
 'Five',
 'Flaco Jimenez',
 'Flaco Jimenez & Country Roland',
 'Flash',
 'Flash Cadillac & the Continental Kids',
 'Fleetwood Mac',
 'Flesh Electric',
 'Flotsam & Jetsam',
 'Fluffy',
 'Foghat',
 'Foo Fighters',
 'Footprints',
 "Force M.D.'s",
 'Foreigner',
 'Four Freshmen',
 'Four-On-the-Floor',
 'Franco',
 'Frank Garrett and His All Stars',
 'Frank Marino & Mahogany Rush',
 'Frank Rodarte',
 'Frank Rodarte & los Blues Vatos',
 'Frank Rodarte & the Alamo All-Stars',
 'Frank Rodriguez Band',
 'Frankie J',
 'Frankie Valli',
 'Frankie Valli & the Four Seasons',
 'Franz Ferdinand',
 'Freak Nasty',
 'Fred Hooter',
 'Fred Zimmerle',
 'Freddie Fender',
 'Freddy Fender',
 'Frenchie Burke',
 'Gagasdan',
 'Gallagher',
 'Galo Gutierrez & Ocean Breeze',
 'Garth Brooks',
 'Gary Allan',
 'Gary Bonnett',
 'Gary Lewis & the Playboys',
 'Gary Moore',
 'Gary Puckett & the Union Gap',
 'Gavin DeGraw',
 'Geezinslaws',
 'Gene Woods',
 'George Chambers',
 'George Chambers & the Country Gentlemen',
 'George Jones',
 'George Jones & Tammy Wynette',
 'George Porter Jr. & the Runnin Pardners',
 'George Strait',
 'George Strait,',
 'George Thorogood & the Destroyers',
 'George Winston',
 'Georgia Satellites',
 'Geronimo Trevino',
 'Gerry Gibbs & the Bitches Brew Orchestra',
 'Giant Smiling Dog',
 'Gilbert Velasquez',
 'Girls Against Boys',
 'Girls in a Coma',
 'Gloria Aguilar',
 'Gloria Aguillar',
 'Gloria Estefan',
 'Gojira',
 'Gonsemble',
 'Goo Goo Dolls',
 'Good Charlotte',
 'Gordon Lightfoot',
 'Graham Wilkinson',
 'Grand Alliance',
 'Grandmaster Flash & the Furious Five',
 'Grant Lee Buffalo',
 'Grass Roots',
 "Graverobbin' Bastards and Hellbound Hearse",
 'Gravity Kills',
 'Great White',
 'Green Day',
 'Gretchen Wilson',
 'Grey Holiday [Matt Minor (vocals',
 'Grim Reaper',
 'Groove Movement',
 'Grupo Mazz',
 'Grupo Privilegio',
 'Grupo Vida',
 'Guadalajara Symphony Orchestra',
 'Guess Who',
 'Guild and Lucid Dementia. DJs include INSOC',
 'Guitares del Sol',
 "Guns 'n' Roses",
 'Gus Hardin',
 'Guy Forsyth Band',
 'H.I.M.',
 'Hank Thompson',
 'Hank Thompson & Susan Raye',
 'Hank Williams',
 'Hannah Montana',
 'Harmsay',
 'Hassan Hakmoun',
 'Hate',
 'Hatebreed',
 'Head East',
 'Heather Leather',
 'Hector Tricoche',
 'Helix',
 'Helloween',
 'Henry Brun & the Latin Playerz',
 'Henry Lee Summer',
 'Henry Mancini w',
 'Herb Keyser',
 'Herbie Hancock',
 "Herman's Hermits",
 'Hey Monday and the Friday Night Boys.',
 'High Calibre',
 'High Lonesome Country',
 'Hilary Duff',
 'Hilda Jimenez',
 'Hired Guns',
 'Hoi Polloi',
 'Holly Dunn',
 'Homer',
 'Honor Society',
 'Houserockers',
 'Howling Bells',
 'Huey',
 'Hulda Jimenez',
 'Hum',
 'Humble Blues All-Stars',
 'Humble Pie',
 'I Ching Gatos',
 'I.O.I.',
 'IMCE Choral Group',
 'Ian Moore',
 'Icon',
 'Iggy Pop',
 'Imperial Drag',
 'Incubus',
 'Indigo Rose',
 'Infectious Grooves,',
 'Infidels',
 'Inner City All-Stars',
 'Insane Clown Posse',
 'Intocable',
 'Ipso Facto',
 'Irma Navarro',
 'Iron Maiden',
 'Italian National Opera',
 'Itzhak Perlman',
 'J. Stiles & the Cementary Hips',
 'JFJ',
 'Jaci Velazquez',
 'Jack Ingram',
 'Jack Levitt',
 'Jack Russell',
 'Jack Skiles Band',
 'Jackie Huddle',
 'Jackie King',
 'Jackson Browne',
 'Jackyl',
 'Jag Wire',
 'Jagged Edge',
 'Jai',
 'Jake Owen',
 'James & Michael Younger',
 'James Brown',
 'James Cotton',
 'James Cotton & his Blues Band',
 'James Otto',
 'Jamie Foxx',
 'Jamie McMurtry',
 'Janet Jackson',
 'Janie de La Garza',
 'Janis Martin',
 'Janus',
 'Jarrod Birmingham',
 'Jason & the Scorchers',
 'Jason Aldean',
 'Jay Eric',
 'Jazzmanian Devils',
 'Jazzworks',
 'Jeff Crissler',
 'Jeff Foxworthy',
 'Jeff Healey Band',
 'Jeremy Camp',
 'Jerry Cole',
 'Jerry Field',
 'Jerry Jeff Walker',
 'Jerry Lee Lewis',
 'Jerry Reed',
 'Jesse Gonzales',
 'Jim Cullum Jazz Band',
 'Jim Cullum and Happy Jazz Band',
 'Jim Cullum and the Happy Jazz Band',
 "Jim Cullum's Happy Jazz Band",
 'Jim Ed Brown & Helen Cornelius',
 'Jim MacFarland',
 'Jimi Lee',
 'Jimmie Kay Ramos',
 'Jimmy Cliff and his six-piece Oneness Band',
 'Jimmy Dean',
 'Jimmy Edward',
 'Jimmy Gonzalez y Grupo Mazz',
 'Jimmy Spacek',
 'Jo Dee Messina',
 'Jo Jo Gunne',
 'Joan Carroll & Footprints',
 'Joan Carroll Trio',
 'Joan Jett & the Blackhearts',
 'Joanna Ramriez',
 'Jocelyn Enrique',
 'Jody Jenkins',
 'Jody Jenkins Band',
 'Joe "King" Carrasco',
 'Joe "King" Carrasco and the Crowns',
 'Joe "King"Carrasco & Esteban Jordan',
 'Joe & the Torpedos',
 'Joe Guererro',
 'Joe McBride and Marion Meadows',
 'Joe Nichols',
 'Joe Paul Nichols',
 'Joe Piscopo',
 'Joe Posada',
 'Joe Posada Group',
 'Joe Posada y El Quito Sol',
 'Joe Reyes Quartet',
 'Joe Satriani',
 'Joe T. Campos',
 'Joe Venuti',
 'Joe Williams',
 'Joel Dilley Quintet',
 'Joel Dilley [bass] Cecil Carter [trumpet]',
 'Joey Fender and the 55s',
 'Johhny Copeland',
 'John Cafferty',
 'John Conlee',
 'John Davidson',
 'John Hanley Martinez',
 'John Holt',
 'John Kay & Steppenwolf',
 'John Legend',
 'John Magaldi',
 'John Magaldi Trio',
 'John Magaldi and Saxophonic',
 'John Mayall',
 'John Michael Montgomery',
 'John Reuben',
 'John Rich with Cowboy Troy',
 'John Waite',
 'John Watkins',
 'Johnny & Bobby Wright',
 'Johnny Bush',
 "Johnny Dee & the Rocket 88's",
 'Johnny Duncan',
 'Johnny Lee',
 'Johnny P & the Wiseguys',
 'Johnny Rivers',
 'Johnny Rodriguez',
 'Johnny Z',
 'Jokester',
 'Jon B',
 'Jon Hendricks',
 'Jon Secada',
 'Jonas Brothers',
 'Jonathan Davis (Korn)',
 'Jonathan Raveneau [violin])',
 'Jordan Knight',
 'Jordin Sparks',
 'Jorge Infante',
 'Jose Maria Perello',
 'Josh Turner',
 'Jr',
 'Jr.',
 'Juan Zaizar',
 'Juanita LaBeaux',
 'Judas Priest',
 'Judy Lynn',
 'Julian Lennon',
 'Julian Marley',
 'Julio Casas',
 'Jumbo',
 'Jungle Brothers',
 'Junior Wells',
 'Justin Bieber',
 'Juvenile',
 'K Phillips & the Concho Pearls',
 'K-Ci & JoJo',
 'KISS',
 'KKYX Great Country River Festival',
 'KTFM 1200 Squad',
 'Karen Finley',
 'Katchie Cartwright',
 'Katherine Dawn',
 'Kathleen Battle',
 'Kathy Mattea',
 'Kathy Murray and the Electrifying Kilowatts',
 'Kathy Sledge and the Sisters',
 'Katy Perry',
 'Katy Rose',
 'Ke$ha',
 'Keel',
 'Keith Davis',
 'Keith Davis Band',
 'Keith Lutz',
 'Keith Sweat',
 'Keith Urban',
 'Kelly Malone',
 'Kenny Chesney',
 'Kenny Dale',
 'Kenny Dale & Shiloh',
 'Kenny Dale & the Jimmie Mac Band',
 'Kenny G',
 'Kenny Garrett Quartet',
 'Kenny Rogers & Dottie West',
 'Kenny Seratt',
 'Kenny Wayne Shepherd',
 'Kevin Evans',
 'Kevin Fowler',
 'Kid Rock',
 'Kilamanjaro',
 'Kill Paradise',
 'Killswitch',
 'Kimberly Locke',
 'Kin of Cain',
 'King Diamond',
 'King Diamond (formerly of Merciful Fate)',
 'King Kone',
 'King Pelican',
 'Kings of Leon',
 'Kinky Friedman',
 'Kinsu',
 'Kiss',
 'Kitty Wells',
 'Kix',
 "Knock 'em Stiff",
 'Koko Taylor',
 'Kon Kan',
 'Korn',
 'Kris Kimura Quartet',
 'Krokus',
 'Kromags',
 'Krystal',
 'Kumbia Kings',
 'Kurt Griffey',
 'Kyle Turner and Richard Garcia & First Light',
 'L.A. Guns',
 'LL Cool J',
 'La Calidad',
 'La Calma',
 'La Contra',
 'La Mafia',
 'La Referencia',
 'La Sombra',
 'La Sombra Chicana USA',
 'La Tropa Colombiana',
 'La Tropa F',
 'Laaz Rockit',
 'Lady Antebellum',
 'Lady Antebellum & Billy Ray Cyrus',
 'Lake and Palmer',
 'Lakeside',
 'Lalo Gonzalez & Karen Wheeler',
 'Lalo Gonzalez & Mickey Gilley',
 'Lamb of God',
 'Larry Carlton',
 'Las 3 Divas',
 'Last of Our Kind',
 'Latin Breed',
 "Latin Player'z",
 'Laura Canales',
 'Laura Marie',
 'LeAnn Rimes',
 'Leahy',
 'Ledaswan',
 'Lee Ann Womack',
 'Lee Roy Parnell',
 'Lee Thomason Quintet',
 'Legs Diamond',
 'Leon Russell',
 'Lesley Roy',
 'Less than Jake',
 'Letty Guval',
 'Life of Agony',
 'Lifehouse',
 'Lil Troy',
 'Lil Wayne',
 'Lila Downs',
 'Lillian Axe',
 'Lillian Stanfield',
 'Limp Bizkit',
 'Linda Perry',
 'Link',
 'Lisa Lisa & Cult Jam',
 'Lisa Lopez',
 'Lita Ford',
 'Little Anthony',
 'Little Joe y La Familia',
 'Little Richard',
 'Little River Band',
 'Little Texas',
 'Little Willie & Zydeco Hitchhikers',
 'Little Willie Davis & Zydeco Band',
 'Liz Phair',
 'Lloyd Herrman [drums]',
 'Lo-Pro and Doctura',
 'Lohnny Lyon',
 'Lolita Villa',
 'Lonnie Brooks',
 'Lorenza Lory',
 'Loretta Lynn',
 'Lorrie Morgan',
 'Los #3 Dinners',
 'Los Caminantes',
 'Los Cardenales de Nuevo Leon',
 'Los Chavalozz',
 'Los Conquistadores',
 'Los Crawdaddies',
 'Los Desperados',
 'Los Desperadoz',
 'Los Espanolas',
 'Los Flamencos de San Antonio',
 'Los Gauchos de Argentina',
 'Los Jovenes',
 'Los Lobos',
 'Los Lonely Boys',
 'Los Palominos',
 'Los Paranas',
 'Los Pasajeros',
 'Los Polkeros',
 'Los Shit Magnets',
 'Los Texas Outlaws',
 'Los Tigres del Norte',
 'Los Tigrillos',
 'Los Tucanes',
 'Lou Ann Barton',
 'Lou Christie',
 'Lou Rojas',
 'Loudness',
 'Love',
 'Loverboy',
 'Lucha Villa',
 'Lucky Dube',
 'Ludacris',
 'Luis Miguel',
 'Luis Shati',
 'Luisito Carrion',
 'Luke',
 'Luke Bryan & Duelo',
 'Lustre',
 'Lydia Mendoza',
 'Lynn Anderson',
 'Lynn Anderson & Charlie Walker',
 'Lynryd Skynyrd',
 'Lynyrd Skynyrd',
 'M.D.O.',
 'M:G',
 'MIMS',
 'Machine Head',
 'Mad Temple',
 'MadMax',
 'Maddex 13',
 'Madhouse',
 'Man Mountain',
 'Man of Sorrows',
 'Mana',
 'Manana Brothers',
 'Mania',
 'Manic Shuffle',
 'Mannequin',
 'Marcus David Saenz',
 'Marcus Rubio',
 'Maria Teresa Rodriguez (piano)',
 'Mariachi Femenil Las Eréndiras de San Antonio',
 'Mariachi Infantil',
 'Mariachi Internacional',
 'Mariachi International',
 'Mariachi Jalisco',
 'Mariachi Las Campanas de America',
 'Mariachi Los Caporales',
 'Mariachi Nuevo San Juan',
 'Mariachi Vargas de Tecalitan',
 'Mariachi Vargas de Tecalitlan',
 'Mariachis Victoria Acosta and Kandi Garcia; Elizabeth "La Cantante" Brackman and Rick Balderrama; Gabe Nieto & the Jalapeño Express; "Little" Henry Lee Padilla; Pablo Urbina de la Traizion and Elemento; Tato Henriquez and Gabe Garcia',
 'Marilyn Manson',
 'Maritza',
 'Mark Chesnutt',
 'Mark Lindsay',
 'Mark Wills',
 'Marley',
 'Marshall Tucker Band',
 'Martha Wash',
 'Martina McBride',
 'Marvin Hamlisch',
 'Mary J. Blidge',
 'Mase',
 'Mason Ruffner',
 'Mastodon',
 'Matchezz and the Flames',
 'Matt Barker',
 'Matt Toon & the Big Deals',
 'Maximus',
 'Maynard Ferguson',
 'Mazz',
 'McBride & the Ride',
 'Meagan Tubb',
 'Meg and Dia',
 'Megadeth',
 'Mel Tillis',
 'Melissa Etheridge',
 'Menudo',
 'Merle Haggard',
 ...]

Now I'll look at the venue_artist_event sheet, which is the main one with all the concerts from the 1850s to the 2020s. There are 20320 unique artists in this list.

In [12]:
artists_venue_artist_event_sheet = set(venue_artist_event['Artist_Formula'].dropna().str.strip())

In [13]:
artists_venue_artist_event_sheet

{'Stillwater',
 'Dance Like Robots',
 'Dreamcastle',
 'Pocketsettas',
 'The Pursuit of Happiness',
 'Styx',
 'Roger and the Ethics',
 'Navasota',
 'Luis Shati',
 'Lou Rawls & his Aggregation',
 'Mike and the Moonpies',
 'Rocky Hernandez',
 'Soda Pop Spys',
 'Big Boy Blue',
 'Two Hearts',
 'Darrell Smith',
 'Neck Deep',
 'Cedric Burnside',
 'Oliver Buck',
 'Catherine Reed',
 'Elizabeth',
 'Christian Nodal',
 'Jim Croce',
 'Buddy Portman Fiddle Band',
 'Mortal Desecration',
 'La Fuerza del Norte',
 'William H. Smith and his Orchestra',
 'the Franklin Brothers',
 'The Ink Spots',
 'Pittsburgh Symphony Orchestra',
 'Gene Reeves',
 "Tom's Texas Groove",
 'Memories',
 'Gary Glenn and the 20X Band',
 'Mr. Hall',
 'Ken Brothers',
 'Lari White',
 'Jonathan Byrd',
 'Clarence Walker and the World Famous Coasters with Clifford Scott',
 'Fire Creek',
 'Dirty Digital',
 'Lucky Joe',
 'Grupo Ideaz',
 "Down 'n' Dirty and Mr. Nasty",
 'Billy Hamilton and Co.',
 'Benny Harp Blues Band',
 'Donice Morace',
 'Gary Bonnet',
 'Andrea Pearson',
 'Tom Gillam and Friends',
 'Good Night Ether',
 'Los Cyclones',
 'Aurora Prado',
 'Hat Trick',
 'Seminole Roots',
 'Wild Child',
 'Foriegn Arm',
 "Sergio Mendes & Brasil '68",
 'DJ Cobra',
 'Papa Roach',
 'The Dirt Boys',
 'Everlast',
 'The Sweet Temptations',
 "Paygun's Reign",
 'Eddy Baker',
 'Larry Irvine (houseband)',
 'Better Lovers',
 'Blood Moon Howlers',
 'Trio Los Pepes',
 'Jason Gerard',
 'Karen Abrahams',
 'Essence',
 'Kandace Springs',
 'Nick Zamora',
 'The Sounds of Animals FIghting',
 'Jamal Amar',
 'Mariachi Los Charros',
 'Kin of Ettins',
 'DJ Ricky',
 'Mary Taylor',
 'Gallagher',
 'The Avett Brothers',
 'Seven Simons',
 'The Williamson Family',
 'Choker Campbell & Orchestra',
 'Lonely Horse',
 'Sarah Centeno',
 'Johnnie Johnson',
 'Colin Dowling (bass). Gabby Hernandez (cello)',
 'Eye Alaska',
 'Beartooth',
 'Concombre Zombi',
 'SZA',
 'CC & the Shades',
 'Sea Sick Sailors',
 'The Texas Tenors',
 'Carlos Vives',
 'Lalo Piparro Gonzalez',
 'DK Bean',
 'Alan Jackson',
 'Janeal Sugars (soprano)',
 'Voodoo Machine',
 'Chicha Libre and Mazel Tov Kocktail Hour',
 'Max and Heather Stalling',
 'David Strauss',
 'Peter Buchi (tenor)',
 'Kevin Brown',
 'Kelvin Rueb',
 'Broken Soul',
 'Miss Nessie & the Ear Food Orchestra',
 'DJ Promote',
 'Alan Fisher',
 'Leopold La Fosse (violin)',
 'Dance Gavin Dance',
 'Mindz of A Different Kind (MDK)',
 'Rick Cavender',
 'The Primetime Jazz Orchestra',
 'Patti Austin',
 'San Antonio Symphony featuring Hams Richter-Haaser (piano)',
 'Metallica',
 'TI',
 'Bud Powell Trio',
 'Geoff Moore',
 'Herb Hall & Friends',
 'Dumb Belles',
 'Russell Clepper',
 'Lorne Greene',
 'Passing Strangers Emilio Navaira',
 'Al Patino (clarinet)',
 'Kilgore Trout',
 'Miss Nessie & Ear Food Orchestra',
 'Mark Chandler',
 'Houston Symphony Orchestra',
 'The Band Kara',
 'Raymond y Rayo',
 'Los Impostores de Nuevo Leon',
 'Gary the Showman',
 'The Johnny Five',
 'Gene Lloyd Orchestra',
 'Lemmings',
 'Estudio 1070',
 'Clay Baker & the Texas Honky Tonk Band',
 'Julio Dominguez Orchestra',
 'Priscilia Hallberg',
 'Crimson Glory',
 'DC Talk',
 'Patrick Glenn',
 'Alamo City Wranglers',
 'Alcatrazz & Odin',
 'the Psychoholics',
 'Oscar Levant - All Gershwin Program',
 'Jazz Orchestra of San Antonio',
 'Katy Perry',
 'Gerry Gibbs & the Bitches Brew Orchestra',
 'Matt Kersch',
 'Joe Jama',
 'Calmeca',
 'Nazareth',
 'Changes de Ernie Gutierrez',
 'The Inspirational Choir of Coliseum Park Baptist Church',
 'Toman Brothers',
 'DJ Stan Elliott',
 'Dylan Riley',
 'Woody Pines (Zack Pozebanchuck [upright bass]',
 'Radio La Chusma',
 'Xscape',
 'Dianne Claffey (soprano)',
 'Buck Wheat and his Orchestra',
 'Verbal Jordan (trumpet)',
 'Girlschool',
 'Arsenio Hall',
 'Mariach Gentil',
 'Bison BC',
 'Front Line Assembly',
 'Forever Miles',
 'The Jersey Tenors',
 'Ice Nine Kills',
 'Liverpool Legends',
 'The Dangerous Summer',
 'El Bigoton Castro',
 'Jordan Knight',
 'The Meadows',
 'Michael Winslow',
 'Gut',
 'Flash Flood Watch',
 'Magneto',
 'Acid Mother Temple',
 'Nosedive',
 'Soli Chamber Ensemble',
 'The Seale Sisters',
 'EJB Reggae Gospel Review',
 'Jason James Band',
 "Ian Moore & Moment's Notice",
 'La Sombra',
 'Michael Martin & the Infidels',
 'Los Tres',
 'The Outfield',
 'the Eli Young Band',
 'Mickey Gilley/Johnny Lee',
 'Freddie King',
 'K Phillips & the Concho Pearls',
 'Al Sturchio and his Orchestra',
 'Donald Willing (organ)',
 'Statesboro Review',
 'Ecunemical Concert',
 'Doc Ross and his Orchestra',
 'Jubel-Heirs',
 'Coyote Dreams [Mike Ryan (guitar',
 'Rocky King and the Dancehall Cowboys',
 'Aaron Prado & the Primetime Jazz Orchestra',
 'Glen Campbell',
 'Superband featuring Stanley Clark',
 'Evan Felkner',
 'Dong Ill-Shin (organ)',
 'Hepcat',
 'Santana',
 'Miss Lavelle White and the L Men',
 'Malo',
 'Hands Like Houses',
 'Speck Rhodes',
 'Lourdes Perez',
 'the Chantels',
 'Carman',
 'Bangor Flying Machine',
 'The Great Dvide',
 'Dee Mueller',
 'Barbara Fairchild',
 'Las Nubes',
 'Deadly Omens',
 'Perfect Strangers',
 'Joanna Connor',
 'Gera Mx',
 'The Ken Williams Trio',
 'Trio Cantares (Henry Gomez, Antonio Rodriguez Romero, Ismael Rivera)',
 'Elmore Morris',
 'Hootie & the Blowfish',
 'JD Clark',
 'X',
 'Leslie Kline',
 'Our Gang and the Rascals',
 'Mother Earth',
 'The Beat Dolls',
 'Plastic Patrick',
 'Beau Rodriguez',
 'Memento',
 "St. Mary's Chamber Choir",
 'The Dreamers quartet (Edward Cooper',
 'Emilio Navaira IV',
 'Distorted Ends',
 'Henry Brun & the International Trio',
 'Gleaming',
 'American Legion Post 177 Band',
 'Tora Tora Tora',
 'Roy Medina Knowles',
 'Love',
 'Checnho Lopez',
 'Arma Musica',
 'Mariachi International',
 'Cherry St.',
 'Joseph Geczy Company',
 'Clay Crosse',
 'Whiskey Myers',
 'Higer Balm and the Threadgills',
 'Flashpoint',
 'DjJ Melon',
 'Marshall Barnes',
 'Paul McCartney',
 'Flatliner',
 'Narita',
 'Vanessa Lynn Bird',
 'Conjunto de Lupe Saenz',
 'Shy Blakeman and the Whisky Fever Band',
 'Oso Oso',
 'Sean K. Preston',
 'Last of Our Kind',
 'Javier Rosas',
 '0.08',
 'Country CrossRoads',
 'Carter Family',
 'Wilbert Beasley and Body & Soul and River City All-Stars.',
 'Ron Wikso',
 'Omen',
 'Penile Pepper Smiles',
 'Regios de Nuevo Leon',
 'The Manana Brothers',
 'Marilyn Horne',
 'Mark Harrell (baritone)',
 'Cripple Creek',
 'Jason Allen',
 'Leon Bridges',
 'Micro',
 'The Buckaroos',
 'Maze',
 'Tony Booth and the Marcy Brothers',
 'Keri Leigh & the Blue Devils',
 'Little Henry and the Laveers',
 'Spank',
 'Texas Radio',
 'Kenny Orts',
 'Incarnate Word Singers',
 'Donald Fagen',
 'Edgar Winter & White Trash',
 'Spectrum A.P.F.',
 'Mariachi Los Pasajeros',
 'Heather Go Psycho',
 'Last We Fall',
 'Katy Hudson',
 'Drugdealer',
 'the San Antonio District Chorus',
 'Ben Balmer',
 'Amilia k Spicer',
 'Hagers',
 'Meredith Ridgway (piano)',
 'Kevin Costner & Modern West',
 'Eighth Cavalry Band (conducted by Wilhelm Marx)',
 'Neytion',
 "James Brown and the J.B.'s",
 'Dave Mason',
 'Chenete Barrera',
 'Mike Landscoot',
 'the Martyrs',
 'Matt Charles',
 'Jan Halsema (saxophone)',
 'Rosilee',
 'William James Ross (organ)',
 'Jose Luis Rodriguez',
 'Social Trauma',
 'Lisa Fischer',
 'The Crusaders',
 'Bryan Duncan/Bob Carlisle',
 'Origami Angel',
 'Elton Dan & The Rocket Band',
 'b.',
 'The Bluehouse',
 'Love Hate Hero',
 'Bloodshot',
 'John McVey',
 'Divine Heresy',
 'The Desperadoz',
 'Big Ike & Band',
 'Lassie',
 'Rev. Lil Timmy',
 "Lydia Can't Breathe",
 'July',
 'Gospel Harmonizers',
 'Glenn Lee and his Orchestra',
 'Yosk and Yimmy',
 'Bocafloja',
 'the Mountaineers',
 'John Christopher Way Band',
 'the Thomas Jimenez Band',
 'Brandon Jenkins',
 'Lord August and his Fountains of Life',
 'RAP Ferreria',
 'Psycho Candy',
 'Jeremy Richards Band',
 'Mainstream',
 'Davie Allan and the Apaches',
 'Fred Zimmerle',
 'TC Taylor',
 'Eva Ybarra y su Conjunto',
 'Shasa',
 'David Mares',
 'Dr. Frank Speller (organ)',
 'Shaun Groves',
 'The Silent Majority',
 'Ed Guymer and his Patriotic Band',
 'Kehlani',
 'John Magaldi and the Quiet Jazz Trio',
 'Mark Weber y Los Cuernos',
 'Jay-Z',
 'Innerview',
 'Mick Hernandez and the Texas Silverados',
 'Marcel Marceau',
 'Los Gauchos de Argentina',
 'Wimberley Volunteer Fire Anys',
 'Guitar Red & his Orchestra',
 'Head Furst',
 'Bill Anderson',
 'Rick Stockton',
 'Shawn Pittman Band',
 'AC/DC',
 'ulations',
 'Newsboys',
 'Mimi Benzell',
 'Hugh Fadal Band',
 'The Skyliners',
 'Bluecreek',
 'Los Unicos',
 'Neil Young (cancelled)',
 'Title Fight',
 'Los Cuatro Vientos de Jimmy Bejarano',
 'Bobby Stone and the Newsboys',
 'The Cruise Control Band',
 'Gabe Rhodes',
 'Freaks on a Leash',
 'Jacob Guererro (bass)]',
 'Magda and Roberto',
 'Mothica',
 '214th Army Band',
 'Doug Strahan',
 'Koast',
 'The Boecks',
 'Sam Kinison',
 'Hans Frank (Glambilly)',
 'The Lost and Nameless Orchestra',
 'Kyle Turner',
 'Jay Aaron',
 'Marisela',
 'Moe Bandy & Joe Stampley',
 'Key Taylor',
 'Blanco',
 'Fox Motel',
 'Red Beard Wall',
 'Os Mutantes',
 'Mundungus',
 'Exit Gate',
 'Downset',
 'Sojourn',
 'Max-A-Million',
 'True Body',
 'The Dirty River Jazz Band',
 'Stuck Mojo and Machine Head',
 'Tony Rico',
 'King Remo Sound System',
 'Joe McBride',
 'Kaeo',
 'Steel Porn Rhino',
 'Gary P. Nunn and the Sons of the Bunkhouse Band',
 'Immortal Technique',
 'Andy Williams',
 'The Band of Heathens',
 'T Lew Tha Vato',
 'Mike McColgan and the Street Dogs',
 'Joel Guzman',
 'Wildstreak',
 'Skn Kvr',
 'Vinyl Williams',
 'Annointed',
 'Nic Ether',
 'Eisley',
 'New Holiday',
 'Red Foley',
 'Charlie Robison',
 'Fire pm the Mountain Cloggers',
 'The Marias',
 'Buddy Clark',
 'Lisa Marie Sharp and Badd Medezine',
 'Sweet Sensation',
 'San Antonio Chordsmen',
 'Lighter Shade of Brown',
 'Dezigual',
 'The Defiled',
 'Manuel Mier',
 'Michael Mitchell and the Max',
 'Zodiac Mindwarp & Love Reaction',
 'Jerry Espinoza (saxophone)',
 'Ten Inch Men',
 'Jay Dominguez and the Stoney Ridge Band',
 'The Reen',
 'Black Angels',
 'Cadillac Ranch',
 'Glass Cloud',
 'Ballet Fiesta de Mexico',
 'Slinece the Messenger',
 'Poppy x PVRIS',
 'Z-Axis',
 'Kids in the Way',
 'Peacefield',
 'Brownsville Station',
 'Kylesa',
 'Invicto',
 'Link and Chain',
 'Dennis Awe (organ)',
 'New Ridaz',
 'Zoso (Led Zeppelin tribute)',
 'Sir WIlliam',
 'Texas Lutheran Concert Band',
 'Honky Tonk Mariachi',
 'TV Girl',
 'Walt Wilkins & The Mystiqueros',
 'Gable Bradley',
 'Erroll Garner Trio',
 'Miss Nessie & the Tin Can Trio',
 'Apache',
 'George Ransom',
 'Keith Urban',
 'Rodney Warner & Bluz Express',
 'Rev. Blues Band',
 'Loosey Laduca',
 'Chacha Zaavedra',
 "Burg's Mill",
 'Jerry Reed',
 'Monte Carlo Orchestra',
 'Herb Alpert & the Tijuana Brass',
 'Luna Nueva with Tara Linda & Gilbert Reyes',
 'Cristina Ortega with John Meadows',
 'Itzhak Perlman',
 'Nicholas Brothers',
 'Big Dippers and Swaziland White Band',
 'Trio Tariacuri Los Dixsons',
 'Bedlam',
 'La Fabrica',
 'Eric Scortia & Vital Organ',
 'Cory Morrow',
 'Bene Medina y su Conjunto Águila w/ guests: \u202fSantiago Jimenez Jr.',
 'Kaoma',
 'Nakia',
 'Jay Perez/Grupo Vida',
 'Paul Cauthen',
 'TWRP',
 'Robert de Gaetano (piano)',
 'Gene DeLisa',
 'Florence Tempest',
 'Zuliema Garcia',
 'The Toro Flores Quintet',
 'Pancho Charro Avitia',
 'Justin Boyd',
 'Steven Wright',
 'Age of Reason',
 'Cones Sisters',
 'Los Hermanos Deleon',
 'Litzbomb',
 'Martin Schwacha',
 'Rammstein',
 'Phil Keaggy',
 'Caustic Mestizo',
 'Susan Torres with Conjunto Los Pinkys',
 'The Tejas Brothers',
 'Ryko Wilson',
 'Lil Scrap',
 'Jimmy Webb',
 'Dave Meyer',
 'Middlefinger',
 'Schertz United Methodist Choir',
 'Larry Williams and his Orchestra',
 'The Whirlybirds',
 'Roadside Libby',
 'Vintage Pictores',
 'Frankie Beverly',
 'Diplo',
 'Skum',
 'Commandos',
 'Mitch McVicker',
 'Blood Engine',
 'Pancasan',
 'John Lee Hooker',
 'Larry Lange and his Lonely Knights',
 'I Remember Atlantis',
 'Immortal Guardian',
 'Cheyenne KC',
 'Ralph White',
 'Chamber Arts Choral Society',
 'Dan Carillio and Common Good',
 'Girl Ultra',
 'Dale Keith',
 'George y Mague Dueto',
 'Dewey Redman',
 'Race Villarreal & Real Me',
 'Gorky Park',
 'La Campana',
 'Alberto Soliz y su Conjunto',
 'Tony Molina y Grupo Kumbe',
 'Uncle Cracker',
 'Kerosene Shores',
 'San Antonio Symphony Orchestra featuring Yo-Yo Ma',
 'Short Shorts',
 'San Antonio Youth Chorale',
 'Jackson Parten',
 'Ray Charles & Neal McCoy',
 'Driver',
 'Grupo Elusion',
 'Topazz',
 'Temptations',
 'National Band of Texas',
 'Lunachicks',
 'Forester Sisters',
 'Ruth Bingaman Smith (piano)',
 'Avett Brothers',
 'Iron and Wine',
 'Spec Rhodes',
 'SS Alexander',
 'Tommy Genesis',
 'Rick Sikes & Band',
 'Blinde Side',
 'Catbamboo',
 'The Imperials',
 'Jeanne Robertson',
 'Noe Pro',
 'Intentions',
 'Eddie Lalo Torres y su conjunto',
 'Solarized Trio',
 'Cephalic Carnage',
 'Ringo Starr',
 'Cecilian Choristers',
 'Dick Jurgens and his Orchestra',
 'Jim Rose Circus',
 'Express Blues Band',
 'Skyfox',
 'Richard Marx',
 'Michael Johnson',
 'Slaughter Witch',
 'Grupo Mirado',
 'Pat Byrne',
 'Heller Moon Horizon',
 'Tijuana Brass',
 'Les Parent',
 'Lynnie and Friends',
 'Joel Dilley [bass] Cecil Carter [trumpet]',
 'The Speer Family',
 'Dharius',
 'Too Smooth',
 'Harlandale ISD Mariachi',
 'Elida y Alante',
 'Blind Sacrifice',
 'Big Deal',
 'Fuerza Regida',
 'The King William Brass Band',
 'Shalamar',
 'The Followthrough',
 'Zero',
 'Linda Vera Y Su Gran Conjunto Tropical',
 'Matchbox Twenty',
 'Asuncion Granados',
 'Dim Lit Daylight',
 'Keith Urban (2 shows)',
 'Hank Williams and the Drifting Cowboys',
 'Secret Six',
 'Los Carnales del Chapparo Solis',
 'The Front Bottoms',
 'Chris Holzhaus',
 'Orlando Puntilla Rios',
 'Los Conquistadores',
 'Emporium',
 'Latin Playerz',
 'Popskull',
 'Master Four Quartet',
 'Billy Bright Trio',
 'Jan Howard',
 'Lackland Contemporary Music Ensemble',
 'Matt Kitchen',
 'Val Jones and the Sundowners',
 'Jeff Lorber',
 'The Las Bandoleros',
 'Josh Alan',
 'Lillian Stanfield',
 'Matt Toon & the Big Deal',
 'Screamer',
 'La Sombra Chicana USA',
 'Kotsie Keith Orchestra',
 'Audio',
 'Requiem Rust',
 'Latex Duplex',
 'Bus 52',
 'Rick Rice Band',
 'El Eumbon',
 'Exeter',
 'Deep in the Heart',
 'Eco de Mexico',
 'Nico Canada',
 'Denny Brooks',
 'Chris Perez',
 'Mark Rubinstein Jazz Trio',
 'Hassan Hakmoun',
 'Valerio Longoria Sr. and Jr. y Sus Conjunto',
 'Boxmasters',
 'Chazz Emile Bessette',
 'SA Community Band',
 'JSquared',
 'KiiKii Star',
 'Relent',
 'Justin Hayward (Moody Blues)',
 'Anna Russell',
 'Mental Hopscotch',
 'Eye-to-Eye',
 'Billy Porter',
 'Switch',
 'Hermann Sons German Band',
 'Ronald Wilkins (trombone)',
 'The Jazzmanian Devils',
 'Excellencia de Houston',
 'Mi Casa Su Casa',
 'Hawkshaw Hawkins plus extra added attraction - George Jones',
 'Jo Koy',
 'Mary Lattimore (harp)',
 'Jerry Seinfeld',
 'Bess Hieronymus (piano)',
 'Dead or Alive (Bon Jovi tribute)',
 'Easy Adams and the Texas Top Hands',
 'Solarized',
 'Chris Stapleton',
 'Machismo',
 'Los Cinco Dudes',
 'Red Allen and Paul Barbario',
 'DJ Gen',
 'David Holt',
 '1 Ocean',
 'Nat Garcia',
 'Belay My Last',
 'Burgundy',
 'Atlantic/Pacific',
 'Los Cardenales',
 'Hank Snow',
 'Andy Roberts',
 'Selestial Alcocer',
 'Skinny Puppy',
 'Atlanta Rhythm Section',
 'Country Charley Pride & the Westernaires',
 'Los Yo Yos',
 'The Walk Offs',
 'Chingy',
 'Bucky Payne',
 'The Cone Sisters',
 'Janet McLaughlin',
 'Snake Father',
 'Chris Jungle',
 'Riley Green',
 'Rico and Fred Cavazos',
 'Paul Vidal',
 "The Obernkirchen Children's Choir",
 'The Gondoliers',
 'Amy Morriss',
 'Alamo Heights High School Band',
 'Jack Walker & the Five Lovers',
 'Hans Frank El Gallo',
 'Steppenwolf',
 'Ignoramoose',
 'Cashmo',
 'Miami Sound Machine',
 'Ripped',
 'KTD Official',
 'Green Gasoline',
 'The Fabulous Thunderbirds',
 'Grupo Presenzia',
 'Parliament/Funkadelic',
 'Kevin Geil and Co.',
 'Night Train',
 'StrayKat',
 'Porter Waggoner',
 'Emilio Casares',
 'Monte Warden and the Dangerous Few',
 'Straight Out of Line (Godsmack tribute)',
 'Bonner Rhae',
 'Homeboy Sandman',
 'Patty Loveless & Travis Tritt',
 'England Dan & John Ford Coley',
 'San Antonio Symphony presents Fiesta Pops',
 'Dem Vackra',
 'The Ange K Band',
 'Sunjammer',
 'Truth',
 'Tombs',
 'Pearl Jam',
 'Firehouse',
 'Buckwheat Zydeco',
 'Johnny Z',
 'Sideways Sumlin',
 'Black Rose Garden',
 'Crooks',
 'Curly Mays',
 'Donnie D',
 'Flashback',
 'Dirty River Dixie Band',
 'Rene y la Clave',
 'MCHLS & NEDO',
 'Raven',
 'Amnesia',
 'The Teague Brothers',
 'Mos Generator',
 'Mance Lipscomb',
 'Chk Chk Chk',
 'Jerry Jorrico',
 'Voracious',
 'Draw the Line (Aerosmith tribute band)',
 "Quitty and the Don'ts",
 'American Classic Music Festivals Choir Competition',
 'Marshall Law',
 'Brady Peterson',
 'Vicky and the Vengents',
 "St. Philip's College Concert Choir",
 'Willie Jaye',
 'Pop Evil',
 'Dorothy Maynor (soprano)',
 'Franklyn De Prez',
 'Beale Brothers',
 'Dan del Santo and the Professors of Pleasure',
 'Thraxx FOG',
 'Gloria Dei Cantores',
 'Dave Wagner Group',
 'Courtney Campbell',
 'Satyricon',
 'Leila Farid',
 'The Whitemore Sisters',
 'Tan Mala',
 'Asteroth',
 'Linkin Park',
 'Jeff Watts',
 'Maud Powell (violin)',
 'Linda Fay Casey (piano)',
 'Michael Carey',
 'Otis and the Zydeco Elevators',
 'Texas Eagles',
 'Paul',
 'Good Ole Country',
 'Eva Ybarra',
 'Bop Kings',
 'Glenn Yarbrough',
 'Michael Ibrahim',
 'Jesse and the Satinliners',
 'Stephanie Westney (violin)',
 'Boys Choir of Harlem',
 'The Black Doves',
 "St. Mary's University Glee Club",
 'David de Anda Xelencia',
 'Ryan Edwards',
 'Texas Jim and his Lone Star Cowboys',
 'Violent Femmes',
 'Juan Reyes Orchestra',
 'Mat Kearney',
 'Roger Critchett (piano)',
 'Johnny Lyon and the Country Nu-Notes',
 'SAC Flute Ensemble',
 'Sevendust',
 'Ray Anthony and his Orchestra',
 'Los Rayos de Sol',
 'Temple of Love',
 'The Leisuremen',
 'Rumba King',
 'Skatterman',
 'Billy Joel',
 'Requiem Dust',
 'Patsy Coleman',
 'Bill Green',
 'Fleshrot Sodomy',
 'Glen McKay Light Show',
 'Randy Houser',
 'NicK Hernandez & Wild Horses',
 'The Plunkett Family',
 'Ken Medema',
 'Anne Murray',
 'The Greencards',
 'Jorge Alejandro and La Paz',
 'Paul Neighbors and his Orchestra',
 'Troy Floyd Orchestra',
 'George Winston',
 'Ty Dillon and Six Echo',
 'Mariachi Azteca de Bejar',
 'In June',
 'Crucial Riddim',
 'Mary Lewis and Southern Chorus',
 'Willie Dixon',
 'MC2 and the Soul',
 'Roland Ryan',
 'The Jinx',
 'Jason Christopher Trevino',
 'Aaron Ambrosio',
 'Tony Rozance',
 'The Pear Ratz',
 'John Fogerty',
 'Spiritbox',
 'Joe Venuti',
 'Soak',
 'Linda Mountain',
 'Gerald Klickstein',
 'Chris and Judy Wagon',
 'E Rex',
 'Los Rumores',
 "James O'Gwynn",
 'Scorpions',
 'Broseph',
 'Little Steven & the Disciples of Soul',
 'The Reprecussions (Jim Farmer and Charles Chia)',
 'St. Paul Methodist Choir',
 'Wimberly Volunteer Fire Ants',
 'Gloria Gaynor',
 '21st Annual Balcones Heights Jazz Festival',
 'Oscar Hernandez y Su Conjuunto',
 'Rubén Vela Jr. y Su Conjunto',
 'George R. Gregory (organ)',
 'Chalito Johnson y los Paisanos',
 'Glorified Voices',
 'Big Walter Price',
 'Jordan Brothers Jazz Band',
 'Memphis Kee',
 'Al Tucker and his Orchestra',
 'Sky',
 'C-Kan',
 'Melody Wranglers',
 'Tropicalismo Apache',
 "Flying A's",
 'Tom McMasters',
 'Tex Beneke & the Modernaires',
 'James Montgomery Band',
 'Force',
 'The Mike Ellis Band w/Dee Dee Williams',
 'Keith Richards',
 'Cherelle',
 "Hollywood Gods N' Monsters",
 'Augie Myers)',
 'Jay McShann & His Decca Orchestra; Jimmy Washington; Jessie Pryce',
 'Johnny Dellgondo y Su Conjunto',
 'Eddie & the All-Niters',
 'Espre',
 'Fred Ramirez Trio',
 'The Projx',
 'Big Walter and his Thunderbirds',
 'Dennis Quaid & the Sharks',
 'Palo Alto College Conjunto',
 'Armando Tejeda',
 'Greg Trooper',
 'Inocencia',
 'Jessee Lee',
 'Inner View',
 'Jerry Riviera',
 'Cody Cannon (Whiskey Myers)',
 'Bonnie Barnard & the Infidels',
 'Rings of Saturn',
 'Los Trobadores de Virginio Castillo',
 'An Evening with Yes',
 'Brynn Marie',
 'Leroy Sha Na Na',

In [14]:
len(artists_venue_artist_event_sheet)

20320

Finally, I look at the ven_ev_ar_address sheet. There are 11009 artists in this list, which focuses on the core years from 1970 to 2009. Over half the concerts in the data set are in these years.

In [15]:
artists_ven_ev_ar_address_sheet = set(ven_ev_ar_address['Artist'].dropna().str.strip())

In [16]:
len(artists_ven_ev_ar_address_sheet)

11009

Now, I'll update the unique artists set with the results from the two other sheets. By adding them to a set, duplicates will be eliminated. The length of the entire set is now 20419. 

This suggests that there are 99 artists somewhere that are not in the master concert sheet. Most likely these are artists that got typos edited in one sheet but not in another.

In [17]:
unique_artists.update(artists_venue_artist_event_sheet)

In [18]:
unique_artists.update(artists_ven_ev_ar_address_sheet)

In [19]:
len(unique_artists)

20419

To find out which are these 99 artists, I use a set difference operation. I verify it by checking the length of the resulting set. It is 99 artists. This suggests a need to investigate this particular group of names as they are inconsistent or problematic in some way.

In [20]:
only_in_artists_index = (artists_artist_index - artists_ven_ev_ar_address_sheet - artists_venue_artist_event_sheet)

In [21]:
only_in_artists_index

{'"The Italian Cowboy"',
 '(Fools?)',
 '(TLC - cancelled)',
 '01 Blues',
 '7seconds',
 'AC',
 'Al Hirt w',
 'Al Sturchio and His Orchestra',
 'Better than Ezra',
 'Bobby "Tossin\' and Turnin\'" Lewis',
 'Bobby Baker & the Longnecks',
 'Campanas De America,Ram Herrera',
 'Charlie and the Cool Cats',
 'Chick Corea (trio w',
 'DC',
 'Dave Wakeling',
 'Deborah Hay',
 'Earl "Fatha\' Hines',
 'Emerson',
 'Emotions',
 'English Beat w',
 'Evelyn "Champagne" King',
 'Frank Rodarte & los Blues Vatos',
 'Frank Rodarte & the Alamo All-Stars',
 'George Jones & Tammy Wynette',
 'George Strait,',
 'Hannah Montana',
 'Hate',
 'Henry Mancini w',
 'Infectious Grooves,',
 'Jim Cullum and Happy Jazz Band',
 'Jim Cullum and the Happy Jazz Band',
 "Jim Cullum's Happy Jazz Band",
 'Joe "King" Carrasco',
 'Joe "King" Carrasco and the Crowns',
 'Joe "King"Carrasco & Esteban Jordan',
 'Joe Reyes Quartet',
 'Joel Dilley Quintet',
 'Jr.',
 'Kiss',
 'LeAnn Rimes',
 'Less than Jake',
 'Lynn Anderson & Charlie Walker',
 'Lynryd Skynyrd',
 'Mariachi Las Campanas de America',
 'Mariachis Victoria Acosta and Kandi Garcia; Elizabeth "La Cantante" Brackman and Rick Balderrama; Gabe Nieto & the Jalapeño Express; "Little" Henry Lee Padilla; Pablo Urbina de la Traizion and Elemento; Tato Henriquez and Gabe Garcia',
 'Mike Ellis & Funtones',
 'Mike Ellis & Jackie Huddle',
 'New Christy Minstrels w',
 'Paul Elizondo and His Orchestra',
 'Pauline Oliveros',
 'Perry Como w',
 'Pete Fountain and his New Orleans Jazz group',
 'Porter Waggoner & Dolly Parton',
 'PreZence',
 'Ramiro Cervera and his Orchestra',
 'Randy and Ernie Garibay and West Side Horns',
 'Rare Earth and Sugarloaf)',
 'Rock All-Stars (members of Iron Butterfly',
 'Roll Cherry Blues',
 'Roy Haynes and Mirsalov Vitous)',
 'S.A. Symphony',
 'SA Symphony',
 'Sammi Smith & Roy Head',
 'Sammy Davis',
 'San Antonio Symphony "Star Light" Concert',
 'San Antonio Symphony presents Virgil Fox (organ)',
 'San Antonio Symphony with guest conductor David Gilbert',
 'Sara Jordan Powell',
 'Selena and La Sombra',
 'Shirley Jones w',
 'Smothers Brothers w',
 'Steve James & the Vocalions',
 'Stoney LaRue',
 'Tanya Tucker w',
 'The Air Force Band of the West',
 'The Cones Sisters',
 'The Deftones',
 'The Jim Cullum Jazz Band',
 'The Offbeats',
 'The Sergio Lara',
 'The Smith Brothers',
 'The Toadies',
 'The Tyrones',
 'The US Air Force Band of the West',
 'TobyMac',
 'Tomren Shannon',
 'Trick Daddy and 112',
 'We the Kings',
 'Willis Alan Ramsey,',
 'Zap',
 'dc talk',
 'fIREHOSE',
 'the Bett Butler',
 'the Regency Jazz Band',
 'the San Antonio Symphony',
 'the Suspects',
 'the Swindles',
 'the West Side Sound'}

In [22]:
len(only_in_artists_index)

99

Next, I'm going to create a lookup dictionary for artists with their index. This will make it very fast to look up whether an artist already has an index or not.

The rationale for this is as follows. We have 1769 listed artists with indexes already assigned. We don't want to reassign unique indexes; these may be in use somewhere already, so we want to retain unique indexes for all artists that already have one assigned. However, it is clear we have a lot more artists in the data than have these inexes assigned. So as we look over the unique list of all artists, we are going to want to look up whether it has an index, and if not assign it a new one. To make this an efficient and fast task, it's helpful to create a lookup dictionary in advance.

In [23]:
artist_to_index = dict(
    zip(
        artists_index["Name"],
        artists_index["Index"]
    )
)

I'd like the artists to be sortable chronologically in some way, so I'm going to add first appearance and last appearance information for them. To do this, I need to take the current text "Year", "Month", and "Day" columns and convert them into pandas datetime objects.

First, it occurs to me we may be able to save some time. The Ven_Ev_Ar_Address sheet was derived from the Venue_Artist_Event sheet, so I want to see if there are any aritsts in the first that are not in the second. I use a set difference operation. The result is an empty set. There are no artists in the first sheet that aren't in the second sheet. So I can do the date operation entirely on the second set.

In [24]:
artists_ven_ev_ar_address_sheet - artists_venue_artist_event_sheet

set()

Next, I'm going to use a utility I wrote some time ago that transforms string dates into ISO format date objects. Then I'll apply the method to every row in the venue_artist_event sheet and generate a new column, "date". Note that this is not writing the new column to the sheet, just adding it to the pandas data frame I'm working from.

In [25]:
import datetime
from dateutil import parser

def str_date_to_iso(month, day, year):
    
    str_date = f"{month} {day} {year}"
    dt = parser.parse(str_date).date().isoformat()
    
    return dt

In [26]:
venue_artist_event["date"] = venue_artist_event.apply(lambda row: str_date_to_iso(row['Month'], row['Day'], row['Year']), axis=1)

When I ran the method, it flagged a concert in the data by Bob Wills on "February 29, 1962" at the Farmer's Daughter. There was no February 29 in 1962, so I changed it to February 28.

Next, I'm creating a new data frame with all the artists listed next to their first and last appearances in the concert list, by chronological order.

In [28]:
venue_artist_event_dates = (
    venue_artist_event
    .groupby("Artist_Formula")["date"]
    .agg(["min", "max"])
)

In [29]:
venue_artist_event_dates

                                                  min         max
Artist_Formula
 Jimmy Heath                               1982-06-19  1982-06-19
 Robert Casadesus (piano)                  1970-12-05  1970-12-05
!!! Chk Chk Chk                            2023-10-12  2023-10-12
$Not                                       2023-05-09  2023-05-09
'Blue' Gene Tyranny                        1985-06-28  1985-06-28
...                                               ...         ...
vocals]                                    2010-02-27  2010-02-27
west                                       1986-02-08  1986-02-08
with added attraction Curley Mays          1958-03-06  1958-03-06
xxxx                                       1996-06-08  1996-06-08
¿Por qué los hombres aman a las cabronas?  2021-10-24  2021-10-24

[20341 rows x 2 columns]

Inspecting this list, I can see a few issues straight away: an artist just called "vocals]', and an artist called "$Not", another one just called "west". These issues may bear further investigation.

In [31]:
artist_list_rows = []

next_index = artists_index["Index"].max() +1

for artist in unique_artists:
    
    if artist in artist_to_index:
        idx = artist_to_index[artist]
    else:
        idx = next_index
        next_index += 1

    if artist in venue_artist_event_dates.index:
        first = venue_artist_event_dates.loc[artist, "min"]
        last = venue_artist_event_dates.loc[artist, "max"]
    else:
        first = None
        last = None
        
    artist_list_rows.append({
        "Index": idx,
        "Artist": artist,
        "FirstAppearance": first,
        "LastAppearance": last,
    })

result = pd.DataFrame(artist_list_rows)

In [32]:
result

       Index                        Artist FirstAppearance LastAppearance
0       1770            Waking the Sleeper      2021-08-18     2021-08-18
1       1771                    Stillwater      1975-01-10     1977-09-03
2       1772             Dance Like Robots      2008-06-20     2023-01-21
3       1773                   Dreamcastle      1990-11-24     1990-11-24
4       1774                  Pocketsettas      2022-05-29     2022-05-29
...      ...                           ...             ...            ...
20414   1172  Gary Puckett & the Union Gap      1968-11-23     1986-06-25
20415  20422            Chubby Knuckle Duo      2021-06-04     2021-06-04
20416  20423                      Sosamann      2022-03-06     2022-03-06
20417  20424                     Bangtango      1989-10-17     1989-10-24
20418  20425                   Mark Monaco      2003-06-14     2011-09-13

[20419 rows x 4 columns]

In [33]:
result.to_excel('sounds_data_to_share.xlsx', sheet_name='artistsIndex')