# Sounds Data Paper Python

## Artists List

There are multiple lists of artists. One is in the `artistsIndex` worksheet. This should presumably be the master artist list since it contains indexes for all of them.

There are also artists in other worksheets: `Venue_Artist_Event` and `Ven_Ev_Address`. The first task is to double check artist names and ensure we have a complete list with unique indexes for all artists.

First, I'm going to load the excel file and access the worksheet.

Here, I'm going to import the pandas library, read the file, and inspect the names of the worksheets.

In [70]:
import pandas as pd

In [71]:
sounds_data = pd.ExcelFile('spreadsheets/product1_data_master_rev.xlsx')

In [72]:
sheets = sounds_data.sheet_names
sheets

['Ven_Ev_Ar_Address',
 'Venue_Artist_Event',
 'Layer 1 Venues',
 'artistsGenre',
 'genreIndex',
 'Sheet5',
 'artistsIndex',
 'Venues No Address',
 'venues_with_coordinates']

Now that I have the exact names of all the sheets, I will go ahead and load the artistsIndex sheet and the other sheets I am interested in. Then I will inspect the resulting pandas data frames to find the names of the columns containing artist information.

In [73]:
artists_index = pd.read_excel('spreadsheets/product1_data_master_rev.xlsx', sheet_name='artistsIndex')
venue_artist_event = pd.read_excel('spreadsheets/product1_data_master_rev.xlsx', sheet_name='Venue_Artist_Event')
ven_ev_ar_address = pd.read_excel('spreadsheets/product1_data_master_rev.xlsx', sheet_name='Ven_Ev_Ar_Address')

In [74]:
artists_index.head()

                   Name  Index
0        Dierks Bentley      1
1  "The Italian Cowboy"      2
2           Keith Urban      3
3          George Jones      4
4           Hilary Duff      5

In [75]:
venue_artist_event.head()

,Month,Day,Year,Venue,Event_Artists,Artist_Formula,Event_Formulas,Index
0,September,10,1857,St. Mary's Catholic Church,French Mountaineer Singers,French Mountaineer Singers,NaN,1
1,June,25,1869,Menger Hotel,General Mason Farewell Party: San Antonio Bras...,San Antonio Brass Band,General Mason Farewell Party,2
2,July,4,1874,San Pedro Park,San Antonio Brass Band,San Antonio Brass Band,NaN,3
3,October,9,1874,"San Pedro Springs, Turner Hall",Tenth Texas Saengerfest,Tenth Texas Saengerfest,NaN,4
4,October,10,1874,"Casino Hall, Turner Hall",Tenth Texas Saengerfest,Tenth Texas Saengerfest,NaN,5

In [76]:
ven_ev_ar_address.head()

,Index,Month,Day,Year,Venue,Event_Artists,Address,Zip,Longitude,Latitude,Artist,Event,City,State
0,2581,January,1,1970,San Antonio Convention Center Arena,"KBER Holiday Show: Willie Nelson, Charley Pri...",601 Hemisfair Plaza Way,78205.0,NaN,NaN,Willie Nelson,KBER Holiday Show,San Antonio,Texas
1,2581,January,1,1970,San Antonio Convention Center Arena,"KBER Holiday Show: Willie Nelson, Charley Pri...",601 Hemisfair Plaza Way,78205.0,NaN,NaN,Charley Pride,KBER Holiday Show,San Antonio,Texas
2,2581,January,1,1970,San Antonio Convention Center Arena,"KBER Holiday Show: Willie Nelson, Charley Pri...",601 Hemisfair Plaza Way,78205.0,NaN,NaN,Grandpa Jones,KBER Holiday Show,San Antonio,Texas
3,2581,January,1,1970,San Antonio Convention Center Arena,"KBER Holiday Show: Willie Nelson, Charley Pri...",601 Hemisfair Plaza Way,78205.0,NaN,NaN,David Houston,KBER Holiday Show,San Antonio,Texas
4,2582,January,16,1970,San Antonio Municipal Auditorium,Vikki Carr,100 Auditorium Cir.,78205.0,NaN,NaN,Vikki Carr,NaN,San Antonio,Texas

Now, I'm going to extract the list of unique artists listed in the artistIndex sheet. I see there are 1764 total artists listed there.

In [77]:
artists_artist_index = set(artists_index['Name'].dropna().str.strip())
len(artists_artist_index)

1764

Next, I'm going to create a set data structure, which ensures that all data items are unique and avoids any duplication. I'll then get the length of the set and do an initial inspection of its contents.

I can see there are 1764 artists in the artistsIndex sheet, and that while it's a good list, there are some data issues. For example, 

```
'Ballet Folklorico de San Antonio',
'Ballet Folkloricp de San Antonio',
```

or

```
'Billy Mata & the Texas Tradition',
'Billy Mata and the Texas Tradition',
```

All this suggests some manual cleanup may be helpful, but overall the collection is generally valid.

In [78]:
unique_artists = set()
unique_artists.update(artists_artist_index)

In [79]:
len(unique_artists)

1764

In [80]:
sorted(unique_artists)

['"The Italian Cowboy"',
 '(Fools?)',
 '(TLC - cancelled)',
 '01 Blues',
 '10 Years',
 '112',
 '12 Step Rebels',
 '13th Floor Elevators',
 '214th Army Band',
 '3 Balls of Fire',
 '4 2 MD',
 '4 on the Floor',
 '7seconds',
 '98 Degrees',
 'A Perfect Circle',
 'AC',
 'ANJ',
 'Aaron Barker',
 'Aaron Carter',
 'Accept',
 'Ace Frehley',
 'Adam Bomb',
 "Adler's Appetite",
 'Adolescents',
 'Adolph Hofner',
 'Adolph Hofner and the Pearl Wranglers',
 'Adrian y Destino',
 'Aerosmith',
 'Agustin Ramirez',
 'Air Force Concert Band',
 'Air Supply',
 'Airbourne',
 'Al Gomez',
 'Al Hirt w',
 'Al Olsen',
 'Al Sturchio Orchestra',
 'Al Sturchio and His Orchestra',
 'Alabama',
 'Alan Jackson',
 'Albert Collins and the Antone Blues Band',
 'Albert Garcia',
 'Albita',
 'Alcatrazz & Odin',
 'Alex Abravanel',
 'Alex Sutherlin Project',
 'Algiers Brass Band',
 'Ali Ekber Cicek',
 'Alibi',
 'Alice Cooper',
 'Alice Gomez',
 'All Time Low',
 'All-American Rejects',
 'Alondra',
 'Altered Natives',
 'Alvin Crow and the Pleasant Valley Boys',
 'Aly & AJ',
 'Amanda Perez',
 'America',
 'Americult',
 'Amy Grant',
 'Anacani',
 "Anarchists' Convention",
 'Ancient Cross',
 'Andre Cymone',
 'Angelina',
 'Angels Grace',
 'Angerkill',
 'Anthrax',
 'Antonio Aguillar',
 'April Wine',
 'Armed Forces Bicentennial Band Concert',
 'Armored Saint',
 'Army Blues',
 'Arthur Hanlon',
 'Article of Control',
 'Arturo Sandoval',
 'Ashburn',
 'Ashlee Rose',
 'Asian Dub Foundation',
 'Asleep at the Wheel',
 'Association',
 'Aswad',
 'Atlanta',
 'Augie Meyer',
 'Augie Meyers',
 'Augie Meyers and the Western Head Band',
 'Aurellio de Hoyas and Mariachi Azteca',
 'Awaken the Fallen',
 'Axe',
 'Az Yet',
 'Azteca Intnernacional',
 'Azul & Maya',
 'Azul (Azucena Barrientos)',
 'B.B. King',
 'B.G. and Hot Boys',
 'BL Lacerta',
 'Baby Bash',
 'Bachman Turner Overdrive',
 'Backstreet Boys',
 'Bad Company',
 'Bad Religion',
 'Ball & Jack',
 'Ballet Folklorico de San Antonio',
 'Ballet Folkloricp de San Antonio',
 'Ballet Regional Mexicano',
 'Bamboleo',
 'Banda Copala',
 'Bandango',
 'Banned in Public',
 'Bar-Kays',
 'Barbara Fairchild',
 'Barbara Mandrell',
 'Barrington Levy',
 'Barry Brake (piano)',
 'Basehead',
 'Bastard Sons of Johnny Cash',
 'Be Syndicate',
 'Beach Boys',
 'Beastie Boys',
 'Beatriz Lamas',
 'Becky Hobbs and Moe Bandy',
 'Bela Fleck and the Flecktones',
 'Bellamy Brothers',
 'Ben King',
 'Ben McPeak',
 'Benny Goodman',
 'Bent Norup',
 'Berlin Opera',
 'Beto and the Fairlanes',
 'Bett Butler',
 'Better Than Ezra',
 'Better than Ezra',
 'Betty Carter',
 "Beverly Houston and Breezin'",
 'Beyond Black',
 'Big & Rich',
 'Big & Rich with Cowboy Troy',
 'Big Al Downing',
 'Big Mountain',
 'Big Walter Price',
 'Big Wreck',
 'Bill Bailey',
 'Bill Cosby',
 'Bill Engvall',
 'Billy Cobham',
 'Billy Currington',
 'Billy Joel & Elton John',
 'Billy Mata',
 'Billy Mata & the Texas Tradition',
 'Billy Mata and the Texas Tradition',
 'Billy Morgan',
 'Biohazard',
 'Black Crowes',
 'Black Market Revival',
 'Black Oak Arkansas',
 'Black Sabbath',
 'Black Sabbath featuring Ozzy Osbourne',
 'Black and Blue',
 'Blackbird',
 'Blackwater Gospel',
 'Blaine Keith',
 'Blak Fate',
 'Blake Shelton',
 'Blaque',
 "Blood 'n' Beer",
 'Bloodhound Gang',
 'Blowsing Trees',
 'Blue Man Group',
 'Blue Norther',
 'Blue October',
 'Blue Öyster Cult',
 'Blues Traveler',
 'Bo Bice',
 'Bob Dylan',
 'Bob Dylan with G.E. Smith',
 'Bob Haggart',
 'Bob James',
 'Bob Marley Festival',
 'Bobbie Cryner and Sisters Morales.',
 'Bobby "Tossin\' and Turnin\'" Lewis',
 'Bobby & Jody Jenkins',
 'Bobby Aragon Group',
 'Bobby Baker & the Longnecks',
 'Bobby Blue Bland',
 'Bobby Flores Band',
 'Bobby G & the Drive',
 'Bobby Jenkins',
 'Bobby Lloyd',
 'Bobby Martin',
 'Bobby Pulido',
 'Boerne Village Band',
 'Bombasta',
 'Bone Thugs-n-Harmony',
 'Bonham',
 'Bonnie Raitt',
 'Border Palace All-Stars',
 'Boston',
 'Bow Evil',
 'Boxcar Willie',
 'Boys II Men',
 'Boys Like Girls',
 'Brad Paisley',
 'Brand New',
 'Brandon Rhyder and Wade Bowen',
 'Brenda Russell',
 'Brian Culbertson',
 'Briggs',
 'Britney Spears',
 'Brokencyde',
 'Brooks & Dunn',
 'Brother Cane',
 'Bruce James',
 'Bubba Bartosh',
 'Bubba Littrell and the Melody Mustangs',
 'Buckcherry',
 'Bud Keefer',
 'Buddy Guy',
 'Budgie',
 'Buffalo Soldier',
 'Bullet for My Valentine',
 'Bush',
 'Butthole Surfers',
 'Byfist',
 'Café Tacumba',
 'Calhoun',
 'Campanas De America,Ram Herrera',
 'Candlebox',
 'Cano Estremera',
 'Carlos Vives',
 'Carman',
 'Carmen Munoz',
 'Carnaval de San Anto',
 'Carol Plunk',
 'Carolyn Steele',
 'Carolyn Wonderland',
 'Carrie Underwood',
 'Casey Donahew Band',
 "Cat's Cradle",
 'Catch War',
 'Catfish',
 'Cedella Marley Booker',
 'Celine Dion',
 'Centro Cultural Aztlan',
 'Cerrito',
 'Chacho & Brance',
 'Chamillionaire',
 'Charlie Daniels Band',
 'Charlie Walker',
 'Charlie and the Cool Cats',
 'Cheap Trick',
 'Cheats',
 'Cheb Tati',
 'Chente Barrera',
 'Cher',
 'Cherelle',
 'Chevelle',
 'Chick Corea (trio w',
 'Children of Bodom',
 'Chilton Vance & Texas Connection',
 'Chiodos',
 'Chris Holzhaus',
 'Chris Pfifer',
 'Chris and Judy',
 'Chris and Judy Wagon',
 'Chrissy Flatt',
 'Christopher Parker;  Wire Train',
 'Cinderella',
 'Cinderleaf',
 'Claude Morgan & the Blast',
 'Clay Walker',
 'Cleo Auiderhaar',
 'Clifford Scott',
 "Clyde's Car and the Rockets",
 'Coal Chamber',
 'Coffin Creeps',
 'Cold Sweat',
 'Coldplay',
 'Colima',
 'Collective Soul',
 'Collin Raye',
 'Commodores',
 'Concombre Zombi',
 'Concrete Blonde',
 'Conjunto Reunion de Raul Vasquez',
 'Conspiracy of Silence',
 'Conway Twitty',
 'Cool for August',
 'Corina',
 'Corrosion of Conformity',
 'Cortez Greer',
 'Cory Morrow',
 'Cory Morrow Band',
 'Costumbre',
 'Country Cavaliers',
 'Country Express',
 'Country Horizon',
 'Country Joe and the Fish',
 'Countrymen',
 'Covergirls',
 'Cowboy Mouth',
 'Coyote Dreams',
 'Craig Morgan',
 'Cranberries',
 'Creed',
 'Creed Taylor',
 'Creed Taylor and the Travellers',
 'Crimson Jazz Orchestra',
 'Crosby',
 'Cross Canadian Ragweed',
 'Cross Canadian Ragweed & Montgomery Gentry',
 'Cross Wind',
 'Cruz Arizmendi and his Orchestra',
 'Crystal Myth',
 'Curley Mays',
 'Curtis Calderon',
 'Cutting Crew',
 'Cyndi Lauper',
 'DC',
 'DJ Laze',
 'DJ Papote and the Semeneya Dance Group',
 'DJ Unk',
 'DRI',
 'Dale Jackson',
 'Damian Marley (Rasta Rapper)',
 'Damij',
 'Damn Yankees',
 'Dan Ryan',
 'Dan Seals',
 'Dangerous Toys',
 'Danny Valdez',
 'Darius Rucker',
 'Darrel Tidaback',
 'Darrell Clanton',
 'Darrell Harkins and the Love Country Express',
 'Daryl Singletary',
 'Dave Kemp and the Family Tradition',
 'Dave Koz',
 'Dave Valentine',
 'Dave Wakeling',
 'Dave Wilkins Band',
 'David Ball',
 'David Larson',
 'David Lee Garza',
 'David Lindley',
 'David Mares and Hot Tamales',
 'David Marez',
 'David Sanborn',
 'Davie Allan and the Apaches',
 'De Los Muertos',
 'De-Animator',
 'DeBarge',
 'DeWayne Toney & Rogue Moon',
 'Deadpool',
 'Deadpool (Carlos Lopez',
 'Deanna Carter',
 'Debbie Garris',
 'Deborah Harry',
 'Deborah Hay',
 'Default',
 'Deicide',
 'Del Castillo',
 'Delbert McClinton',
 'Deniece Williams',
 'Denim',
 'Denny Ezba',
 'Denny Ezba (the Goldens)',
 'Denny Laine',
 'Depeche Mode',
 'Deryl Dodd',
 "Destiny's Child",
 'Destruction Evolution',
 'Desvelados',
 'Detective',
 'Devestation',
 "Devil's Hollow",
 "Devil's Martini",
 'Dieboy',
 'Dierks Bentley',
 'Dimas Garza',
 'Dino',
 'Dio',
 'Dirty Dozen Brass Band',
 'Dirty Power',
 'Dishwalla and Seven Mary Three',
 'Dissension',
 'Dixie Chicks',
 'Dizzy Gillespie',
 'Dog Men Poets',
 'Dog Tooth Violet',
 'Dokken',
 'Don Albert',
 'Don Santiago & Flaco Jimenez',
 'Don Wallace',
 'Don Williams',
 'Doobie Brothers',
 'Dottsy',
 'Double or Nothing',
 'Doug Fesler',
 'Doug Kershaw & Trio',
 'Doug Stone',
 'Downfall Funeral',
 'Downset',
 'Doyle Bramhall',
 'Dr. Ed Hill',
 'Dr. Matt Jones',
 'Dr. Patterson Barrett & the Associates',
 'Drain S.T.H. and Vision of Disorder',
 'Dreamscape',
 'Drivin Rain',
 'Dru Hill',
 'Duke',
 'Duke Ellington and his Orchestra',
 'Duke y Azzero',
 'Dynasty',
 'E-Z-O',
 'EJB Reggae Gospel Review',
 'Eagles',
 'Earl "Fatha\' Hines',
 'East Meets West',
 'Easy Adams',
 'Echoset',
 'Ecleticism',
 'Eclipse',
 'Econoline Crush',
 'Ed Shaughnessy',
 'Eddie Gonzales',
 'Eddie Gonzalez',
 'Eddie Gonzalez and Grupo Vida',
 'Eddie Holman',
 'Eddie Money',
 'Eddy Raven',
 'Eden Burning',
 'Edward C. Garza',
 'Eisley',
 'El Caso de Pullo',
 'El Curro',
 'El International Folklorico Mexicano',
 'El Mariachi Nuevo San Juan',
 'El Rayo X',
 'Eleven Hundred Springs',
 'Eli Young Band',
 'Elida y Avante',
 'Elton John',
 'Elton John & Billy Joel',
 'Elyssia Marie',
 'Emerald House',
 'Emerson',
 'Emilio',
 'Emilio Casares',
 'Emilio Navaira',
 'Emily Gimble and the Jitterbug Vipers',
 'Emotions',
 'Engage',
 'English Beat w',
 'Enrique Inglesias',
 'Eric Clapton',
 'Eric Hisaw',
 'Eric Johnson',
 'Eric Lynn',
 'Ernesto Rodriguez',
 'Ernie Sky and the K-Tells',
 'Eskalith',
 'Esteban Jordan y el Rio Jordan',
 'Etta James',
 'Eve 6',
 'Evelyn "Champagne" King',
 'Everclear',
 'Everlast',
 'Exciter',
 'Exile',
 'Exodus',
 'Expose',
 'Eye 2 Eye',
 'Fabolous',
 'Fabulous Thunderbirds',
 'Faith Hill',
 'Fama',
 'Faron Young',
 'Faster Pussycat',
 "Fate's Warning",
 'Fear Factory',
 'Fearless Iranians from Hell',
 'Fergie Frederiksen',
 'Festus (Ken Curtis)',
 'Fictionplane',
 "Fiddlin' Frenchie Burke",
 'Fifth Army Band',
 'Fine Line',
 'Fingerprints',
 'Firehouse',
 'Five',
 'Flaco Jimenez',
 'Flaco Jimenez & Country Roland',
 'Flash',
 'Flash Cadillac & the Continental Kids',
 'Fleetwood Mac',
 'Flesh Electric',
 'Flotsam & Jetsam',
 'Fluffy',
 'Foghat',
 'Foo Fighters',
 'Footprints',
 "Force M.D.'s",
 'Foreigner',
 'Four Freshmen',
 'Four-On-the-Floor',
 'Franco',
 'Frank Garrett and His All Stars',
 'Frank Marino & Mahogany Rush',
 'Frank Rodarte',
 'Frank Rodarte & los Blues Vatos',
 'Frank Rodarte & the Alamo All-Stars',
 'Frank Rodriguez Band',
 'Frankie J',
 'Frankie Valli',
 'Frankie Valli & the Four Seasons',
 'Franz Ferdinand',
 'Freak Nasty',
 'Fred Hooter',
 'Fred Zimmerle',
 'Freddie Fender',
 'Freddy Fender',
 'Frenchie Burke',
 'Gagasdan',
 'Gallagher',
 'Galo Gutierrez & Ocean Breeze',
 'Garth Brooks',
 'Gary Allan',
 'Gary Bonnett',
 'Gary Lewis & the Playboys',
 'Gary Moore',
 'Gary Puckett & the Union Gap',
 'Gavin DeGraw',
 'Geezinslaws',
 'Gene Woods',
 'George Chambers',
 'George Chambers & the Country Gentlemen',
 'George Jones',
 'George Jones & Tammy Wynette',
 'George Porter Jr. & the Runnin Pardners',
 'George Strait',
 'George Strait,',
 'George Thorogood & the Destroyers',
 'George Winston',
 'Georgia Satellites',
 'Geronimo Trevino',
 'Gerry Gibbs & the Bitches Brew Orchestra',
 'Giant Smiling Dog',
 'Gilbert Velasquez',
 'Girls Against Boys',
 'Girls in a Coma',
 'Gloria Aguilar',
 'Gloria Aguillar',
 'Gloria Estefan',
 'Gojira',
 'Gonsemble',
 'Goo Goo Dolls',
 'Good Charlotte',
 'Gordon Lightfoot',
 'Graham Wilkinson',
 'Grand Alliance',
 'Grandmaster Flash & the Furious Five',
 'Grant Lee Buffalo',
 'Grass Roots',
 "Graverobbin' Bastards and Hellbound Hearse",
 'Gravity Kills',
 'Great White',
 'Green Day',
 'Gretchen Wilson',
 'Grey Holiday [Matt Minor (vocals',
 'Grim Reaper',
 'Groove Movement',
 'Grupo Mazz',
 'Grupo Privilegio',
 'Grupo Vida',
 'Guadalajara Symphony Orchestra',
 'Guess Who',
 'Guild and Lucid Dementia. DJs include INSOC',
 'Guitares del Sol',
 "Guns 'n' Roses",
 'Gus Hardin',
 'Guy Forsyth Band',
 'H.I.M.',
 'Hank Thompson',
 'Hank Thompson & Susan Raye',
 'Hank Williams',
 'Hannah Montana',
 'Harmsay',
 'Hassan Hakmoun',
 'Hate',
 'Hatebreed',
 'Head East',
 'Heather Leather',
 'Hector Tricoche',
 'Helix',
 'Helloween',
 'Henry Brun & the Latin Playerz',
 'Henry Lee Summer',
 'Henry Mancini w',
 'Herb Keyser',
 'Herbie Hancock',
 "Herman's Hermits",
 'Hey Monday and the Friday Night Boys.',
 'High Calibre',
 'High Lonesome Country',
 'Hilary Duff',
 'Hilda Jimenez',
 'Hired Guns',
 'Hoi Polloi',
 'Holly Dunn',
 'Homer',
 'Honor Society',
 'Houserockers',
 'Howling Bells',
 'Huey',
 'Hulda Jimenez',
 'Hum',
 'Humble Blues All-Stars',
 'Humble Pie',
 'I Ching Gatos',
 'I.O.I.',
 'IMCE Choral Group',
 'Ian Moore',
 'Icon',
 'Iggy Pop',
 'Imperial Drag',
 'Incubus',
 'Indigo Rose',
 'Infectious Grooves,',
 'Infidels',
 'Inner City All-Stars',
 'Insane Clown Posse',
 'Intocable',
 'Ipso Facto',
 'Irma Navarro',
 'Iron Maiden',
 'Italian National Opera',
 'Itzhak Perlman',
 'J. Stiles & the Cementary Hips',
 'JFJ',
 'Jaci Velazquez',
 'Jack Ingram',
 'Jack Levitt',
 'Jack Russell',
 'Jack Skiles Band',
 'Jackie Huddle',
 'Jackie King',
 'Jackson Browne',
 'Jackyl',
 'Jag Wire',
 'Jagged Edge',
 'Jai',
 'Jake Owen',
 'James & Michael Younger',
 'James Brown',
 'James Cotton',
 'James Cotton & his Blues Band',
 'James Otto',
 'Jamie Foxx',
 'Jamie McMurtry',
 'Janet Jackson',
 'Janie de La Garza',
 'Janis Martin',
 'Janus',
 'Jarrod Birmingham',
 'Jason & the Scorchers',
 'Jason Aldean',
 'Jay Eric',
 'Jazzmanian Devils',
 'Jazzworks',
 'Jeff Crissler',
 'Jeff Foxworthy',
 'Jeff Healey Band',
 'Jeremy Camp',
 'Jerry Cole',
 'Jerry Field',
 'Jerry Jeff Walker',
 'Jerry Lee Lewis',
 'Jerry Reed',
 'Jesse Gonzales',
 'Jim Cullum Jazz Band',
 'Jim Cullum and Happy Jazz Band',
 'Jim Cullum and the Happy Jazz Band',
 "Jim Cullum's Happy Jazz Band",
 'Jim Ed Brown & Helen Cornelius',
 'Jim MacFarland',
 'Jimi Lee',
 'Jimmie Kay Ramos',
 'Jimmy Cliff and his six-piece Oneness Band',
 'Jimmy Dean',
 'Jimmy Edward',
 'Jimmy Gonzalez y Grupo Mazz',
 'Jimmy Spacek',
 'Jo Dee Messina',
 'Jo Jo Gunne',
 'Joan Carroll & Footprints',
 'Joan Carroll Trio',
 'Joan Jett & the Blackhearts',
 'Joanna Ramriez',
 'Jocelyn Enrique',
 'Jody Jenkins',
 'Jody Jenkins Band',
 'Joe "King" Carrasco',
 'Joe "King" Carrasco and the Crowns',
 'Joe "King"Carrasco & Esteban Jordan',
 'Joe & the Torpedos',
 'Joe Guererro',
 'Joe McBride and Marion Meadows',
 'Joe Nichols',
 'Joe Paul Nichols',
 'Joe Piscopo',
 'Joe Posada',
 'Joe Posada Group',
 'Joe Posada y El Quito Sol',
 'Joe Reyes Quartet',
 'Joe Satriani',
 'Joe T. Campos',
 'Joe Venuti',
 'Joe Williams',
 'Joel Dilley Quintet',
 'Joel Dilley [bass] Cecil Carter [trumpet]',
 'Joey Fender and the 55s',
 'Johhny Copeland',
 'John Cafferty',
 'John Conlee',
 'John Davidson',
 'John Hanley Martinez',
 'John Holt',
 'John Kay & Steppenwolf',
 'John Legend',
 'John Magaldi',
 'John Magaldi Trio',
 'John Magaldi and Saxophonic',
 'John Mayall',
 'John Michael Montgomery',
 'John Reuben',
 'John Rich with Cowboy Troy',
 'John Waite',
 'John Watkins',
 'Johnny & Bobby Wright',
 'Johnny Bush',
 "Johnny Dee & the Rocket 88's",
 'Johnny Duncan',
 'Johnny Lee',
 'Johnny P & the Wiseguys',
 'Johnny Rivers',
 'Johnny Rodriguez',
 'Johnny Z',
 'Jokester',
 'Jon B',
 'Jon Hendricks',
 'Jon Secada',
 'Jonas Brothers',
 'Jonathan Davis (Korn)',
 'Jonathan Raveneau [violin])',
 'Jordan Knight',
 'Jordin Sparks',
 'Jorge Infante',
 'Jose Maria Perello',
 'Josh Turner',
 'Jr',
 'Jr.',
 'Juan Zaizar',
 'Juanita LaBeaux',
 'Judas Priest',
 'Judy Lynn',
 'Julian Lennon',
 'Julian Marley',
 'Julio Casas',
 'Jumbo',
 'Jungle Brothers',
 'Junior Wells',
 'Justin Bieber',
 'Juvenile',
 'K Phillips & the Concho Pearls',
 'K-Ci & JoJo',
 'KISS',
 'KKYX Great Country River Festival',
 'KTFM 1200 Squad',
 'Karen Finley',
 'Katchie Cartwright',
 'Katherine Dawn',
 'Kathleen Battle',
 'Kathy Mattea',
 'Kathy Murray and the Electrifying Kilowatts',
 'Kathy Sledge and the Sisters',
 'Katy Perry',
 'Katy Rose',
 'Ke$ha',
 'Keel',
 'Keith Davis',
 'Keith Davis Band',
 'Keith Lutz',
 'Keith Sweat',
 'Keith Urban',
 'Kelly Malone',
 'Kenny Chesney',
 'Kenny Dale',
 'Kenny Dale & Shiloh',
 'Kenny Dale & the Jimmie Mac Band',
 'Kenny G',
 'Kenny Garrett Quartet',
 'Kenny Rogers & Dottie West',
 'Kenny Seratt',
 'Kenny Wayne Shepherd',
 'Kevin Evans',
 'Kevin Fowler',
 'Kid Rock',
 'Kilamanjaro',
 'Kill Paradise',
 'Killswitch',
 'Kimberly Locke',
 'Kin of Cain',
 'King Diamond',
 'King Diamond (formerly of Merciful Fate)',
 'King Kone',
 'King Pelican',
 'Kings of Leon',
 'Kinky Friedman',
 'Kinsu',
 'Kiss',
 'Kitty Wells',
 'Kix',
 "Knock 'em Stiff",
 'Koko Taylor',
 'Kon Kan',
 'Korn',
 'Kris Kimura Quartet',
 'Krokus',
 'Kromags',
 'Krystal',
 'Kumbia Kings',
 'Kurt Griffey',
 'Kyle Turner and Richard Garcia & First Light',
 'L.A. Guns',
 'LL Cool J',
 'La Calidad',
 'La Calma',
 'La Contra',
 'La Mafia',
 'La Referencia',
 'La Sombra',
 'La Sombra Chicana USA',
 'La Tropa Colombiana',
 'La Tropa F',
 'Laaz Rockit',
 'Lady Antebellum',
 'Lady Antebellum & Billy Ray Cyrus',
 'Lake and Palmer',
 'Lakeside',
 'Lalo Gonzalez & Karen Wheeler',
 'Lalo Gonzalez & Mickey Gilley',
 'Lamb of God',
 'Larry Carlton',
 'Las 3 Divas',
 'Last of Our Kind',
 'Latin Breed',
 "Latin Player'z",
 'Laura Canales',
 'Laura Marie',
 'LeAnn Rimes',
 'Leahy',
 'Ledaswan',
 'Lee Ann Womack',
 'Lee Roy Parnell',
 'Lee Thomason Quintet',
 'Legs Diamond',
 'Leon Russell',
 'Lesley Roy',
 'Less than Jake',
 'Letty Guval',
 'Life of Agony',
 'Lifehouse',
 'Lil Troy',
 'Lil Wayne',
 'Lila Downs',
 'Lillian Axe',
 'Lillian Stanfield',
 'Limp Bizkit',
 'Linda Perry',
 'Link',
 'Lisa Lisa & Cult Jam',
 'Lisa Lopez',
 'Lita Ford',
 'Little Anthony',
 'Little Joe y La Familia',
 'Little Richard',
 'Little River Band',
 'Little Texas',
 'Little Willie & Zydeco Hitchhikers',
 'Little Willie Davis & Zydeco Band',
 'Liz Phair',
 'Lloyd Herrman [drums]',
 'Lo-Pro and Doctura',
 'Lohnny Lyon',
 'Lolita Villa',
 'Lonnie Brooks',
 'Lorenza Lory',
 'Loretta Lynn',
 'Lorrie Morgan',
 'Los #3 Dinners',
 'Los Caminantes',
 'Los Cardenales de Nuevo Leon',
 'Los Chavalozz',
 'Los Conquistadores',
 'Los Crawdaddies',
 'Los Desperados',
 'Los Desperadoz',
 'Los Espanolas',
 'Los Flamencos de San Antonio',
 'Los Gauchos de Argentina',
 'Los Jovenes',
 'Los Lobos',
 'Los Lonely Boys',
 'Los Palominos',
 'Los Paranas',
 'Los Pasajeros',
 'Los Polkeros',
 'Los Shit Magnets',
 'Los Texas Outlaws',
 'Los Tigres del Norte',
 'Los Tigrillos',
 'Los Tucanes',
 'Lou Ann Barton',
 'Lou Christie',
 'Lou Rojas',
 'Loudness',
 'Love',
 'Loverboy',
 'Lucha Villa',
 'Lucky Dube',
 'Ludacris',
 'Luis Miguel',
 'Luis Shati',
 'Luisito Carrion',
 'Luke',
 'Luke Bryan & Duelo',
 'Lustre',
 'Lydia Mendoza',
 'Lynn Anderson',
 'Lynn Anderson & Charlie Walker',
 'Lynryd Skynyrd',
 'Lynyrd Skynyrd',
 'M.D.O.',
 'M:G',
 'MIMS',
 'Machine Head',
 'Mad Temple',
 'MadMax',
 'Maddex 13',
 'Madhouse',
 'Man Mountain',
 'Man of Sorrows',
 'Mana',
 'Manana Brothers',
 'Mania',
 'Manic Shuffle',
 'Mannequin',
 'Marcus David Saenz',
 'Marcus Rubio',
 'Maria Teresa Rodriguez (piano)',
 'Mariachi Femenil Las Eréndiras de San Antonio',
 'Mariachi Infantil',
 'Mariachi Internacional',
 'Mariachi International',
 'Mariachi Jalisco',
 'Mariachi Las Campanas de America',
 'Mariachi Los Caporales',
 'Mariachi Nuevo San Juan',
 'Mariachi Vargas de Tecalitan',
 'Mariachi Vargas de Tecalitlan',
 'Mariachis Victoria Acosta and Kandi Garcia; Elizabeth "La Cantante" Brackman and Rick Balderrama; Gabe Nieto & the Jalapeño Express; "Little" Henry Lee Padilla; Pablo Urbina de la Traizion and Elemento; Tato Henriquez and Gabe Garcia',
 'Marilyn Manson',
 'Maritza',
 'Mark Chesnutt',
 'Mark Lindsay',
 'Mark Wills',
 'Marley',
 'Marshall Tucker Band',
 'Martha Wash',
 'Martina McBride',
 'Marvin Hamlisch',
 'Mary J. Blidge',
 'Mase',
 'Mason Ruffner',
 'Mastodon',
 'Matchezz and the Flames',
 'Matt Barker',
 'Matt Toon & the Big Deals',
 'Maximus',
 'Maynard Ferguson',
 'Mazz',
 'McBride & the Ride',
 'Meagan Tubb',
 'Meg and Dia',
 'Megadeth',
 'Mel Tillis',
 'Melissa Etheridge',
 'Menudo',
 'Merle Haggard',
 ...]

Now I'll look at the venue_artist_event sheet, which is the main one with all the concerts from the 1850s to the 2020s. There are 20320 unique artists in this list.

In [81]:
artists_venue_artist_event_sheet = set(venue_artist_event['Artist_Formula'].dropna().str.strip())

In [82]:
artists_venue_artist_event_sheet

{'Jamie DeAnda',
 'Natalie Rose',
 'Kolby Cooper',
 'Field of Seed',
 'Maenerchor',
 'The Texas All-Stars',
 'Stage 1 - Highway 101',
 'Cassidy',
 'The Junior Brown Band',
 'Ed Guymer and his Patriotic Band',
 'Thirteen',
 'Chick Corea Elektric Band',
 'Mateo Lopez',
 'Fifth Avenue Band',
 'Temblor del Norte',
 'Jimmy Witherspoon; Big Jim Winn and His Orchestra',
 'Pagame',
 'Golden Earring',
 'Sonny Ace',
 'Mariachi Campanas',
 'Small Faces',
 'Los Connyns',
 'Tailwind',
 'Momgoblin',
 'Santiago Jiminez',
 'Paul Jackson Jr.',
 'Frank Rodarte',
 'Blue Ridge Connection',
 'Joan Rivers',
 'Yelawolf',
 'J. Spockey',
 'Kelli King',
 'Roosevelt Sykes and His RCA Recording Orchestra',
 'La Nopalera',
 'Chase Matthew',
 'Chase Petra',
 'Alexander Ramirez',
 'Isidro Lopez',
 'Fuel',
 'Xceptthe1iwant',
 'Blackbirds',
 'Little Giant',
 'DJ Guero Vaquero',
 'the Shadow',
 'Forplay',
 'Earle Cobb School of Dance Revue',
 'Kenny Clark',
 'Rosario de la Fraga',
 'X-Greats',
 'Honorario Rodriguez',
 'Megalo',
 'Rage Against the Machine',
 'David Houston',
 'Structures',
 'the Corn Handlers',
 'The 3 Danes',
 'Derailers',
 'Calypso Joe and Coco-Te (houseband)',
 '20th Anniversary Tribute to the Doors',
 'Cooper Greenberg',
 'The American Peddlers',
 'Turnpike Troubadours',
 'The Tonewheels',
 'T.G. Sheppard',
 'Ted Russell Kamp',
 'Russ Morgan',
 'Coffee & Alcohol',
 'Welk',
 'Los Unicos',
 'Moon Toki',
 'Micky & The Motorcars',
 'Lo=as Torcasitas',
 'Santiago Jimenez y Su Conjunto',
 'Bobby Aragon Group',
 'Commandos',
 'Jknodic',
 'Louis Minjarez Orchestra',
 'DJ REM.A.NISS',
 'Oscar Ornelus',
 'Topazz',
 'Jr. Medlow and the Bad Boys',
 'Salzer-Sternheim',
 'Happy Jazz Band',
 'Kip Moore & Kacey Musgraves',
 'Los Principes de Nuevo Laredo',
 'Los Jovenes',
 'Sons of Fathers',
 'Jeff Price (Jet Jaguar)',
 'Jazzy Jay',
 'Sean McConnell',
 'The Montiques',
 'Dlo',
 'Fiel a La Vega',
 'Toby Blumenthal (piano)',
 'SeeYouSpaceCowboy',
 'Rick Holden (square dance)',
 'Black Pumas',
 'La Justicia',
 'Dawn Robbins (piano)',
 'Hulda Jimenez',
 'Bruce Mahler',
 'Kim MacKenzie & Glenn Allan',
 'Awake for Days',
 'Grupo Bryndis',
 'Americult',
 'The Wonder Years',
 'Joseph and Tree Brunelle',
 'Toat-Lee Bluz',
 'Christina Edelen (harpsichord)',
 'Carta Blanca',
 'Eric Hanke',
 'Jimmy Buffett',
 'Jimmy Edwards',
 'Thomas Gaab',
 'Walter Beasley',
 'Reality Show',
 'Showstoppers Broadway Tunes',
 'Claude King',
 'Jenny Reynolds',
 'DJ Centrifik',
 'Clyde McCoy and his Sugar Blues Orchestra',
 'The Aaron Prado Trio',
 'Wise Eyes',
 'Greater Mount Olive Baptist Choir',
 'Danny Thomas',
 'Quicksilver Messenger Service',
 'Master Four Quartet',
 'Isolaydead',
 'Mike Sanders and the Country Union Band',
 'Conjunto Acosta',
 'B.J. Reando and the Sounds of the Big Country',
 'Sadgirl',
 'DJ Angelos',
 'Mickey and the Motorcars',
 'Cheryl Wheeler',
 'Rogelio Garcia',
 'Bonsai',
 'Rob Huap',
 'Milt Larkin and his Orchestra',
 'the Presidents',
 'Ramiro Herrera',
 'Jacob Stelly',
 'Prairie View A&M Coeds All Girl Orchestra',
 'Cilantro Boombox',
 'Eco de Mexico Mariachi (with Luis Balderas',
 'Warlung',
 'Bone',
 'Mom Jeans',
 'The Suffers',
 'San Fernando Choir',
 'Algiers Brass Band',
 'Paul Harper',
 'Butch Morgan/Happy Camper Jammers',
 'As I Dosed Myself',
 'Carlene Carter',
 'Fay Adams',
 'Piranha',
 'Mike and the Moonpies',
 'Chordsmen',
 'Madonna',
 'Mariachi San Cecelia',
 'AJ Suede',
 'Little Roy Wiggins',
 'Chris Saucedo',
 'Merle Haggard and the Strangers',
 "St. Mary's Hall Band",
 'Johnny y La Familia',
 'The Bent-Gents',
 'The Band',
 'San Antonio Symphony Orchestra featuring Raya Goubasova (cello)',
 'Ruth Brown',
 'The Joy Formidable',
 'Deer Vibes',
 'Stinger',
 'Suzanna Sharp and the Samba Police',
 'K Phillips',
 'Danny Ray Harris',
 'Pee Wee Hunt and the Twelfth Street Rag Band',
 'Gojira',
 'Tyler Cannon',
 'Stardust',
 'Carmen La Fave and his Orchestra',
 'Joan Jett and the Blackhearts',
 'Goolaks',
 'Luz Amelia Avilez de Cerdio',
 'Nudeswirl',
 'Kree Harrison',
 'The Laves',
 'Broken Stars',
 'AG & Kate',
 'Carnival de San Anto',
 "Joe Thomas/Class of '55",
 'King Peach',
 'Courtney Santana',
 'Reggie & the Full Effect',
 'Torres Lane',
 'Wynonie Harris',
 'Climax',
 'Vended',
 'LUNA 13',
 'singer/keyboardist; Anthony Hernandez',
 'Lu Mitchell',
 'Ceci & Wally',
 'Dirty Power',
 'Bachelor Party',
 'Betty Johnson',
 'Southside High School Band',
 'Carlo Garcia',
 'Aurra',
 'JD Clayton',
 'Professor Julius',
 'Darian Thomas',
 'Maria Conesa',
 'Collin Raye',
 'Soldier Thread',
 'Tito El Bambino',
 'Milton Carroll',
 'Future Shock',
 'George Chambers & the Country Gentlemen',
 'San Antonio Symphony Orchestra featuring Alexey Koltakov',
 'Patsy Torres',
 'Vaughan Pederson (trumpet)',
 'Ready to Fail and Bad Fish',
 'Brian Marshall',
 'Memphis Kee',
 'Clarence Gatemouth Brown & his Orchestra',
 'Kevin Brown',
 'Alcatrazz',
 'Hatebreed',
 'Paul McCandless',
 'Nick Fit & the Seizures',
 'Tiltan and Nathan Zertuche',
 'DJ Rahking Tot',
 'Mim Scharlack',
 'Jimmy Martin and the Texas Playboys',
 'Roy Acuff and his Smoky Mountain Boys',
 'War Babies',
 'Chris Jungle',
 'Roger Creager',
 'TT Troll',
 'Resortes',
 'Leila Josefowicz (violin)',
 'RMRS',
 'Jimmy Tshargi and the David Champion Band',
 "Randy Garibay & Cats Don't Sleep",
 'Little Neesie',
 'Chente Barrera with Oscar G.',
 'The Carter Family',
 "Emily's Gone Mad",
 'Nitro',
 'Ponciano Seoane',
 "Reverend Payton's Big Damn Band",
 'Nitzer Ebb (NE)',
 '16 Tons of Monkeys',
 'Rudy T. Saturday',
 'Die Fighting',
 'The Pipelines',
 'Catherine Denise',
 'Lazarus',
 'Chimchango',
 'Teen Idols',
 '112',
 'La Cima',
 'Tennis',
 'Wide Awake',
 'JJ Grey and Mofro',
 'Forgotten Boys',
 'Terill Avenue',
 'Will Carter Band',
 'Elaine Ehlers (organ)',
 'Big Pile Garbage Band',
 'Ara Gregorian (viola)',
 'Ed Sheeran',
 'Destructive Guerilla Force',
 'Isaac Jacob',
 'Jonas Brothers',
 'Taylor Rae',
 'Stellar',
 'San Antonio Symphony Orchestra featuring Elizabeth Pritchett (soprano)',
 'Fang',
 "Jack Fister's Wildlife",
 'Steve Allen',
 'San Antonio Symphony Orchestra featuring Thomas L. Thomas (baritone)',
 'Stick to Your Guns',
 'La Tropa F & Intocable',
 'Beer Drinking Goats and Friends',
 'Blue Skies',
 'Filmstrips',
 'JR Herrera',
 'Mark Odom Band',
 'Word Alive',
 'Michael Ibrahim',
 'Jose Luis Zagar',
 'Beauty School Dropout',
 'DJ Scorpion',
 'Ray Wylue Hubbard',
 "Jay Eric & the Blieder's Creek",
 'Kyuss',
 'Mark and Laura Marty (houseband)',
 'Mushroomhead',
 'Johnny Duncan & Jeanne Pruett',
 'Hungarian String Quartet',
 'Kings of Leon',
 'Mijail Martinez',
 'Laura Bell & the Blue Aces',
 'Faith Hill',
 'Delphic Sybil',
 'U.D.O. and Jokester',
 'Hillbilly Hellcats',
 "Plain White T's",
 'Del Reeves',
 'Richard Garcia',
 'Wet Li',
 'Tyrone Davis',
 'Martina McBride',
 'The Children',
 'Stillwater',
 'Poder Norteno',
 'Trinity University Handbell Ensemble',
 'Black Diamonds',
 'Becca Jackson',
 '82nd Airborne Division All American Chorus',
 'Katy Perry',
 'Dax Perrier',
 'Larry Herman and his Orchestra',
 'Vincent Villa and his Orchestra',
 'Soultwang Band',
 'Skn Kvr',
 'Rolo Tomassi',
 'Dieboy',
 'Skip Ewing',
 'Roy Haynes',
 'Danny Segovia',
 'Baghdad Bombers',
 'William Beck (baritone)',
 'Tex Beneke & the Glenn Miller Orchestra',
 'Wilburn Brothers',
 'Carrie Lucas',
 'Knox Hamilton',
 'Coup de Ville',
 'Bloodrock',
 'Mighty Lemon Drops',
 'San Antonio Symphony Orchestra',
 'Larry Campbell',
 'Johnny Duncan',
 "Kash'D Out",
 'Gary Puckett',
 'Claude Morgan',
 'Craig Owens',
 'Power Mad',
 'The Skunks',
 'Jerry Waddel',
 'the Fever',
 'Aaron Stephens',
 'Maravia',
 'Syzlak',
 'Average White Band',
 'Kathia',
 'Ruby Dee & Ossie Davis',
 "Eglin's Air Force",
 'Redbow',
 'David Lucke Group',
 'The Smith Brothers and Miss Neesie & Ear Food',
 'Pat Benatar & Neil Giraldo',
 'Las Hijas de la Chingada',
 'The Swaziland White Band',
 'Robert Cray (guitar)',
 'Bubble Puppy',
 'Borodin String Quartet',
 'Konvxtion',
 'Raphael Diaz (piano)',
 'Brad Blackburn and Emma Faye Rudkin',
 'Dave Nault (organ)',
 'Deniz Love',
 'Katherine Dawn & the Texas Ladybugs',
 'Deanna Carter',
 'David Greehly (guitar)',
 'Stevie B.',
 'James Hinkle and the Transatlantics',
 'Yabby You',
 'Clay Hollis Band',
 'William Lewis (bassoon)',
 'Michael Ward',
 'The Wayne Harper Show',
 'Israel',
 'Randy Pelt',
 'Rumba King',
 'Los Tex-Mex',
 'Bart Crow Band',
 'Leon Presley',
 'Parkway Drive',
 'Lonestar Conspiracy',
 'Kill Paradise',
 'Pur3ly Root3d',
 'Sweat & Tears',
 'Esther Luquin',
 'Horizon',
 'Karl Graf',
 'El Gran Sabor de Adrian Diaz',
 'Acadians (folk music)',
 'Linda Ronstadt',
 'the Bottle Rockets',
 'Hugo Gonzales',
 'Anagen',
 'Seven Means Seven',
 'Eddie Lalo Torres y su conjunto',
 'San Antonio Symphony Orchestra featuring Oscar Levant (piano)',
 'Until I Wake',
 'Banda de Monterrey',
 'Neto Caballero',
 'Roberto Pulido',
 'Brandy Zdan',
 'Oak Ridge Boys',
 'Mitch Ryder',
 'Pattti Malcolm',
 'Ruco Villareal and his Orchestra',
 'Harlandale ISD Mariachi',
 'Denim and Diamonds',
 'Joan Jett',
 'Isasias Lucero',
 'Bracoustic',
 'Ballet Folkorico de Navarro',
 'Glass Cloud',
 'Tennessee Valley Authoirty',
 'Kishi Bashii',
 'Deja Blues',
 'Tune Wranglers',
 'Slaughter',
 'Fire and Ice (Pat Benetar tribute band)',
 'The Lonesome Strangers',
 'Nita Lacoste',
 'Kataklysm',
 'Bobby Bland',
 'Little Willie & Zydeco Hitchhikers',
 'Jake Penrod Band',
 'the Schoolhouse Rockers',
 'Gene Zavala and the Chosen Few',
 'Gloomy Gus',
 'Lisa Cameron',
 'John Cockerell',
 'Country Boys Union Band',
 'USAA Jazz Band',
 'Rehab',
 'Vetter Kids',
 'Gene Loves Jezebel',
 'Island',
 "Claude Morgan's Old Country",
 'Jay Dominguez',
 'Tom Petty',
 'Soft Gems',
 'Beverly Houston',
 'Stephanie Lynn',
 'Jack McDuff (organ)',
 'Huston-Tillotson College Concert Choir',
 'Larissa Boyd',
 'Joan Baez',
 'The Sunday Funnies',
 'Young Country',
 'The Cutthroats (Misfits tribute)',
 'Weston Boy Ripps',
 'White Rabbit Reunion',
 'Purvis Henson & his Orchestra',
 'The Howlers',
 'Forsloce',
 'Tom Wassenich',
 'Derringer Band',
 'Orange 9mm',
 'Johnny Rodriguez and the All Star Band',
 'Hassan Hakmoun',
 'Orleans Avenue',
 'Harriet Richardson Gay (contralto)',
 'Little Johnny Taylor',
 'Billy Crash Craddock',
 'Angel',
 'Jack Green and Band',
 'Nic Ether',
 'Luis Miguel',
 'Tito Puente Jr.',
 'Jason Mraz',
 'Dawon of the Phoenix',
 'Zapp & Roger',
 'David Crosby - Graham Nash',
 'Balcones Fault',
 'The West Side Horn',
 'Dylan Riley',
 'Cactus Country',
 'Joseph Sanders (bass)',
 'RNS',
 'Black Eyed Peas',
 'Bill Spivey and his Ford Rangers',
 'White Lion',
 'Gospel Choir',
 'Lee Hoppel and Jubilation',
 'Age of Reason',
 'Hector Gamaliel',
 'Marco Cholo Jazz Quintet',
 'Tatyana Ali',
 'Zoe',
 'Witzend',
 'Grupo Inizio',
 'Los Infiernos',
 'Ada Garcia and the Lamar Band',
 'Huey Smith and the Clowns',
 'Back in Black (AC/DC tribute band)',
 'Captain Glen and the Kling-Ons',
 "Jazz'sAlive",
 'Grupo Legado',
 'The Five Satins',
 'Militia',
 'Bonnie Lang',
 'Tempo Strings',
 'Mr. I K E',
 'W*A*S*P',
 'Augie Meyers & his Western Head Band',
 'Discreet',
 'Not Breathing',
 'Arturo Sergi (tenor)',
 'Dysrupter',
 'Mount Healthy High School Band (Cincinnati)',
 'The Yellow Payges',
 'Willie Nelson',
 'Robert Shaw',
 'Blood Incantation',
 'Mary Gauthier',
 'Remanon',
 'Jesus Sanchez Mariachi',
 'Orquesta Amante con Mike Arocha',
 'Michael James Carey',
 'Amy Grant',
 'Agent-C',
 'Urban Heat',
 'Wendy Moten',
 'Jocelyn Enrique',
 'Carla Mauri',
 'Kottonmouth Kings',
 'Bett Butler Band',
 'Mariachi Alegre',
 'Vallecitas Leopards',
 'Ron Wilkins Quintet (Ron Wilkins, Paul Heniry, Morgan King)',
 'Saunders King and his Orchestra',
 'The Tex-Sons',
 'Tonal Jones',
 'Otis Day and the Knights',
 'Trans Siberian Orchestra',
 'Balaam and the Angel',
 'Deric Ruttan',
 'Mad 1',
 'Muddy Waters Quintet',
 'Kevin and the Blacktears',
 'Thievery Corp.',
 'In June',
 'WB Inc.',
 'Two for Tuesday',
 'Webb Pierce',
 'Tino Drima',
 'Chris Hawkes',
 'Bett Butler',
 'Jimmy Lee Jones',
 'Nirvana',
 'Spotlight Vultures',
 'Hero',
 'Tropical Hawaii',
 'Jack Green',
 'BJ Barham (American Aquarium)',
 'Grupo Folklorico',
 'Lohnny Lyon',
 'Milez',
 'Ryan Bonn',
 "St. Olaf's College A Cappella Choir",
 'Jonny Martinez y Grupo Bravo',
 'Espuela Dorada',
 'M.O.D.',
 'Chris Salinas & The Wild Grass Band',
 'Blind Date',
 "Herman Waldman's Orchestra",
 'The Drifters (Grand Opening)',
 'Carleton Pride',
 'X',
 'Ray Charles & His Orchestra with the Raelettes',
 'Stage 1 - Stevie Ray Vaughan & Double Trouble',
 'Footloose',
 'Pinhead',
 'Celebration Circle',
 'Entombed',
 'Michael Levine',
 'Marshall Styler)',
 'Guadalupe Church Mariachi',
 'Ed Shaughnessy',
 'the Ghost',
 'Stevie Ray Vaughn and Double Trouble',
 'The Jenkins',
 'The Blue Note Ringos',
 'Greensleeves',
 'Gary Allan',
 'Race Villarreal & Real Me',
 'Rixton',
 'Killing Seasons',
 'Textones',
 'Michael Schenker',
 'Too Many Zoo X Big Freedia',
 'Sophie Braslau (contralto)',
 'Rayrito Tropical',
 'Bill Oliver',
 'Charlie Wood and his Band',
 'Will Riley',
 'The Great 85',
 'Ms. B. Haven',
 'Michael Ballew',
 'Edith MArquez',
 'Maya Angelou',
 'Twila Paris',
 'The Jones Boys',
 'Dean Vallecillo',
 'DJ Riggz',
 'Cecil Carter/Tim McWright Quintet',
 'David Wayne Band',
 'Metalachi',
 'James Cotton Band',
 'Kenny Dale',
 'Esteban Jordan y el Rio Jordan',
 'Depeche Mode',
 '2 Chainz',
 'Violence & Hate',
 'The Quiet Life',
 'Juke Box 40',
 'William Shatner',
 'The Stardust Cowboys',
 'Tom Frost',
 'Potliquor',
 'NIIS',
 'Canned Heat',
 'Ernie Durawa',
 'the San Antonio District Chorus',
 'Matheus Church',
 'Jakob Botello',
 'As Cities Burn',
 'Spin FX',
 'Brick + Mortar',
 'the Entertainers',
 'Electro Chemists',
 'DJ Despeinada',
 'Country Men',
 'Tommy Cowan',
 'Skandalo',
 'The Visitor',
 'Sisqo',
 'Eyewash',
 'The Woodwinds Quintet',
 'Smiley Whitley and his Texans',
 'The Levis',
 'Exit Gate',
 'Jose Luis Rodriguez',
 'Jazzworks',
 'Nightriot',
 'King Clave',
 'The Merles',
 'Medusa Complex',
 'Forced Entry',
 'Tommy Cash',
 'Big Cedar Fever',
 'Aly and AJ',
 'Clark St. Bridge',
 'Cell 69',
 'Damien Escobar',
 'Gail Wettstein',
 'The Four Lovers',
 'Martyn Joseph',
 'Jitterbug Jam Session',
 'the Bel-Airs',
 'The Other Bandaholics',
 'Todd Snider',
 'OBG Band (with West Side legends Rudy “Tee” Gonzales, Ricky “Güero Polkas” Davila and Johnny Hernandez)',
 'Uptown Creepers',
 'Miguel Aceves Mejia',
 'Jerry King and Bruce Hathaway',
 'Toat Lee Bluz',
 'Soncache',
 'The Flaming Lips',
 'Zeecekeely',
 'DJ Ely Bat',
 'Oddzar',
 'Slowpoke',
 'Dee Burleson',
 'The Whiptails',
 'Shannon Trompeter (pinao)',
 'Glen H. Lane',
 'Allman Brothers',
 'The New Variety Band',
 'J Cole',
 'BoDeans',
 "Ida Siddon's Mastadons",
 'Anuna',
 'Joe Moreno',
 'Justin Heflin',
 'Dave Wagner Band',
 'Courtney Woods',
 'Ian Davidson (oboe)',
 'Baja Marimba Band',
 "R.J.'s Latest Arrival",
 'Drivin Rain',
 'Appointed by Grace',
 'Ruben Ramos & Texas Revolution',
 'Curly Mays',
 'Delbert McClinton & Steve James',
 'Victor Hugo Ruiz y el Combo la Conquista',
 'Willie Mabon',
 'Terry Henkins',
 'the Honeybears',
 'Hellis',
 'Sylvia and Lynnie',
 'Jackie on Acid',
 'The Higher',
 'Van Wilks',
 'San Antonio Civic Orchestra',
 'Mark Maniscalco',
 'Dying Fetus',
 'Willis Hysaw',
 'Joe Tex',
 'Great Divide',
 'The Clever Name Band',
 'Sammi Smith',
 'Sandy Sandy y la Revancha',
 'Clint Taft and the Buck Wild Band',
 'URBAN 15',
 'Los Coyotes de Ruben Rios',
 'Isaac Jacob Band',
 'DJ Malediction',
 'Jon Hendricks',
 'Grupo Zaffir',
 'Season Ammons',
 'La Luz',
 'Los Desperadoz',
 'Joe Lopez',
 'Conjunto San Antonio',
 'Tyrones',
 'Loaded',
 'Dehumanize the Machine',
 'Alter Bridge',
 'All-Nite Truckstop',
 'Linda Vos',
 'Mingo Saldívar y sus Tremendos Cuatro Espadas',
 'Bonnie Owens & the Strangers',
 'Trio Los Paisanos',
 'Judy Carol',
 'Julie and Michele',
 'Rhythmics School of Kathak Dance',
 'Josh Groban',
 'El Chatanooga',
 'Chris Duarte',
 'Sandra K. McCowen',
 "Flyin' A's",
 'Mikele Buck',
 'Dustin Lynch',
 'Charlotte Kendrick',
 'For Your Ears Only',
 'Josh Glenn',
 'Denis Dietz',
 'Jerry Jeff Walker',
 'Dreamscape',
 'The Golden Roses',
 'Rossy y Su Grupo Yoko',
 'Sundance',
 'Cecil and Sylvia',
 'Wayne Wilson & the Bad Boys',
 'San Antonio Brass Band',
 'The Wood Bee Soldiers',
 'Howard Payne College Band',
 "Howlin' Devils",
 'Linda Perry',
 'Deya',
 'Relient K',
 'Shooting Star',
 'Dueto Carta Blanca de Jorge y Mague',
 'Emily Herring',
 'Jim Reeves',
 'South Austin Moonlighters',
 'Solarized Trio',
 'Desolate until Decomposed',
 'Eddie Fuller',
 'Felt Nun',
 'Dynamite Kidd',
 'Jeery Jeff Walker',
 'Chris Taylor',
 'Grange Orchestra',
 'Linda Laurie',
 'Los Rumores',
 'Alicia C',
 'Mike Laure Y Sus Cometas',
 'Los Tex-maniacs and Henry Zimmerle',
 'Ataris',
 'Kid Curry Stage 2 - Patsy Torres',
 'Christianmingle',
 'Flora Purim; Bruce Edwards with Carol Cisneros; Jan Halsema and Holland',
 "Shinin' Pride",
 'Bonnie Guitar',
 'Robert Earl Keen with Lloyd Maines',
 'Downtown Boys',
 'Bobby Kapp',
 'Nations Afire and Hard Luck Heroes',
 'San Antonio Symphony Orchestra featuring Gary Graffman (piano)',
 'Queen',
 'Hot for Crime',
 'Raw Brigade',
 'Los Gauchos de Argentina',
 'Glen Campbell',
 'Will Downing',
 'Drum Corps International',
 'Nguyen Family',
 'Georgia Parker',
 'William Carter (piano)',
 'Dan Hicks & his Hot Licks',
 'Ernie Isley',
 'Barbara Nesbitt',
 'Claire Holley',
 'Quincy Harper',
 'Cutthroats',
 'Mrs. Donald Carle',
 'Ram Herrera & the Outlaws',
 'Vitriol',
 'Ron Bilbrey',
 'Harfmann Duo',
 'Ken-David Masur (baritone)',
 'Andre Rieu',
 'Tha Midax',
 'Johnny Lyons and the Nu-Notes',
 'Danny Davis',
 'Insecticide',
 'Primitive Modern',
 'The Ricky Nelson Show',
 'Ivan Davis (piano)',
 'Texas Latino',
 'Rhythm of Fear',
 "Mother's Finest",
 'Jordan Guana',
 'Bobby Mitchell',
 'Kent & Jenni Finlay',
 'Shanghai Steal',
 'Ashlee Rose',
 'Johnny Torres',
 'Mac Wiseman',
 'Jim Messina',
 'Frenchie Burke',
 'the Alamo-Dels',
 'Althea Rene',
 'The Jenkins Sisters',
 'Elvis Presley',
 'Black Crowes',
 'Ben Kweller',
 'The Psychedelic Furs',
 'Karizzia',
 'Conjunto Los Pavos Reales',
 'Cactus Country Band',
 'Red Jumpsuit Apparatus',
 'vocals; Chris Wolfe',
 'Math the Band',
 'Odyssey',
 'Laura Yvette',
 'Ricardo Montaner',
 'Fallon Franklin',
 'Phoenix Recoil',
 'Katchafire',
 'Bidi Bidi Banda',
 'Brian and the Bar Flies',
 'Nancy Wilson',
 'Paul Neubauer',
 'Eye Alaska',
 'Brenda Russell',
 'the Circle C Band',
 'Tommy Newman',
 'Mancilla Brothers',
 'Rude Awakening',
 'Mariachi Gilberto Reyes',
 'Perx',
 'The Native Howl',
 'IWrestledABearOnce',
 'Atlantic/Pacific',
 'Fools',
 'Paula Mitchell',
 'Michael Salgado and La Contra',
 'CHUD',
 'Uriah Heep',
 'Alan Parsons Project',
 'Linda Allen',
 'Babylonz',
 'Los Nahautlanos',
 'Andrea Bocelli',
 'Raquel',
 'Jimmy Short and the Silver Saddle Ranch Boys',
 'Jerry Galante',
 'Los Forasteros de Nuevo Leon',
 'Neil Wilson (baritone)',
 'Al Schnabel Orchestra',
 'Las Fenix',
 'San Antonio Accordian Club',
 'Mrs. Lovie Mae Banks (formerly of Wings over Jordan)',
 'Joe Piscatelle',
 'The Road Runner Express',
 'Guadalajara Symphony Orchestra',
 'Butch Hancock',
 "Soulja Boy Tell'em",
 'Huey',
 'The Albums',
 'Lake and Palmer',
 'Chilton Vance & Texas Connection',
 'Slobberbone',
 'Dee y Grupo Valiente',
 'Jody and Faye Frymire',
 'Heller Moon Horizon',
 'Dilly Dally',
 'Maria Larson',
 'The Dead Kennedys',
 'Panic the Brave',
 'Felipe Esparza',
 'Mo and the Earth Tones',
 'Wes and Victoria Hamil',
 'Major Harris',
 'Sergio Fachelli',
 'Tides of Man and Of Machines',
 'Red Sovine',
 'Straight Out of Line (Godsmack tribute)',
 'Gerard Jaffe',
 'Taylor Campbell',
 'Paul English',
 'Monte Mongomery',
 'Kenia OS',
 'San Antonio Symphony with guest conductor Jussi Jalas',
 'The Scooterz',
 'Def Lepaord',
 'Joanna Connor',
 'John Michael Montgomery & Jessica Andrews',
 'Mark Gray',
 'Everlast',
 'Rio Blanco',

In [83]:
len(artists_venue_artist_event_sheet)

20320

Finally, I look at the ven_ev_ar_address sheet. There are 11009 artists in this list, which focuses on the core years from 1970 to 2009. Over half the concerts in the data set are in these years.

In [84]:
artists_ven_ev_ar_address_sheet = set(ven_ev_ar_address['Artist'].dropna().str.strip())

In [85]:
len(artists_ven_ev_ar_address_sheet)

11009

Now, I'll update the unique artists set with the results from the two other sheets. By adding them to a set, duplicates will be eliminated. The length of the entire set is now 20419. 

This suggests that there are 99 artists somewhere that are not in the master concert sheet. Most likely these are artists that got typos edited in one sheet but not in another.

In [86]:
unique_artists.update(artists_venue_artist_event_sheet)

In [87]:
unique_artists.update(artists_ven_ev_ar_address_sheet)

In [88]:
len(unique_artists)

20419

To find out which are these 99 artists, I use a set difference operation. I verify it by checking the length of the resulting set. It is 99 artists. This suggests a need to investigate this particular group of names as they are inconsistent or problematic in some way.

In [89]:
only_in_artists_index = (artists_artist_index - artists_ven_ev_ar_address_sheet - artists_venue_artist_event_sheet)

In [90]:
only_in_artists_index

{'"The Italian Cowboy"',
 '(Fools?)',
 '(TLC - cancelled)',
 '01 Blues',
 '7seconds',
 'AC',
 'Al Hirt w',
 'Al Sturchio and His Orchestra',
 'Better than Ezra',
 'Bobby "Tossin\' and Turnin\'" Lewis',
 'Bobby Baker & the Longnecks',
 'Campanas De America,Ram Herrera',
 'Charlie and the Cool Cats',
 'Chick Corea (trio w',
 'DC',
 'Dave Wakeling',
 'Deborah Hay',
 'Earl "Fatha\' Hines',
 'Emerson',
 'Emotions',
 'English Beat w',
 'Evelyn "Champagne" King',
 'Frank Rodarte & los Blues Vatos',
 'Frank Rodarte & the Alamo All-Stars',
 'George Jones & Tammy Wynette',
 'George Strait,',
 'Hannah Montana',
 'Hate',
 'Henry Mancini w',
 'Infectious Grooves,',
 'Jim Cullum and Happy Jazz Band',
 'Jim Cullum and the Happy Jazz Band',
 "Jim Cullum's Happy Jazz Band",
 'Joe "King" Carrasco',
 'Joe "King" Carrasco and the Crowns',
 'Joe "King"Carrasco & Esteban Jordan',
 'Joe Reyes Quartet',
 'Joel Dilley Quintet',
 'Jr.',
 'Kiss',
 'LeAnn Rimes',
 'Less than Jake',
 'Lynn Anderson & Charlie Walker',
 'Lynryd Skynyrd',
 'Mariachi Las Campanas de America',
 'Mariachis Victoria Acosta and Kandi Garcia; Elizabeth "La Cantante" Brackman and Rick Balderrama; Gabe Nieto & the Jalapeño Express; "Little" Henry Lee Padilla; Pablo Urbina de la Traizion and Elemento; Tato Henriquez and Gabe Garcia',
 'Mike Ellis & Funtones',
 'Mike Ellis & Jackie Huddle',
 'New Christy Minstrels w',
 'Paul Elizondo and His Orchestra',
 'Pauline Oliveros',
 'Perry Como w',
 'Pete Fountain and his New Orleans Jazz group',
 'Porter Waggoner & Dolly Parton',
 'PreZence',
 'Ramiro Cervera and his Orchestra',
 'Randy and Ernie Garibay and West Side Horns',
 'Rare Earth and Sugarloaf)',
 'Rock All-Stars (members of Iron Butterfly',
 'Roll Cherry Blues',
 'Roy Haynes and Mirsalov Vitous)',
 'S.A. Symphony',
 'SA Symphony',
 'Sammi Smith & Roy Head',
 'Sammy Davis',
 'San Antonio Symphony "Star Light" Concert',
 'San Antonio Symphony presents Virgil Fox (organ)',
 'San Antonio Symphony with guest conductor David Gilbert',
 'Sara Jordan Powell',
 'Selena and La Sombra',
 'Shirley Jones w',
 'Smothers Brothers w',
 'Steve James & the Vocalions',
 'Stoney LaRue',
 'Tanya Tucker w',
 'The Air Force Band of the West',
 'The Cones Sisters',
 'The Deftones',
 'The Jim Cullum Jazz Band',
 'The Offbeats',
 'The Sergio Lara',
 'The Smith Brothers',
 'The Toadies',
 'The Tyrones',
 'The US Air Force Band of the West',
 'TobyMac',
 'Tomren Shannon',
 'Trick Daddy and 112',
 'We the Kings',
 'Willis Alan Ramsey,',
 'Zap',
 'dc talk',
 'fIREHOSE',
 'the Bett Butler',
 'the Regency Jazz Band',
 'the San Antonio Symphony',
 'the Suspects',
 'the Swindles',
 'the West Side Sound'}

In [91]:
len(only_in_artists_index)

99

Next, I'm going to create a lookup dictionary for artists with their index. This will make it very fast to look up whether an artist already has an index or not.

The rationale for this is as follows. We have 1769 listed artists with indexes already assigned. We don't want to reassign unique indexes; these may be in use somewhere already, so we want to retain unique indexes for all artists that already have one assigned. However, it is clear we have a lot more artists in the data than have these inexes assigned. So as we look over the unique list of all artists, we are going to want to look up whether it has an index, and if not assign it a new one. To make this an efficient and fast task, it's helpful to create a lookup dictionary in advance.

In [92]:
artist_to_index = dict(
    zip(
        artists_index["Name"],
        artists_index["Index"]
    )
)

I'd like the artists to be sortable chronologically in some way, so I'm going to add first appearance and last appearance information for them. To do this, I need to take the current text "Year", "Month", and "Day" columns and convert them into pandas datetime objects.

First, it occurs to me we may be able to save some time. The Ven_Ev_Ar_Address sheet was derived from the Venue_Artist_Event sheet, so I want to see if there are any aritsts in the first that are not in the second. I use a set difference operation. The result is an empty set. There are no artists in the first sheet that aren't in the second sheet. So I can do the date operation entirely on the second set.

In [93]:
artists_ven_ev_ar_address_sheet - artists_venue_artist_event_sheet

set()

Next, I'm going to use a utility I wrote some time ago that transforms string dates into ISO format date objects. Then I'll apply the method to every row in the venue_artist_event sheet and generate a new column, "date". Note that this is not writing the new column to the sheet, just adding it to the pandas data frame I'm working from.

In [94]:
import datetime
from dateutil import parser

def str_date_to_iso(month, day, year):
    
    str_date = f"{month} {day} {year}"
    dt = parser.parse(str_date).date().isoformat()
    
    return dt

In [95]:
venue_artist_event["date"] = venue_artist_event.apply(lambda row: str_date_to_iso(row['Month'], row['Day'], row['Year']), axis=1)

When I ran the method, it flagged a concert in the data by Bob Wills on "February 29, 1962" at the Farmer's Daughter. There was no February 29 in 1962, so I changed it to February 28.

Next, I'm creating a new data frame with all the artists listed next to their first and last appearances in the concert list, by chronological order.

In [96]:
venue_artist_event_dates = (
    venue_artist_event
    .groupby("Artist_Formula")["date"]
    .agg(["min", "max"])
)

In [97]:
venue_artist_event_dates

                                                  min         max
Artist_Formula
 Jimmy Heath                               1982-06-19  1982-06-19
 Robert Casadesus (piano)                  1970-12-05  1970-12-05
!!! Chk Chk Chk                            2023-10-12  2023-10-12
$Not                                       2023-05-09  2023-05-09
'Blue' Gene Tyranny                        1985-06-28  1985-06-28
...                                               ...         ...
vocals]                                    2010-02-27  2010-02-27
west                                       1986-02-08  1986-02-08
with added attraction Curley Mays          1958-03-06  1958-03-06
xxxx                                       1996-06-08  1996-06-08
¿Por qué los hombres aman a las cabronas?  2021-10-24  2021-10-24

[20341 rows x 2 columns]

Inspecting this list, I can see a few issues straight away: an artist just called "vocals]', and an artist called "$Not", another one just called "west". These issues may bear further investigation.

In [98]:
artist_list_rows = []

next_index = artists_index["Index"].max() +1

for artist in unique_artists:
    
    if artist in artist_to_index:
        idx = artist_to_index[artist]
    else:
        idx = next_index
        next_index += 1

    if artist in venue_artist_event_dates.index:
        first = venue_artist_event_dates.loc[artist, "min"]
        last = venue_artist_event_dates.loc[artist, "max"]
    else:
        first = None
        last = None
        
    artist_list_rows.append({
        "Index": idx,
        "Artist": artist,
        "FirstAppearance": first,
        "LastAppearance": last,
    })

result = pd.DataFrame(artist_list_rows)

In [99]:
result

,Index,Artist,FirstAppearance,LastAppearance
0,1770,Jamie DeAnda,2022-04-02,2022-04-02
1,1771,Natalie Rose,2018-04-21,2023-08-27
2,1772,Kolby Cooper,2019-11-09,2023-07-08
3,1773,Field of Seed,2003-10-25,2003-10-25
4,1774,Blind Ignorents,1988-09-09,1988-09-09
...,...,...,...,...
20414,20421,December '63 (Franki Valli & the Four Seasons ...,2021-06-19,2021-06-19
20415,20422,Gordy Quist,2013-08-27,2013-08-27
20416,20423,The Bobby Boyle Trio (houseband),1979-09-12,1979-09-15
20417,20424,Hardluck Heroes,2007-09-02,2007-09-02
20418,20425,Jay Martinez & the Chaser,1987-08-07,1987-08-07

In [100]:
result.to_excel('sounds_data_to_share.xlsx', sheet_name='artistsIndex')

## Venues List

Now I'm going to turn my attention to the venues. As with the artists, we have different lists spread across different sheets. Some have coordinates, some do not. In this case we do not have a unique index for each venue anywhere in the data. We are going to want a list of all unique venues, with all available address and geodata, and a unique identifier for all of them.

We have a sheet called `Layer 1 Venues`. This list has 975 venues with addresses. It also has coordinates for 313 of these. 

Next there is a `Venues No Address` sheet, which I remember I derived at one point in order to be able to focus research on getting new coordinates. This sheet has 1080 venues on it. Considering that `Layer 1 Venues` has only 662 venues without coordinates, that leaves 418 venues in `Venues No Address` that can't be in `Layer 1 Venues`. This suggest some sort of data mismatch occurred, probably between the venues list in `Ven_Ev_Ar_Address` and the venues in `Layer 1 Venues`.

We have `venues_with_coordinates` in the revised product 1 master. This consists of the list from `Layer 1 Venues`, but with additional coordinates gathered by Angelina Cortes through R tidyverse. There are 965 venues with coordinates. One of them appears to have been subject to an editing error (The Copper Penny), because the longitude and latitude are the same except one has fewer decimals. There are ten venues still without coordinates in this list.

Then we have `Ven_Ev_Ar_Address`. This is the list of concerts between 1970 and 2009, which formed the basis for "Project 1" ("Get Lost") of Sounds of San Anto. 

Finally there is the authoritative source list, `Venue_Artist_Event`, with the complete list of all concerts and venues -- but no addresses or coordinates.

I'll follow the same process as with artists. Firstly I'll develop unique lists based on each data source, then compare and form a unified list. I'll start by loading the sheets that I haven't yet loaded. Then I'll inspect the sheets that have venue information, so I can see the column headings.

In [101]:
layer_1_venues = pd.read_excel('spreadsheets/product1_data_master_rev.xlsx', sheet_name='Layer 1 Venues')
venues_no_address = pd.read_excel('spreadsheets/product1_data_master_rev.xlsx', sheet_name='Venues No Address')
venues_with_coordinates = pd.read_excel('spreadsheets/product1_data_master_rev.xlsx', sheet_name='venues_with_coordinates')

In [102]:
ven_ev_ar_address.head()

,Index,Month,Day,Year,Venue,Event_Artists,Address,Zip,Longitude,Latitude,Artist,Event,City,State
0,2581,January,1,1970,San Antonio Convention Center Arena,"KBER Holiday Show: Willie Nelson, Charley Pri...",601 Hemisfair Plaza Way,78205.0,NaN,NaN,Willie Nelson,KBER Holiday Show,San Antonio,Texas
1,2581,January,1,1970,San Antonio Convention Center Arena,"KBER Holiday Show: Willie Nelson, Charley Pri...",601 Hemisfair Plaza Way,78205.0,NaN,NaN,Charley Pride,KBER Holiday Show,San Antonio,Texas
2,2581,January,1,1970,San Antonio Convention Center Arena,"KBER Holiday Show: Willie Nelson, Charley Pri...",601 Hemisfair Plaza Way,78205.0,NaN,NaN,Grandpa Jones,KBER Holiday Show,San Antonio,Texas
3,2581,January,1,1970,San Antonio Convention Center Arena,"KBER Holiday Show: Willie Nelson, Charley Pri...",601 Hemisfair Plaza Way,78205.0,NaN,NaN,David Houston,KBER Holiday Show,San Antonio,Texas
4,2582,January,16,1970,San Antonio Municipal Auditorium,Vikki Carr,100 Auditorium Cir.,78205.0,NaN,NaN,Vikki Carr,NaN,San Antonio,Texas

In [103]:
venue_artist_event.head()

,Month,Day,Year,Venue,Event_Artists,Artist_Formula,Event_Formulas,Index,date
0,September,10,1857,St. Mary's Catholic Church,French Mountaineer Singers,French Mountaineer Singers,NaN,1,1857-09-10
1,June,25,1869,Menger Hotel,General Mason Farewell Party: San Antonio Bras...,San Antonio Brass Band,General Mason Farewell Party,2,1869-06-25
2,July,4,1874,San Pedro Park,San Antonio Brass Band,San Antonio Brass Band,NaN,3,1874-07-04
3,October,9,1874,"San Pedro Springs, Turner Hall",Tenth Texas Saengerfest,Tenth Texas Saengerfest,NaN,4,1874-10-09
4,October,10,1874,"Casino Hall, Turner Hall",Tenth Texas Saengerfest,Tenth Texas Saengerfest,NaN,5,1874-10-10

In [104]:
layer_1_venues.head()

,Venue_Name,Longitude,Latitude,Address,Zip,City,State
0,1033 Club,-98.480763,29.436116,1033 Avenue B,78215.0,San Antonio,Texas
1,151 Saloon,-98.690386,29.464097,10619 Westover Hills Blvd,78215.0,San Antonio,Texas
2,1902 Nightclub,-98.478216,29.421548,1174 East Commerce St,78205.0,San Antonio,Texas
3,210 Kapone's,-98.478815,29.425150,1223 East Houston,78205.0,San Antonio,Texas
4,4th Quarter Sports Bar,-98.569389,29.524564,8779 Wurzbach Rd,78240.0,San Antonio,Texas

In [105]:
venues_no_address.head()

                            Venue
0       Bayt-El-Awhe Coffee House
1          Baptisit Temple Church
2            Providence Hall-OLLU
3            McCullom High School
4  Theater for the Perfoming Arts

In [106]:
venues_with_coordinates.head()

,Venue_Name,Longitude,Latitude,Address,Zip,City,State,...8,full_address,needs_geo,Unnamed: 10
0,1033 Club,-98.480763,29.436116,1033 Avenue B,78215.0,San Antonio,Texas,NaN,"1033 Avenue B, San Antonio, Texas, 78215",False,NaN
1,151 Saloon,-98.690386,29.464097,10619 Westover Hills Blvd,78215.0,San Antonio,Texas,NaN,"10619 Westover Hills Blvd, San Antonio, Texas,...",False,NaN
2,1902 Nightclub,-98.478216,29.421548,1174 East Commerce St,78205.0,San Antonio,Texas,NaN,"1174 East Commerce St, San Antonio, Texas, 78205",True,NaN
3,210 Kapone's,-98.478815,29.42515,1223 East Houston,78205.0,San Antonio,Texas,NaN,"1223 East Houston, San Antonio, Texas, 78205",True,NaN
4,4th Quarter Sports Bar,-98.569389,29.524564,8779 Wurzbach Rd,78240.0,San Antonio,Texas,NaN,"8779 Wurzbach Rd, San Antonio, Texas, 78240",False,NaN

The master sheet is venue_artist_event, so I'll start there. I get the list of unique individual venues listed there. There are 2602 in total.

In [107]:
venues_from_venue_artist_event = set(venue_artist_event['Venue'].dropna().str.strip())

In [108]:
len(venues_from_venue_artist_event)

2602

Next, I'm going to look at the ven_ev_ar_address sheet. In theory, this is derived from venue_artist_event, only filtered by dates (1970-2009) and with geodata added. I'll derive the unique venues list from this sheet, then use a set difference operation to confirm this. The set of venues in ven_ev_ar_address that aren't also in venue_event_artist is an empty set, so we can effectively ignore this sheet in building a unique venues list.

In [109]:
venues_from_ven_ev_ar_address = set(ven_ev_ar_address['Venue'].dropna().str.strip())
len(venues_from_ven_ev_ar_address)

1548

In [110]:
venues_from_ven_ev_ar_address - venues_from_venue_artist_event

set()

Next, I'll investigate the "Layer 1 Venues" sheet. This one does present some interesting results. It has 974 venues listed. When I use a set difference operator, I see there are 369 venues in Layer 1 Venues that are not in Venue_Artist_Event. I inspect the list, and find that some of these are spelling variants. As an example, in Layer 1 Venues we have the "Big Apple Night Club" but in Venue_Artist_Event this is "Big Apple Nite Club". Some of these are not so easily explained. Thus, we have the "Bier Garten Riverwalk" in Layer 1 Venues, but there is no mention of it in Venue_Artist_Event.

I conclude that these are somewhat separate lists. We have, on the one hand, a list of concerts with their associated venues, which is derived from the original SAPL librarian's list. Then there is this separate list of venues, of which about one third appear to be just names of venues, with no associated concert data in the other sheet.

The problem is, this (Layer 1 Venues) is the sheet we used as the primary basis for geocoding. But, it's not really the same as the list of concert locations. In retrospect, it would have been better to use the unique venues list from `ven_ev_ar_address` instead.

In [111]:
venues_from_layer_1_venues = set(layer_1_venues['Venue_Name'].dropna().str.strip())

In [112]:
in_layer_1_venues_but_not_ven_ar_ev = venues_from_layer_1_venues - venues_from_venue_artist_event

In [113]:
len(in_layer_1_venues_but_not_ven_ar_ev)

369

In [114]:
in_layer_1_venues_but_not_ven_ar_ev

{'108 Noth Centre',
 '4th Quarter Sports Bar',
 'Abracadabra',
 'Alamo Ice House',
 "Aldaco's Mexican Restaurant",
 "Aldo's Ristorante Italian",
 'Antonio Ballroom',
 'Antonio Strad Violin',
 'Apple Tree Lounge',
 'Aquariaum Disco',
 'Aragon Blue Room',
 'Artisan on Alamo Distillery',
 'Artpace San Antonio',
 'Azuca Nuevo Latino Restaurant & Bar',
 'Bar 414',
 'Bar America',
 'Bar Rojo at The Grand Hyatt Hotel',
 "Barclay's Piano Bar",
 "Beto's Comida Latina",
 'Bier Garten Riverwalk',
 'Big Apple Night Spot',
 'Big Band Fun Club',
 "Big Bob's Burgers",
 'Big Texas Ice House',
 'Bihl Haus Arts',
 "Billy D's Club",
 'Black Canteen',
 'Blind Tiger Comedy Club',
 'Blue Note Lounge',
 'Blue Star Brewing Co.',
 "Bo's Rodeo",
 "Bohanan's Prime Steaks & Seafood",
 'Boiler House Texas Grill & Wine Garden',
 'Bombay Bicycle Club',
 'Bone Club',
 'Bonesshakers Tap House and Pizzeria',
 'Boozehounds',
 'Botika Peruvian-Asian Restaurant',
 'Bottom Bracket Social Club',
 'Boudro’s Texas Bistro',
 'Bowlero',
 'Brews Brothers',
 'Brick at Blue Star Arts Complex',
 'Brooks Pub',
 "Brooster's Backyard IceHouse",
 'Bull Moose',
 'Burgundy Woods',
 'Burnhouse Cigar & Martini Lounge',
 'Cactusland Brewery',
 'Caliente Harley-Davidson',
 'Candlelight Coffeehouse & Wine Bar',
 'Carousel Court Shopping Center',
 'Casablanca',
 "Casey's Saloon and Dance",
 'Castle Hills Market Shopping Center (Two locations - (2211 NW Military Highway)',
 'Cattlemen Square Tavern',
 'Chance Are Lounge',
 'Chandelier Club',
 "Charlie Brown's Neighborhood Bar & Grill",
 'Chelsea Street',
 'Club Eldorado',
 'Co Lab',
 'Come On Inn',
 "Connor's Night Club",
 "Conroy's Irish Pub",
 'Cooter Browns Saloon',
 'Corner Pocket Bar',
 'Cottonwood Country Club',
 'County Line - Downtown',
 'Courtyard',
 'Coyote Ugly Saloon',
 'Crockett Park',
 'Crumpets Restaurant & Bakery',
 'Crystal Sea Drama Co Inc',
 'Cured at Pearl',
 "D'Angelo's",
 "Dad's",
 "Dad's Karaoke",
 'Daiquiri Lounge',
 'Deer Crossing Saloon',
 'Denim and Diamonds',
 'Deol Bar',
 "Doc Holliday's",
 'Downtown San Antonio (Alamo Address inputted)',
 'Draft Station at Sonterra',
 'Drink Texas Bar',
 'Drink Texas Stone Oak',
 "Durty Nelly's Irish Pub",
 "Eagle's Hall",
 'Edge of Town',
 'Edwards Ridge Distillery',
 "El Antonio's Hacienda Ballroom",
 'El Jarro',
 'El Luchador Bar',
 'El Machito',
 'El Taxco',
 'El Tropicano Nite Club',
 'Element Ultra Lounge',
 'Embers Wood Fire Grill & Bar',
 'Epic Bar',
 'Esperanza Peace & Justice Center',
 'Faust Brewery',
 'Feast Restaurant',
 'Five Stones Artisan Brewery',
 'Flying Saucer Draught Emporium',
 'Fralo’s Art of Pizza',
 "Frankie G's Sports Bar",
 'Freetail Taproom',
 'Frost Bank Center',
 'Fun Palace',
 'G.W. Carver Library Auditorium',
 'Garden Tea Lounge',
 'Gemini Ink',
 "Graffiti's",
 'Grayze on Grayson',
 'HEAT Nightclub',
 'Hallelujah Hollywood',
 'Hard Rock Cafe | San Antonio',
 'Hard Times Saloon and Party House',
 'Helotes Event Hall',
 'Henry B. Gonzalez Convention Center',
 'Here it Tiz',
 'Hill Country Farmers Market',
 'Historic Pearl',
 'Historic Sunset Station',
 'Holiday Club',
 'Hollywood Cafe',
 'Hookah House At Bentleys',
 "Hooligan's Bar & Grill",
 'Hot Joy',
 'Hot Shot Night Club',
 'Howl at the Moon',
 'Hyatt Hill Country Resort',
 'Iguana Bay Bar & Grill',
 'Illusions Theatre at the Alamodome',
 'Imagine Books & Records',
 'Irish Pub',
 'Iskcon Mission Society',
 'Ivory Lounge & Nightclub',
 'JW S Bracken Saloon',
 "Jaime's Place",
 'Jimenez Restaurant and Bar',
 'Jo Long Theatre',
 "Joe's Volcano",
 "Josabi's Acres",
 'Juniper Tar',
 'Just Country',
 'K23 Gallery',
 'Kelly Field Terrace',
 'Keyhole (#1)',
 'Keyhole (#2)',
 'Keystone Club',
 'Knave Pub',
 "Krueger's Bar and Party House",
 'La Fonda on Main',
 'La Playa',
 'La Quinta Inn and Suites Riverwalk',
 'La Rancherita Night Club',
 'La Rumba Nite Club',
 'La Tuna Grill',
 'La Villita Historic Arts Village',
 'Lamp Post Lounge',
 "Larry's Cantina",
 "Larry's Lounge",
 'Lartos Lounge',
 'Las Canarias',
 'Las Ramblas at The Hotel Contessa',
 'Las Vegas Night Club',
 'Last National Bank',
 'Last Stand',
 'Lejac Club',
 "Let's Go Bottom Up",
 "Li'L Hut Lounge",
 "Limon's Lounge",
 "Lindbergh's",
 'Lion and Rose British Restaurant and Pub - Park North',
 'Lion and Rose British Restaurant and Pub -La Cantera',
 'Little Italy Restaurant',
 'Little Las Vegas Club',
 'Little Red Barn Steakhouse',
 'Los Barrios Mexican Restaurant',
 "Lyndy's Great Indoors",
 'Mad Dogs British Pub Riverwalk',
 'Maggiano’s Little Italy San Antonio',
 'Mai Tai',
 'Main Plaza Conservancy- San Antonio',
 'Make My Day Lounge Make sure to use 12114 Nacogdoches Rd',
 'Manana',
 'Mantle Art Space',
 'Margaritaville',
 "Mario's Mexican Restaurant",
 "Marty's Outback",
 "Mary's Café",
 'Matamoros Restaurant y Cantina',
 'Maverick Music Festival',
 "Max's Lil'B",
 "Max's Wine Dive",
 'Mcqueeney Hall',
 'Medina County Fairgrounds',
 "Mendiola's Ballroom",
 "Milo's Backyard",
 'Mine Shaft Saloon - Inside Magic Time Machine',
 "Monterrey Jack's-Ingram",
 'Moulin Rouge Lounge',
 'Movement Gallery/Galeria del Movimiento',
 'Musical Arts Center of San Antonio, Inc. (1604)',
 'Musical Arts Center of San Antonio, Inc. (I-10)',
 "Nana's Grill",
 "Neal's Ice House",
 'Network for Young Musicians',
 'Newsroom',
 'On The Rocks Pub',
 "Paesano's 1604",
 'Palo Alto College Performing Arts Center',
 'Pan American Nite Club',
 "Panama's Red",
 'Paramour Bar',
 'Pearl Stable',
 "Pedrotti's North Wind Ranch",
 'Perch Coworking Space',
 'Performing Arts San Antonio',
 'Pericos Mexican Restaurant',
 'Perry’s Steakhouse and Grille',
 'Peters Brothers',
 'Playpen North',
 'Plaza de Armas Gallery',
 'Poco Loco',
 'Prize Bull Saloon and Dance Hall',
 'Pueblo Hall & Activity Center',
 'Pump House Lounge',
 'Pusi Kat',
 'R & J Lounge',
 'R & J Lounge Music Pavillion',
 'R & R Ice House',
 "RC Peacock's",
 'Radius Center',
 'Raffles Restaurant and Bar',
 'Rainbow Cafe',
 'Rancho Bar',
 'Random Beer Garden',
 "Rascal's Night Club",
 "Raul's``",
 "Ray's Ice House",
 'Razzle Dazzle',
 'Recovery Room',
 "Reed's Red Derby",
 'Repitlez Sports Bar',
 "Ricardo's on the River",
 'Riff House Concerts',
 "Rosario's Café y Cantina",
 'Round Table Club',
 "Rouring 20's",
 'Roxy Sports Bar -2801 Pat Booker Rd, Universal City, TX 78148',
 "Ruth's Chris Steak House-Concord Plaza",
 "Ruth's Chris Steak House-Grand Hyatt",
 'Ruth’s Chris Steak House –La Cantera',
 'SA Country Saloon',
 'SAY Si',
 'SIN 13',
 'San Antonio Club',
 'San Antonio Event Center',
 'Sanchos Cantina & Cocina',
 "Sandra's Bar & Live Music",
 'Scobee Education Center',
 'Serape Club',
 'Seven Oaks',
 'Shenanygans -Sports Bar & Lounge',
 'Silver Dollar Saloon',
 'Slackers Sports Bar Naco',
 'Slackers Sports Bar North star',
 'Smoke: The Restaurant',
 "Snoop's Tavern",
 'SoHo Wine & Martini Bar',
 'Social House',
 'South Texas Museum of Popular Culture',
 'Southern Lady',
 'Southtown Vinyl',
 "Sparky's Pub",
 'Speedway Sports Bar',
 'Speedway Sports Bar II',
 "St. Albert's Hall",
 'St. Mary University Treadway Recital Hall',
 "St. Mary's Brewing Company",
 "St. Mary's Pit",
 'Suburban Garden(s)',
 "Sugar Daddy's",
 "Sum'thin Diff'Rent",
 'Sumthin Different',
 'Sunken Garden',
 'Swizzle Stick',
 'Taco Garage',
 'Tacos & Tequila',
 'Taqueria La Gloria- Pearl',
 'Teddy Bear Lounge & Café',
 'Tejas Rodeo, Steakhouse and Saloon',
 'Texas 21 Funhouse',
 'Texas Burgers, Brews, and Blues',
 'Texco Nite Club',
 'The Art Institute of San Antonio',
 'The Bar on Broadway',
 'The Beer Depot',
 'The Brass Tap',
 'The Broadway 50 50',
 'The Brooklynite',
 'The Carver Community Cultural Center – The Jo Long Theatre for Performing Arts',
 'The Classic Theater',
 'The Copper Penny',
 'The Crazy Ape',
 'The Davenport Lounge',
 'The DoSeum',
 'The Friendly Spot Ice House',
 'The Frutería -Botanero',
 'The Garter North',
 'The Hangar Bar',
 'The Hoppy Monk',
 'The Jackson Ranch in the Heart of San Antonio',
 'The Korova',
 'The Local Bar',
 'The Monty and Ivy Hall',
 'The Nestle Inn',
 'The Other Women',
 'The Phantom Room',
 'The Ringer Pub',
 'The Rock',
 "The Rockin' K",
 'The Service Station Cafe and Beer Garden',
 'The Settlement',
 'The Silver Slipper Nite Club',
 'The Squeezebox',
 'The Three-Legged Monkey',
 'The Twig Book Shop',
 'The Underground Metal Haven',
 'The Vineyard Club',
 'The Warehouse',
 'Thirsty Camel Bar & Lounge',
 'Ticket Sports Pub',
 'Tiffany Palace',
 'Tonic Bar',
 'Torres Dance Hall',
 'Toyota Field San Antonio',
 'Trading Post',
 "Tramp's",
 'Tre Trattoria',
 'Treasures Events',
 'Tropics Dinner Club',
 'Twin Mountain Inn',
 'Two Step Restaurant and Cantina',
 'University Bowl',
 'VFW Post 7108 Helotes Post',
 "VIP's`",
 'Velvet Turtle',
 'Ventura San Antonio',
 "Virginia's Ace-Hi-Lounge",
 'Viva Tacoland',
 'Vybrations Luxury Lounge',
 'Water Street Oyster Bat',
 'Watson Fine Arts Center',
 'Wax Club Lounge',
 'Weathered Souls',
 'Web House Café & Bar',
 'West Avenue Club & Sports Bar',
 'Whiskey Cake',
 'Wild Wild West',
 'Willis Corner',
 'Wyndham Garden Riverwalk',
 'Yellow Rose Country and Western Bar',
 'Zanzibar Nite Club',
 'Zip 2 Five Sports and Spirits',
 'Zombies Bar and Live Music Venue'}

In [115]:
len(layer_1_venues)

974

Next, I look at venues_with_coordinates. This should be identical to layer 1 venues, but it isn't. There are 18 venues that appear in Layer 1 Venues but not in venues_with_coordinates. This should be impossible. Closer inspection suggests these are cases where symbols have been differently represented, possibly due to software (Microsoft Excel?) or operating system (Word vs. Mac) differences.

For example, the dash in 'The Carver Community Cultural Center – The Jo Long Theatre for Performing Arts' is represented as 'â€“' in venues_with_coordinates. I can't tell why Python thinks there is a difference between the representations of 'Raul's``'. I do know those backticks shouldn't be there. In venues_with_coordinates, acceents have been transposed, for example Rosario's Café y Cantina is Rosario's CafÃ© y Cantina. 

Others appear to have been corrected in venues_with_coordinates. For example, '108 Noth Centre', clearly a typo, has been changed to '108 North Centre' in venues_with_coordinates.

So, these 18 venues will generate false double listings in our eventual unique venues list and require manual editing and attention.

In [116]:
venues_from_venues_with_coordinates = set(venues_with_coordinates['Venue_Name'].dropna().str.strip())
venues_from_layer_1_venues - venues_from_venues_with_coordinates

{'"Menudo Acres"',
 '108 Noth Centre',
 "Alexander's Bar and Café",
 'Bonesshakers Tap House and Pizzeria',
 'Boudro’s Texas Bistro',
 'Fralo’s Art of Pizza',
 'Maggiano’s Little Italy San Antonio',
 "Mary's Café",
 'Perry’s Steakhouse and Grille',
 'Powerhouse Café',
 "Raul's``",
 "Rosario's Café y Cantina",
 'Roxy Sports Bar -2801 Pat Booker Rd, Universal City, TX 78148',
 'Ruth’s Chris Steak House –La Cantera',
 'Teddy Bear Lounge & Café',
 'The Carver Community Cultural Center – The Jo Long Theatre for Performing Arts',
 'The Frutería -Botanero',
 'Web House Café & Bar'}

In [117]:
venues_from_venues_with_coordinates

{'1033 Club',
 '108 North Centre',
 '1428 S. Presa St.',
 '151 Saloon',
 '1902 Nightclub',
 "210 Kapone's",
 '321 Max',
 '4th Quarter Sports Bar',
 '500 Block Madison',
 '500 Carolina Street',
 '502 Bar',
 '801 West Russell Place',
 'AT&T Center',
 'Abracadabra',
 "Acapulco Sam's",
 'Accents',
 'Acquarium III',
 'After Midnight',
 'Aggie Park',
 'Agudas Achim Synagogue',
 'Alameda Theater',
 'Alamo Beer Company',
 'Alamo City Music Hall',
 'Alamo Heights United Methodist Church',
 'Alamo Ice House',
 'Alamo Plaza',
 'Alamodome',
 "Aldaco's Mexican Restaurant",
 "Aldo's Ristorante Italian",
 "Alexander's Bar and CafÃ©",
 "Alfred's",
 'Alzafar Shrine Temple',
 'American Legion Post 539',
 'Anaqua Room',
 "Andrew's 281 Live",
 'Anhalt Hall',
 "Annie & Ed's",
 'Antonian Ballroom',
 'Antonio Ballroom',
 'Antonio Strad Violin',
 'Apple Tree Lounge',
 'Aquariaum Disco',
 'Aragon Blue Room',
 "Arjon's International Club",
 'Arneson River Theatre',
 "Arthur's",
 'Artisan on Alamo Distillery',
 'Artpace San Antonio',
 "Arturo's Sports Bar & Grill",
 'Austin Municipal Auditorium',
 'Avalon Grill',
 'Aztec Theatre',
 'Azuca Nuevo Latino Restaurant & Bar',
 "BJ's Night Club",
 'Backstage Live',
 'Backyard on Broadway',
 'Badlands Saloon',
 'Bamboo Room',
 'Baptist Temple Church',
 'Bar 414',
 'Bar America',
 'Bar Rojo at The Grand Hyatt Hotel',
 "Barclay's Piano Bar",
 "Barney's-Bandera",
 'Barriba Cantina',
 'Beethoven Maennerchor Halle Und Garten',
 "Bentley's",
 "Beto's Comida Latina",
 'Bier Garten Riverwalk',
 'Big Apple Night Spot',
 'Big Band Fun Club',
 "Big Bob's Burgers",
 'Big Texas Ice House',
 'Bihl Haus Arts',
 'Billy Blues BBQ',
 "Billy D's Club",
 'Billy Marbles',
 'Black Canteen',
 'Black Clover Pub',
 'Black Orchid',
 'Blanco Ballroom',
 'Blind Tiger Comedy Club',
 'Blossom Athletic Center',
 'Blue Note Club',
 'Blue Note Lounge',
 'Blue Star Brewing Co.',
 'Bluebonnet Palace',
 "Bo's Rodeo",
 'Boardwalk Bistro',
 "Bogart's",
 "Bohanan's Prime Steaks & Seafood",
 'Boiler House Texas Grill & Wine Garden',
 'Bombay Bicycle Club',
 "Bond's 007 Rock Bar",
 'Bone Club',
 'Boneshakers Tap House and Pizzeria',
 'Bonham Exchange',
 "Bonnie Jean's",
 'Boozehounds',
 'Botika Peruvian-Asian Restaurant',
 'Bottom Bracket Social Club',
 'Bottom Line',
 "Boudro's Texas Bistro",
 'Bowlero',
 'Brackenridge Park',
 "Brandi's Piano Bar",
 'Brass Monkey',
 'Braun Hall',
 "Brazakka's Reef",
 'Brews Brothers',
 'Brick at Blue Star Arts Complex',
 'Briscoe Western Art Museum',
 'Broad Street',
 "Broadway Turk's",
 'Brooklyn Street Bar and Grill',
 'Brooks Pub',
 "Brooster's Backyard IceHouse",
 "Buckley's Jazz Bar",
 "Bucko's Boardroom",
 "Buddy's Ize House",
 "Budro's",
 'Bull Moose',
 'Burgundy Woods',
 'Burleson Yard Beer Garden',
 'Burnhouse Cigar & Martini Lounge',
 'Burro Land',
 'Bwana Dik',
 'Cabaret',
 'Cactus Beer Garden',
 'Cactusland Brewery',
 'Cadillac Bar',
 'Cafe Americain',
 'Cafe Shalom International Coffee House',
 'Caliente Harley-Davidson',
 'Cameo Theater',
 'Candlelight Coffeehouse & Wine Bar',
 'Cantina del Rio',
 "Cardi's",
 'Carlsbad Tavern',
 "Carmen's de la Calle",
 'Carmens de la Calle',
 'Carousel Court Shopping Center',
 'Carver Community Cultural Center',
 'Carver Library Auditorium',
 'Casablanca',
 'Casbeers',
 'Casbeers at the Church',
 "Casey's Saloon and Dance",
 'Casino Club',
 'Castle Hills Baptist Church',
 'Castle Hills Market Shopping Center (Two locations - (2211 NW Military Highway)',
 'Cattlemen Square Tavern',
 'Central Park Mall',
 'Chance Are Lounge',
 'Chandelier Club',
 'Chapel of the Incarnate Word',
 "Charlie Brown's Neighborhood Bar & Grill",
 'Charline McCombs Empire Theatre',
 "Chaser's",
 'Cheers',
 'Chelsea Street',
 'Cherrity Bar',
 'Cibolo Creek Country Club',
 'Cibolo Nature Center',
 'Circle B&R',
 'City Limits Cantina',
 "Clay's Ice House",
 "Clem's Old Fashioned Barbeque",
 'Clown Alley',
 'Club 181',
 'Club Abrazo',
 'Club Country',
 'Club Eldorado',
 'Club Iries',
 'Club Miami',
 'Club Movida',
 'Club Oasis',
 'Club Reflex',
 'Club Ricardo',
 'Club Rico',
 'Club Ron Rico',
 'Club Sirius',
 'Club Vortex',
 'Co Lab',
 'Cobalt Club',
 'Coco Beach',
 'Comanche Ice House',
 'Comanche Park',
 'Come On Inn',
 'Conglomeration',
 "Connor's Night Club",
 "Conroy's Irish Pub",
 'Continental Cafe',
 "Conway's",
 "Cooter Brown's",
 'Cooter Browns Saloon',
 "Cootey's Tavern",
 'Corner Pocket Bar',
 'Cottonwood Country Club',
 'Country Cabaret',
 'Country Down Under',
 'Country Gold',
 'Country Road Ballroom',
 'Country on the Rocks',
 'County Line - Downtown',
 'County Line- I 10',
 'Courtyard',
 'Cowboys Dance Hall',
 'Coyote Ugly Saloon',
 "Coyote's",
 "Crabby Jack's",
 "Crazy Darryl's",
 'Crazy Horse Saloon',
 "Crazy J's Sports Bar",
 'Crockett Park',
 'Crumpets Restaurant & Bakery',
 'Crystal Sea Drama Co Inc',
 'Cuatro Aces',
 'Cured at Pearl',
 "Cyrano's",
 "D'Angelo's",
 'DMZ Clubhouse',
 "Da Silva's",
 "Dad's",
 "Dad's Karaoke",
 "Daddy's",
 'Daiquiri Lounge',
 'Danceland',
 "Daniel's Brooklyn Street",
 'Deco Pizzeria',
 'Deer Crossing Saloon',
 'Denim and Diamonds',
 'Deol Bar',
 'Desperado',
 "Dick's Last Resort",
 "Doc Holliday's",
 'Dog and Pony Grill',
 'Dominion Country Club',
 'Don Strange Ranch',
 'Dos Guys',
 'Downtown San Antonio (Alamo Address inputted)',
 "Doza's",
 'Draft Station at Sonterra',
 'Drink Texas Bar',
 'Drink Texas Stone Oak',
 "Durdy Annie's (Americana Inn)",
 "Durty Nelly's Irish Pub",
 "Eagle's Hall",
 'Earl of Country',
 'Eastwood Country Club',
 'Edge of Town',
 'Edwards Ridge Distillery',
 "El Antonio's Hacienda Ballroom",
 'El Cabaret',
 'El Camaroncito',
 'El Caribe',
 'El Chamizal Nightclub',
 'El Fandango',
 'El Jarro',
 'El Luchador Bar',
 'El Machito',
 'El Rancho Nite Club',
 'El Taxco',
 'El Tropicano Nite Club',
 'El Venadito Club',
 'Elbow Room',
 'Element Ultra Lounge',
 'Embers Wood Fire Grill & Bar',
 "Engle's Place",
 'Epic Bar',
 'Erwin Events Center',
 'Esperanza Peace & Justice Center',
 "Eva's Cozy Spot",
 'Evil Olive Elixir Lounge',
 'Fantastic 60s',
 'Far West Event Center',
 'Far West Rodeo',
 "Farmer's Daughter",
 'Farmers Market',
 "Fatso's BBQ",
 "Fatso's Sports Garden",
 'Faust Brewery',
 'Feast Restaurant',
 "Fiasco's",
 'Fiesta Ballroom',
 'Fiesta Club',
 'Fiesta Plaza',
 "Fitzgerald's Bar and Live Music",
 'Five Stones Artisan Brewery',
 'Flying Saucer Draught Emporium',
 'Fountain Bleu Banquet Hall',
 "Fralo's Art of Pizza",
 "Franco's Lounge",
 "Frankie G's Sports Bar",
 'Freeman Coliseum',
 'Freetail Taproom',
 'Freiheit Country Store',
 'Frost Bank Center',
 'Fuggawi',
 'Fun Palace',
 'G.W. Carver Library Auditorium',
 'GIG on the Strip',
 "Gallagher's",
 'Garden Tea Lounge',
 'Gasoline Alley',
 'Gemini Ink',
 "Gennie's Lounge",
 "George's Keep",
 'Golden Stallion',
 "Graffiti's",
 'Graham Central Station',
 'Grasshopper Club',
 'Grayze on Grayson',
 'Great Jubilations',
 'Gruene Hall',
 'Guadalupe Brewing Company',
 'Guadalupe County Coliseum',
 'Guadalupe Theatre',
 'H&R',
 'HEAT Nightclub',
 'Hacienda Salas',
 'Half Price Books-Fredericksburg',
 'Hallelujah Hollywood',
 "Hangin' Tree Saloon",
 'Hard Rock Cafe | San Antonio',
 'Hard Times Saloon and Party House',
 'Harem Skarem',
 'Helotes Event Hall',
 'Helotes Inn',
 'Hemisfair Park',
 'Hemisfair Plaza',
 'Hemisfair Theatre for the Performing Arts',
 'Henry B. Gonzalez Convention Center',
 'Here it Tiz',
 'Hi-Tones',
 'High Tide',
 'Hill Country Farmers Market',
 'Hilton Palacio del Rio',
 'Historic Jackson Ranch',
 'Historic Pearl',
 'Historic Sunset Station',
 'Holiday Club',
 'Hollywood Cafe',
 'Hookah House At Bentleys',
 "Hooligan's Bar & Grill",
 'Hot Joy',
 'Hot Shot Night Club',
 'Hot Tin Roof',
 'Hotel Discotheque',
 'Hotel Havana',
 'Howl at the Moon',
 "Huey's",
 'Hyatt Hill Country Resort',
 'IWC Auditorium',
 'Iguana Bay Bar & Grill',
 'Illusions Night Club',
 'Illusions Theatre at the Alamodome',
 'Imagine Books & Records',
 'Incarnate Word High School',
 'Inner City Development',
 'Institute of Texan Cultures',
 'Instituto Cultural Mexicano',
 'International Folk Culture Center',
 'Irish Pub',
 'Iron Armadillo',
 'Iskcon Mission Society',
 'Ivory Lounge & Nightclub',
 "Izzy's Party House",
 'JAM Factory',
 "JJ's",
 "JK's",
 'JW S Bracken Saloon',
 'Jack Rabbit',
 "Jack's Bar",
 "Jack's Corner Nite Club",
 "Jaime's Place",
 "Jandro's Garden Patio",
 'Javelina Harley-Davidson (Boerne)',
 'Jazz, TX',
 'Jefferson United Methodist Church',
 "Jerry Dean's",
 'Jiggers',
 "Jilly's",
 'Jimenez Restaurant and Bar',
 'Jo Long Theatre',
 "Joe Blue's",
 "Joe's Blues",
 "Joe's Corner Saloon",
 "Joe's Volcano",
 "John T. Floore's Country Store",
 'Johnny Lew Ice',
 'Jolly Joker',
 "Josabi's Acres",
 "Joseph's Foodliner",
 'Josephine Theatre',
 "Judge's",
 'Juniper Tar',
 'Just Country',
 'K T Dance Hall',
 'K23 Gallery',
 'KAPE 1480 Radio Station',
 'KFHM-AM San Antonio',
 'Kelly Bar Patio',
 'Kelly Field Terrace',
 "Kelly's Archway",
 'Kendalia Halle',
 'Kendall County Fairgrounds',
 'Keyhole (#1)',
 'Keyhole (#2)',
 'Keystone Club',
 'King Armadillo',
 "King Arthur's Court",
 "Kirby's Steakhouse",
 'Klub Amnesia',
 'Knave Pub',
 'Knight Time Lounge',
 'Kopy Kat Klub',
 "Krause's Cafe and Biergarten",
 "Krueger's Bar and Party House",
 'LUNA',
 'La Bamba Super Nite Club',
 'La Botanica',
 'La Fonda on Main',
 'La Fuente Super Ballroom',
 'La Playa',
 'La Quinta Inn and Suites Riverwalk',
 'La Rancherita Night Club',
 'La Rumba Nite Club',
 'La Tuna Grill',
 'La Tuna Icehouse',
 'La Vernia Chamber of Commerce Hall',
 'La Villita',
 'La Villita Assembly Hall',
 'La Villita Historic Arts Village',
 'Laboratory Brewing Company',
 'Lackland Air Force Base',
 'Lamp Post Lounge',
 'Lanier High School',
 "Larry's Cantina",
 "Larry's Lounge",
 'Lartos Lounge',
 'Las Canarias',
 'Las Chiladas',
 'Las Ramblas at The Hotel Contessa',
 'Las Vegas Night Club',
 'Last National Bank',
 'Last Stand',
 'Laugh Out Loud Comedy Club',
 'Laurel Heights United Methodist Church',
 'Laurie Auditorium',
 'Le Bistro Restaurant and Bar',
 'Lejac Club',
 'Leon Springs',
 'Leon Springs Café',
 'Leon Springs Dance Hall',
 'Leon Valley Bar and Grill',
 "Lerma's Nite Club",
 "Let's Go Bottom Up",
 "Li'L Hut Lounge",
 'Liberty Bar',
 'Lila Cockrell Theatre',
 'Limelight',
 "Limon's Lounge",
 "Lindbergh's",
 'Lion and Rose British Restaurant and Pub - Park North',
 'Lion and Rose British Restaurant and Pub -La Cantera',
 'Little Italy Restaurant',
 'Little Jamaica Bar and Grill',
 'Little Las Vegas Club',
 'Little Nashville',
 'Little Red Barn Steakhouse',
 'Live Oak Civic Center',
 'Local Motion',
 'Lone Star Corral',
 'Lonely Ladies',
 'Lonestar Pavillion',
 'Loose Screws',
 'Los Barrios Mexican Restaurant',
 'Los Mesquites',
 'Los Padrinos',
 'Loyalty Lounge',
 "Luther's Cafe",
 'Luxello Hall',
 "Lyndy's Great Indoors",
 'MacArthur Field - Fort Sam Houston',
 'Mad Dogs British Pub Riverwalk',
 "Mad Michael's",
 "Maggiano's Little Italy San Antonio",
 "Maggie's",
 'Mai Tai',
 'Main Plaza (San Antonio)',
 'Main Plaza Conservancy- San Antonio',
 'Main Street',
 'Majestic Theatre',
 'Make My Day Lounge Make sure to use 12114 Nacogdoches Rd',
 'Manana',
 'Mantle Art Space',
 'Margaritaville',
 'Mariachi Bar',
 "Mario's Mexican Restaurant",
 'Market Square',
 'Martinez Social Club',
 'Martini Ranch',
 "Marty's Outback",
 "Marty's Veranda",
 "Mary's CafÃ©",
 'Matamoros Restaurant y Cantina',
 'Mateo Camargo Park',
 'Maverick Music Festival',
 'Maverick Plaza, La Villita',
 "Max's Lil'B",
 "Max's Wine Dive",
 'McNay Art Museum',
 'Mcqueeney Hall',
 'Medieval Knights',
 'Medina County Fairgrounds',
 "Mel's",
 "Melody's",
 "Mendiola's Ballroom",
 'Menger Hotel',
 'Menudo Acres',
 'Metropolitan Opera House',
 'Midnight Cowboy (Hemisfair Plaza)',
 'Midnight Rodeo',
 'Midtown',
 "Milo's Backyard",
 'Mine Shaft Saloon - Inside Magic Time Machine',
 'Mission County Park',
 "Moe's Lounge",
 "Monterrey Jack's-Ingram",
 "Morgan's Wonderland",
 "Moses Rose's Hideout",
 'Moulin Rouge Lounge',
 'Movement Gallery/Galeria del Movimiento',
 'Mrs. Samuel J. Perkins (House)',
 'Musical Arts Center of San Antonio, Inc. (1604)',
 'Musical Arts Center of San Antonio, Inc. (I-10)',
 'Mustang Lounge',
 'Naked Iguana Tequila Bar',
 "Nana's Grill",
 "Neal's Ice House",
 'Nesta Dive Bar',
 'Network for Young Musicians',
 'Newsroom',
 "Nibble's Eatery",
 'Nightrocker',
 'Noche Caliente',
 "Nona's",
 'Norma Jean',
 'North Star Mall',
 'Number 10 Club',
 "O'Neill's Irish House",
 "O'Riley's",
 'Oak Grove Hall',
 'Oak Hills',
 'Oak Hills Country Club',
 'Ocho at Hotel Havana',
 'Old Spanish Inn',
 'Old Tin Barn Saloon',
 "Olivia's",
 'Olmos Basin Park',
 'Olmos Club',
 'Olmos Pharmacy',
 'On The Rocks Pub',
 "Orphan Annie's Lounge",
 'Oxtail Inn',
 "PJ's",
 "Pablo's Grove",
 "Paesano's 1604",
 'Palo Alto College Performing Arts Center',
 'Pan Am Plaza',
 'Pan American Nite Club',
 "Panama's Red",
 "Pandora's",
 'Paper Tiger',
 "Pappy's",
 'Paramour Bar',
 'Patio Bar and Grill',
 "Patsy's Ice House",
 "Paul's Place",
 'Pearl Stable',
 "Pedrotti's North Wind Ranch",
 "Pelican's Landing",
 "Pennie's Lounge",
 "Pepe's Cantina",
 'Perch Coworking Space',
 'Perfect Timing Night Club',
 'Performing Arts San Antonio',
 'Pericos Mexican Restaurant',
 "Perry's Steakhouse and Grille",
 'Peters Brothers',
 'Phazez',
 'Picks Bar',
 'Pittman-Sullivan Park',
 'Planeta Mexico',
 'Playa Santa Maria',
 "Player's Club",
 'Playpen North',
 'Plaza Guadalupe',
 'Plaza Nueva',
 'Plaza de Armas Gallery',
 'Poco Loco',
 "Posey's Pasture",
 'Pour House',
 'Powerhouse CafÃ©',
 'Prelude Club',
 'Prize Bull Saloon and Dance Hall',
 'Pueblo Hall & Activity Center',
 'Pullman Inn',
 'Pump House Lounge',
 'Pusi Kat',
 'Quiet Valley Ranch',
 'Quihi Gun Club and Dance Hall',
 'R & J Lounge',
 'R & J Lounge Music Pavillion',
 'R & R Ice House',
 'R&J Music Pavilion',
 'R&J Saloon',
 'R&R Bar and Grill',
 "RC Peacock's",
 'Radius Cafe',
 'Radius Center',
 'Raffles Restaurant and Bar',
 'Rainbow Cafe',
 'Rancho 181',
 'Rancho Bar',
 'Random Beer Garden',
 "Randy's",
 "Rascal's Night Club",
 "Raul's",
 'Rawpower and Light Company',
 "Ray's Ice House",
 'Razz Club',
 'Razzle Dazzle',
 'Rebar',
 'Recovery Room',
 'Red Cobra Country Club',
 "Reed's Red Derby",
 "Remington's",
 'Repitlez Sports Bar',
 'Reptilez Live Music Venue',
 'Republique of Boko-Maru',
 'Retama Park',
 'Retox Bar',
 'Reverb Lounge',
 'Rhino Room',
 "Ricardo's Cadillac",
 "Ricardo's on the River",
 'Riff House Concerts',
 'Rio Cibolo Ranch',
 'Ritmo Latino',
 'River Road Ice House',
 "Roaring 20's",
 'Rock Bottom Tattoo Bar',
 'Rock Island',
 'Rock and Rye',
 'Rocking M Dude Ranch',
 'Rockwave',
 "Rocky Joe's-Kerrville",
 "Rocky's",
 'Rolling Oaks Sports Bar & Grill',
 "Rosario's CafÃ© y Cantina",
 'Rosedale Park',
 "Rosie O'Grady's",
 'Round Table Club',
 "Rouring 20's",
 'Roxy Sports Bar',
 'Royal Palace Ballroom',
 "Ruben's Place",
 "Ruffino's",
 'Rusty Nail Saloon',
 'Ruth Taylor Theater',
 "Ruth's Chris Steak House â€“La Cantera",
 "Ruth's Chris Steak House-Concord Plaza",
 "Ruth's Chris Steak House-Grand Hyatt",
 'SA Country Saloon',
 'SAY Si',
 'SBC Center',
 'SIN 13',
 "Sadler's Tent Theater",
 'Saengerhalle',
 'Sahari Club',
 'Salute',
 "Sam's Burger Joint",
 "Sam's Town Point",
 'San Antone Cafe and Concerts',
 'San Antonio Botanical Garden',
 'San Antonio Club',
 'San Antonio College',
 'San Antonio Convention Center Arena',
 'San Antonio Country',
 'San Antonio Country Club',
 'San Antonio Event Center',
 'San Antonio Japanese Tea Garden',
 'San Antonio Municipal Auditorium',
 'San Antonio Museum of Art',
 'San Antonio Music Company',
 'San Antonio Raceway',
 'San Antonio Shrine Auditorium',
 "San Antonio's Opportunities Industrialization Center",
 'San Fernando Cathedral',
 'Sanchos Cantina & Cocina',
 "Sandra's Bar & Live Music",
 "Santa's Place",
 'Scenic Loop Cafe',
 'Schreiner University',
 'Scobee Education Center',
 'Scout Bar',
 'Scratch',
 'Sea World of Texas',
 'Semeneya Ballroom',
 'Serape Club',
 'Seven Oaks',
 'Shadowland Club',
 'Shenanygans -Sports Bar & Lounge',
 "Short's Corner",
 'Showcase Events Center',
 'Silver Dollar Saloon',
 'Silver Fox (Leon Springs)',
 'Silver Saddle',
 'Six Flags Fiesta Texas',
 'Skate Center South',
 "Skip Willy's",
 'Skit Row',
 'Slackers Sports Bar Naco',
 'Slackers Sports Bar North star',
 'Smoke: The Restaurant',
 'Sneak Spot',
 'Sneakers',
 "Sneaky Pete's",
 "Snoop's Tavern",
 'SoHo Wine & Martini Bar',
 'Social House',
 'Somerset Road',
 'Soundcheck',
 'South Texas Museum of Popular Culture',
 'Southern Lady',
 'Southtown 101',
 'Southtown Vinyl',
 'Southwest School of Art',
 "Sparky's Pub",
 "Specht's Store",
 'Speedway Sports Bar',
 'Speedway Sports Bar II',
 'Splashtown',
 'Squeeze Inn',
 "St. Albert's Hall",
 'St. Anthony Hotel',
 'St. Hedwig Hall',
 "St. Henry's Catholic Church",
 'St. James New Hall',
 "St. Luke's Episcopal Church",
 'St. Mary University Treadway Recital Hall',
 "St. Mary's Bar and Grill",
 "St. Mary's Brewing Company",
 "St. Mary's Pit",
 "St. Mary's University",
 'Stardust Ballroom',
 'Station Break',
 "Steely Nevada's Bar and Lounge",
 'Stetson Bar',
 'Stonehenge',
 'Strutters',
 'Studio 210 Nightclub and Bar',
 'Studio 57',
 'Suburban Club',
 'Suburban Garden(s)',
 "Suga A's Lounge",
 "Sugar Daddy's",
 "Sum'thin Diff'Rent",
 'Sumthin Different',
 'Sunken Garden',
 'Sunken Garden Theater',
 'Sunova Beach',
 'Swank Club',
 'Swizzle Stick',
 'Swizzle Stick Lounge',
 'TACOLAND',
 'Tabasco Beach',
 'Taco Garage',
 'Tacos & Tequila',
 'Tandem San Antonio',
 'Taqueria La Gloria- Pearl',
 "Taylor's Tavern",
 'Teddy Bear Lounge & CafÃ©',
 'Teen Canteen',
 'Tejano Cactus',
 'Tejano Explosion',
 'Tejano Explosion 2015',
 'Tejano Rodeo',
 'Tejano Texas',
 'Tejas Rodeo, Steakhouse and Saloon',
 'Tequila Mockingbird',
 "Terry's Lounge",
 'Texas 21 Funhouse',
 'Texas Burgers, Brews, and Blues',
 'Texas Dance Hall',
 "Texas Ex's",
 'Texas Star Inn',
 'Texas Theater',
 'Texco Nite Club',
 'The 4 Way Bar and Grill',
 'The Amp Room',
 'The Aquaduck',
 'The Art Institute of San Antonio',
 'The Bang Bang Bar',
 'The Bar on Broadway',
 'The Bayous',
 'The Beauregard Cafe',
 'The Beer Depot',
 'The Bijou',
 'The Brass Tap',
 'The Broadway 50 50',
 'The Brooklynite',
 'The Carver Community Cultural Center â€“ The Jo Long Theatre for Performing Arts',
 'The Catacombs',
 'The Classic Theater',
 'The Copper Penny',
 'The Corral',
 'The Courtyard',
 'The Cove',
 'The Crazy Ape',
 'The Davenport Lounge',
 'The DoSeum',
 'The Edge',
 'The Friendly Spot Ice House',
 'The FruterÃ\xada -Botanero',
 'The Gambler',
 'The Garter North',
 'The Good Kind-Southtown',
 'The Good News',
 'The Gunter Hotel',
 'The Hangar Bar',
 'The Hangout',
 'The Hoppy Monk',
 'The Industry',
 'The Jackson Ranch in the Heart of San Antonio',
 'The Junction',
 'The Korova',
 'The Landing',
 'The Latin Corner',
 'The Local Bar',
 'The Lonesome Rose',
 'The Longneck Saloon',
 'The Martini Club',
 'The Meridian',
 'The Mix',
 'The Monty and Ivy Hall',
 'The Nash',
 'The Nestle Inn',
 'The Opera House',
 'The Other Women',
 'The Phantom Room',
 'The Pigpen',
 'The Public Theater of San Antonio',
 'The Reggae Bar',
 'The Replay Sports Club',
 'The Republic House',
 'The Ringer Pub',
 'The Rock',
 'The Rock Box',
 "The Rockin' K",
 'The Roundup',
 'The Rustic',
 'The Sanctuary',
 'The Service Station Cafe and Beer Garden',
 'The Settlement',
 'The Shadows',
 'The Showcase',
 'The Silver Slipper Nite Club',
 'The Squeezebox',
 'The Stetson Bar',
 'The Stonehenge',
 'The Ten Eleven',
 'The Three-Legged Monkey',
 'The Trap',
 'The Twig Book Shop',
 'The Underground Metal Haven',
 'The Vineyard Club',
 'The Warehouse',
 'The Warehouse Music Venue',
 'The Well',
 'Third Wave',
 'Thirsty Camel Bar & Lounge',
 'Thirsty Horse Saloon',
 'Thiry Auditorium, Our Lady of the Lake University',
 'Three Walls',
 'Ticket Sports Pub',
 'Tiffany Lounge',
 'Tiffany Palace',

We have some other clear inconsistencies visible on inspection, such as

```
'Repitlez Sports Bar',
'Reptilez Live Music Venue',
```

So, we will need a bit of human TLC here.

The question remains how and from where I derived the `Venues No Address` sheet. It is clear that this was at the start of summer 2025, when the issue of venues without coordinates was raised and work was begun on resolving it.

In [118]:
len(venues_from_ven_ev_ar_address - venues_from_layer_1_venues)

1079

Here is the answer. If we do the set difference between all the venues in `ven_ev_ar_address` and all the venues in `layer 1 venues` we find that there are 1079 venues in `ven_ev_ar_address` that are *not* in `layer 1 venues`. The number of rows in `Venues No Address` is 1079. This makes it clear that what I did is look up venues in `ven_ev_ar_address` that had no address. The venues that do have an address on this list are all derived from `Layer 1 Venues`. In other words, originally venue addresses and coordinates were placed on the Layer 1 Venues sheet, and wherever there was a match in `ven_ev_ar_address`, imported there. All the venues in `ven_ev_ar_address` that are not in `Layer 1 Venues` have no address.

This might have improved subsequently. Originally, as we have seen, only 313 venues in `Layer 1 Venues` had addresses; this was subsequently raised to 964, and the resulting new venue coordinates were imported directly to the Redis database that underlies the Sounds of San Anto "Get Lost" project. But the spreadsheet was never altered; the new venue coordinates live only in the `venues_with_coordinates` sheet.

I'll test this hypothesis by finding out how many venues in `ven_ev_ar_address` have no address. First, I'll find out the exact column names in this data frame. Then I'll created a filtered data frame with just the entries that have no address. Then I'll get the list of unique venues in that list. It is 1078 venues. So that is definitely the source of my "Venues No Address" sheet: a search of `ven_ev_ar_address` for all venues with no address.

In [119]:
ven_ev_ar_address.columns

Index(['Index', 'Month', 'Day', 'Year', 'Venue', 'Event_Artists', 'Address',
       'Zip', 'Longitude', 'Latitude', 'Artist', 'Event', 'City', 'State'],
      dtype='str')

In [120]:
missing_address = ven_ev_ar_address[
    ven_ev_ar_address["Address"].isna() 
]

missing_address = set(sorted(missing_address["Venue"].dropna().unique()))

print(f"{len(missing_address)} venues with no address:")
print(missing_address)

1078 venues with no address:

However, it's not that simple. Our issues run a bit deeper than that. There are venues that have an address but have no coordinates. If we run the same analysis, but look for venues that lack coordinates, we find 1471 venues. There are 393 venues that have an address but no coordinates.

We should also keep in mind that, when, eventually (December 2025) the R tidyverse library was used to add missing address and coordinate data, it was based on τhe Layer 1 Venues sheet, and not from the Venues No Address sheet I had generated from `ven_ev_ar_address`. Even if that were not the case, I had not, at that time, realized we had an additional 393 venues with an address but no coordinates. So, it will be worthwhile now to unify all our data on venues, addresses, and coordinates and get a unified count of all missing and incomplete geolocation data.

In [121]:
missing_coords = ven_ev_ar_address[
    ven_ev_ar_address["Longitude"].isna() | ven_ev_ar_address["Latitude"].isna()
]

missing_coords = set(sorted(missing_coords["Venue"].dropna().unique()))

print(f"{len(missing_coords)} venues with no coordinates:")
print(missing_coords)

1471 venues with no coordinates:

In [122]:
missing_coords - missing_address

{'"Menudo Acres"',
 '1902 Nightclub',
 '321 Max',
 "Acapulco Sam's",
 'Accents',
 'Acquarium III',
 'After Midnight',
 'Alameda Theater',
 'Alamo Heights United Methodist Church',
 'Alamo Plaza',
 "Alexander's Bar and Café",
 "Alfred's",
 'Alzafar Shrine Temple',
 'American Legion Post 539',
 'Anaqua Room',
 "Andrew's 281 Live",
 "Annie & Ed's",
 'Antonian Ballroom',
 "Arthur's",
 "Arturo's Sports Bar & Grill",
 'Austin Municipal Auditorium',
 "BJ's Night Club",
 'Backstage Live',
 'Badlands Saloon',
 'Bamboo Room',
 'Baptist Temple Church',
 'Billy Blues BBQ',
 'Billy Marbles',
 'Black Orchid',
 'Blossom Athletic Center',
 'Boardwalk Bistro',
 "Bogart's",
 "Bonnie Jean's",
 'Bottom Line',
 'Brackenridge Park',
 "Brandi's Piano Bar",
 "Brazakka's Reef",
 'Broad Street',
 "Broadway Turk's",
 'Brooklyn Street Bar and Grill',
 "Buckley's Jazz Bar",
 "Bucko's Boardroom",
 "Buddy's Ize House",
 "Budro's",
 'Burro Land',
 'Bwana Dik',
 'Cabaret',
 'Cactus Beer Garden',
 'Cafe Americain',
 'Cafe Shalom International Coffee House',
 'Cameo Theater',
 "Cardi's",
 'Carlsbad Tavern',
 'Carmens de la Calle',
 'Carver Community Cultural Center',
 'Casbeers',
 'Casbeers at the Church',
 'Castle Hills Baptist Church',
 'Central Park Mall',
 'Chapel of the Incarnate Word',
 "Chaser's",
 'Cheers',
 'Cibolo Creek Country Club',
 'Circle B&R',
 'City Limits Cantina',
 "Clay's Ice House",
 "Clem's Old Fashioned Barbeque",
 'Clown Alley',
 'Club 181',
 'Club Abrazo',
 'Club Country',
 'Club Iries',
 'Club Miami',
 'Club Movida',
 'Club Oasis',
 'Club Reflex',
 'Club Ricardo',
 'Club Rico',
 'Club Ron Rico',
 'Club Vortex',
 'Coco Beach',
 'Comanche Ice House',
 'Comanche Park',
 'Conglomeration',
 "Cooter Brown's",
 'Country Cabaret',
 'Country Down Under',
 'Country Gold',
 'Country Road Ballroom',
 'Country on the Rocks',
 "Coyote's",
 "Crabby Jack's",
 "Crazy Darryl's",
 'Crazy Horse Saloon',
 "Crazy J's Sports Bar",
 'Cuatro Aces',
 "Cyrano's",
 'DMZ Clubhouse',
 "Da Silva's",
 "Daddy's",
 'Desperado',
 'Don Strange Ranch',
 'Dos Guys',
 "Doza's",
 "Durdy Annie's (Americana Inn)",
 'Earl of Country',
 'Eastwood Country Club',
 'El Cabaret',
 'El Camaroncito',
 'El Caribe',
 'El Chamizal Nightclub',
 'El Fandango',
 'El Venadito Club',
 'Elbow Room',
 'Erwin Events Center',
 "Eva's Cozy Spot",
 'Fantastic 60s',
 'Far West Rodeo',
 "Farmer's Daughter",
 'Farmers Market',
 "Fatso's BBQ",
 "Fatso's Sports Garden",
 "Fiasco's",
 'Fiesta Ballroom',
 'Fiesta Club',
 'Fiesta Plaza',
 'Fountain Bleu Banquet Hall',
 'Fuggawi',
 'GIG on the Strip',
 "Gallagher's",
 'Gasoline Alley',
 "Gennie's Lounge",
 'Golden Stallion',
 'Graham Central Station',
 'Great Jubilations',
 'Gruene Hall',
 'Guadalupe County Coliseum',
 'H&R',
 'Hacienda Salas',
 'Half Price Books-Fredericksburg',
 'Harem Skarem',
 'Hemisfair Park',
 'Hemisfair Plaza',
 'High Tide',
 'Hot Tin Roof',
 "Huey's",
 'IWC Auditorium',
 'Illusions Night Club',
 'Inner City Development',
 'Instituto Cultural Mexicano',
 'Iron Armadillo',
 "Izzy's Party House",
 "JJ's",
 "JK's",
 'Javelina Harley-Davidson (Boerne)',
 'Jefferson United Methodist Church',
 "Jerry Dean's",
 'Jiggers',
 "Jilly's",
 "Joe's Corner Saloon",
 'Johnny Lew Ice',
 'Jolly Joker',
 "Joseph's Foodliner",
 "Judge's",
 'KAPE 1480 Radio Station',
 'Kelly Bar Patio',
 "Kelly's Archway",
 'Kendalia Halle',
 'Kendall County Fairgrounds',
 'King Armadillo',
 "King Arthur's Court",
 'Klub Amnesia',
 'Knight Time Lounge',
 'La Bamba Super Nite Club',
 'La Fuente Super Ballroom',
 'La Villita',
 'La Villita Assembly Hall',
 'Laboratory Brewing Company',
 'Lanier High School',
 'Laurel Heights United Methodist Church',
 'Laurie Auditorium',
 'Le Bistro Restaurant and Bar',
 'Leon Springs',
 'Leon Springs Café',
 'Leon Springs Dance Hall',
 'Leon Valley Bar and Grill',
 "Lerma's Nite Club",
 'Little Nashville',
 'Live Oak Civic Center',
 'Local Motion',
 'Lone Star Corral',
 'Lonely Ladies',
 'Lonestar Pavillion',
 'Loose Screws',
 'Los Mesquites',
 'Los Padrinos',
 'Luxello Hall',
 'MacArthur Field - Fort Sam Houston',
 "Mad Michael's",
 "Maggie's",
 'Main Plaza (San Antonio)',
 'Main Street',
 'Martinez Social Club',
 'Martini Ranch',
 "Marty's Veranda",
 'Mateo Camargo Park',
 'Medieval Knights',
 "Mel's",
 "Melody's",
 'Menger Hotel',
 'Midnight Cowboy (Hemisfair Plaza)',
 'Midtown',
 'Mission County Park',
 "Moe's Lounge",
 'Mustang Lounge',
 'Naked Iguana Tequila Bar',
 "Nibble's Eatery",
 'Noche Caliente',
 "Nona's",
 'Norma Jean',
 'North Star Mall',
 "O'Neill's Irish House",
 "O'Riley's",
 'Oak Hills',
 'Old Spanish Inn',
 'Old Tin Barn Saloon',
 "Olivia's",
 'Olmos Basin Park',
 "Orphan Annie's Lounge",
 'Oxtail Inn',
 "PJ's",
 "Pablo's Grove",
 'Pan Am Plaza',
 "Pandora's",
 "Pappy's",
 'Patio Bar and Grill',
 "Patsy's Ice House",
 "Paul's Place",
 "Pelican's Landing",
 "Pennie's Lounge",
 "Pepe's Cantina",
 'Perfect Timing Night Club',
 'Phazez',
 'Pittman-Sullivan Park',
 'Planeta Mexico',
 'Playa Santa Maria',
 "Player's Club",
 'Plaza Guadalupe',
 'Plaza Nueva',
 "Posey's Pasture",
 'Pour House',
 'Powerhouse Café',
 'Prelude Club',
 'Quiet Valley Ranch',
 'Quihi Gun Club and Dance Hall',
 'R&R Bar and Grill',
 'Radius Cafe',
 "Randy's",
 'Rawpower and Light Company',
 'Razz Club',
 'Red Cobra Country Club',
 "Remington's",
 'Republique of Boko-Maru',
 'Retama Park',
 'Reverb Lounge',
 'Rhino Room',
 "Ricardo's Cadillac",
 'Ritmo Latino',
 'River Road Ice House',
 "Roaring 20's",
 'Rock Bottom Tattoo Bar',
 'Rock Island',
 'Rockwave',
 "Rocky Joe's-Kerrville",
 "Rocky's",
 'Rolling Oaks Sports Bar & Grill',
 "Rosie O'Grady's",
 'Royal Palace Ballroom',
 "Ruben's Place",
 "Ruffino's",
 'Rusty Nail Saloon',
 'Saengerhalle',
 'Sahari Club',
 'Salute',
 "Sam's Town Point",
 'San Antonio Convention Center Arena',
 'San Antonio Country',
 'San Antonio Japanese Tea Garden',
 'San Antonio Municipal Auditorium',
 'San Antonio Music Company',
 'San Antonio Raceway',
 "San Antonio's Opportunities Industrialization Center",
 'San Fernando Cathedral',
 'Schreiner University',
 'Scout Bar',
 'Scratch',
 'Semeneya Ballroom',
 'Showcase Events Center',
 'Silver Fox (Leon Springs)',
 'Silver Saddle',
 'Skate Center South',
 "Skip Willy's",
 'Skit Row',
 'Sneakers',
 "Sneaky Pete's",
 'Somerset Road',
 'Squeeze Inn',
 'St. Anthony Hotel',
 "St. Henry's Catholic Church",
 'St. James New Hall',
 "St. Luke's Episcopal Church",
 "St. Mary's Bar and Grill",
 "St. Mary's University",
 'Stardust Ballroom',
 'Station Break',
 'Stonehenge',
 'Strutters',
 'Studio 57',
 "Suga A's Lounge",
 'Sunova Beach',
 'Swizzle Stick Lounge',
 'TACOLAND',
 'Tabasco Beach',
 "Taylor's Tavern",
 'Teen Canteen',
 'Tejano Cactus',
 'Tejano Rodeo',
 'Tejano Texas',
 'Tequila Mockingbird',
 "Terry's Lounge",
 "Texas Ex's",
 'Texas Star Inn',
 'Texas Theater',
 'The Bayous',
 'The Beauregard Cafe',
 'The Bijou',
 'The Catacombs',
 'The Corral',
 'The Courtyard',
 'The Edge',
 'The Gambler',
 'The Gunter Hotel',
 'The Hangout',
 'The Junction',
 'The Landing',
 'The Latin Corner',
 'The Longneck Saloon',
 'The Meridian',
 'The Nash',
 'The Opera House',
 'The Public Theater of San Antonio',
 'The Republic House',
 'The Sanctuary',
 'The Shadows',
 'The Showcase',
 'The Ten Eleven',
 'The Trap',
 'The Warehouse Music Venue',
 'Third Wave',
 'Three Walls',
 'Tin Pan Alley',
 "Tra's Country",
 'Travis Park',
 'Travis Park Church',
 'Trinity Baptist Church',
 'Trinity Church',
 'Tropical Drink Company',
 'Turtle Creek Country Club',
 'Tuxedo Junction',
 'Union Jack',
 'Unique Recreation Ballroom',
 'VFW Post 4700 Sgt. William J. Bordelon Post',
 'VFW Post 76 Sam Houston Post',
 'VFW Post 8315 Cibolo Valley Post',
 'VFW Post 837 Highland Hills Southeast Post',
 'VFW Post 9186 Manuel Alvarado Post',
 "Ventura's Nite Club",
 'Verizon Wireless Amphitheater',
 'Villa Fontana Ballroom',
 'Village Inn',
 "Villareal's Ice House and Concert Grounds",
 'Villita Assembly Building',
 "Wacky's",
 "Waldo's",
 'Walton Buggy Works',
 'Wayfarer Lounge',
 'Who Knows Lounge',
 'Wings',
 'Witolds',
 'Woodlawn Park',
 "Yosemite Sam's",
 'Zig Zag',
 'Zombies'}

In [123]:
len(missing_coords - missing_address)

393

We're ready to construct our unique venue list. Let's go ahead and fuse our various sources.

In [124]:
unique_venues = venues_from_venue_artist_event | venues_from_layer_1_venues | venues_from_venues_with_coordinates

In [125]:
len(unique_venues)

2988

We have a total of 2988 venues. These are 2602 venues from the original `venue_artist_event` sheet, another 369 that are unique to `layer 1 venues`, and an additional 17 that are duplicates with alternative formatting or spelling from `venues_with_coordinates`.

I will double-check that my venue_artist_event data frame still has a date column. If the notebook has shut down and not been fully run again, that column may be gone. If it is gone, I'll add it again.

In [126]:
venue_artist_event.columns

Index(['Month', 'Day', 'Year', 'Venue', 'Event_Artists', 'Artist_Formula',
       'Event_Formulas', 'Index', 'date'],
      dtype='str')

In [127]:
venue_artist_event["date"] = venue_artist_event.apply(lambda row: str_date_to_iso(row['Month'], row['Day'], row['Year']), axis=1)

In [128]:
venue_artist_event.columns

Index(['Month', 'Day', 'Year', 'Venue', 'Event_Artists', 'Artist_Formula',
       'Event_Formulas', 'Index', 'date'],
      dtype='str')

As in the case of artists, I would like the first and last appearance dates of any given venue. On this occasion, I would even be interested to order the venue indexes that way, with the oldest-appearing venues indexed first, and the latest-appearing indexed last. We do have some venues with no concerts at all, listed out in Layer 1 Venues, those will come at the very end.

I'll get that information on first and last appearances, then sort by order of first appearance.

In [129]:
venue_dates = (
    venue_artist_event
    .groupby("Venue")["date"]
    .agg(
        first_appearance="min",
        last_appearance="max"
    )
    .reset_index()
)

In [130]:
venue_dates.head()

                              Venue first_appearance last_appearance
0                    "Menudo Acres"       1978-10-06      1978-10-07
1                         1033 Club       1991-06-24      1991-09-28
2      110 Broadway Building Office       1985-07-12      1987-08-10
3  11th Street Cowboy Bar (Bandera)       2007-07-14      2023-07-29
4                    136 South Acme       2023-03-04      2023-03-04

In [131]:
venue_dates = venue_dates.sort_values(
    by="first_appearance"
).reset_index(drop=True)

In [132]:
venue_dates.head(40)

,Venue,first_appearance,last_appearance
0,St. Mary's Catholic Church,1857-09-10,1857-09-10
1,Menger Hotel,1869-06-25,1980-01-26
2,San Pedro Park,1874-07-04,1991-11-02
3,"San Pedro Springs, Turner Hall",1874-10-09,1874-10-09
4,"Casino Hall, Turner Hall",1874-10-10,1874-10-10
5,"San Pedro Springs, Alamo Plaza, Casino Hall",1874-10-11,1874-10-11
6,Travis Park,1883-01-24,2021-09-25
7,Casino Hall,1883-01-31,1908-05-27
8,Turner Hall,1883-02-01,1900-04-19
9,San Pedro Springs Park,1883-03-24,1883-04-01
10,Jonas' garden,1883-05-13,1883-05-13
11,Mission Garden,1883-07-09,1886-10-23
12,Krisch's Hall,1886-01-24,1886-08-26
13,St. Mark's Episcopal Church,1886-02-26,2003-06-15
14,Turner Opera House,1886-03-31,1886-03-31
15,Dr. Jones residence,1886-04-02,1886-04-02
16,First Presbyterian Church,1886-04-13,1989-10-08
17,Hartmann's Pavillion,1886-04-17,1886-04-18
18,PF Simpson residence,1886-06-09,1886-06-09
19,Sommers Garden,1886-08-29,1886-08-29
20,Mahncke's Garden,1886-09-04,1886-09-12
21,Scholz's Garden,1886-09-05,1886-09-05
22,Beethoven Hall,1902-04-28,2023-08-04
23,Landa Park (New Braunfels),1906-04-22,1906-04-22
24,Grand Opera House,1907-03-21,1918-01-02
25,1902 Nightclub,1908-01-19,2023-10-26
26,Fort Sam Houston,1909-02-24,2017-11-10
27,Jourdanton,1909-09-23,1909-09-25
28,Royal Theater,1910-02-24,1912-12-16
29,Kirkpatrick residence,1910-03-02,1910-03-02
30,St. Anthony Hotel,1911-03-03,2022-05-26
31,YMCA Auditorium,1911-03-20,1911-03-21
32,Electric Park,1911-04-19,1911-05-01
33,Agudas Achim Synagogue,1911-05-07,1954-11-14
34,International Club,1911-05-15,1911-05-15
35,City Cemetery No. 4,1912-05-12,1912-05-12
36,St. Joseph's Hall,1912-06-12,1912-06-12
37,The Plaza,1912-12-16,1912-12-16
38,Travis Park Methodist Church,1913-05-06,1920-11-30
39,Alamo Plaza,1913-12-24,2005-05-02

Next, we'll give them unique indexes.

In [133]:
venue_dates.insert(
    0,
    "Index",
    range(1, len(venue_dates) + 1)
)

In [134]:
venue_dates.head()

   Index                           Venue first_appearance last_appearance
0      1      St. Mary's Catholic Church       1857-09-10      1857-09-10
1      2                    Menger Hotel       1869-06-25      1980-01-26
2      3                  San Pedro Park       1874-07-04      1991-11-02
3      4  San Pedro Springs, Turner Hall       1874-10-09      1874-10-09
4      5        Casino Hall, Turner Hall       1874-10-10      1874-10-10

The next thing we need to do is add the venues that have no concert dates associated with them. These are all located in the `Layer 1 Venues` and `venues_with_coordinates` sheets.

Earlier, I developed a set of all the unique venues, called `unique_venues`, and just now we got the complete list of all the venues that do have concert data associated. So we need to find the difference. I'll derive the set of venues that do have concerts as follows:

In [135]:
venues_with_concerts = set(venue_dates["Venue"])

Now I'll do a set difference between the complete list of venues and this list.

In [136]:
venues_no_concerts = sorted(unique_venues - venues_with_concerts)

In [137]:
len(venues_no_concerts)

386

To add these to the end of the current data frame, I will create a new data frame and then concatenate the two. This strategy uses exclusively pandas rather than regular Python code, and since pandas leverages the C language this is very fast and computationally efficient.

In [138]:
start = len(venue_dates) + 1

new_data = pd.DataFrame({
    "Index": range(start, start + len(venues_no_concerts)),
    "Venue": venues_no_concerts,
    "first_appearance": pd.NaT,
    "last_appearance": pd.NaT
})

In [139]:
all_venues_df = pd.concat(
    [venue_dates, new_data],
    ignore_index=True
)

In [140]:
all_venues_df.tail(50)

,Index,Venue,first_appearance,last_appearance
2939,2940,The Other Women,NaT,NaT
2940,2941,The Phantom Room,NaT,NaT
2941,2942,The Ringer Pub,NaT,NaT
2942,2943,The Rock,NaT,NaT
2943,2944,The Rockin' K,NaT,NaT
2944,2945,The Service Station Cafe and Beer Garden,NaT,NaT
2945,2946,The Settlement,NaT,NaT
2946,2947,The Silver Slipper Nite Club,NaT,NaT
2947,2948,The Squeezebox,NaT,NaT
2948,2949,The Three-Legged Monkey,NaT,NaT
2949,2950,The Twig Book Shop,NaT,NaT
2950,2951,The Underground Metal Haven,NaT,NaT
2951,2952,The Vineyard Club,NaT,NaT
2952,2953,The Warehouse,NaT,NaT
2953,2954,Thirsty Camel Bar & Lounge,NaT,NaT
2954,2955,Ticket Sports Pub,NaT,NaT
2955,2956,Tiffany Palace,NaT,NaT
2956,2957,Tonic Bar,NaT,NaT
2957,2958,Torres Dance Hall,NaT,NaT
2958,2959,Toyota Field San Antonio,NaT,NaT
2959,2960,Trading Post,NaT,NaT
2960,2961,Tramp's,NaT,NaT
2961,2962,Tre Trattoria,NaT,NaT
2962,2963,Treasures Events,NaT,NaT
2963,2964,Tropics Dinner Club,NaT,NaT
2964,2965,Twin Mountain Inn,NaT,NaT
2965,2966,Two Step Restaurant and Cantina,NaT,NaT
2966,2967,University Bowl,NaT,NaT
2967,2968,VFW Post 7108 Helotes Post,NaT,NaT
2968,2969,VIP's`,NaT,NaT
2969,2970,Velvet Turtle,NaT,NaT
2970,2971,Ventura San Antonio,NaT,NaT
2971,2972,Virginia's Ace-Hi-Lounge,NaT,NaT
2972,2973,Viva Tacoland,NaT,NaT
2973,2974,Vybrations Luxury Lounge,NaT,NaT
2974,2975,Water Street Oyster Bat,NaT,NaT
2975,2976,Watson Fine Arts Center,NaT,NaT
2976,2977,Wax Club Lounge,NaT,NaT
2977,2978,Weathered Souls,NaT,NaT
2978,2979,Web House Cafe & Bar,NaT,NaT
2979,2980,Web House Café & Bar,NaT,NaT
2980,2981,West Avenue Club & Sports Bar,NaT,NaT
2981,2982,Whiskey Cake,NaT,NaT
2982,2983,Wild Wild West,NaT,NaT
2983,2984,Willis Corner,NaT,NaT
2984,2985,Wyndham Garden Riverwalk,NaT,NaT
2985,2986,Yellow Rose Country and Western Bar,NaT,NaT
2986,2987,Zanzibar Nite Club,NaT,NaT
2987,2988,Zip 2 Five Sports and Spirits,NaT,NaT
2988,2989,Zombies Bar and Live Music Venue,NaT,NaT

And now we can take this information and write it to our Excel file as a new sheet.

In [141]:
with pd.ExcelWriter(
    "sounds_data_to_share.xlsx",
    engine="openpyxl",
    mode="a",
    if_sheet_exists="replace"
) as writer:
    all_venues_df